#!/bin/sh -eu

# askpass: configure or query askpass helper
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

abort_wrong_arguments() {
    usage "%s: wrong number of arguments\n" "$0"
    exit 2
}

parse_arguments() {
    arg_count=1
    is_query=false

    while getopts hq opt; do
	case $opt in
	    (h)
		usage
		exit 0
		;;
	    (q)
		arg_count=0
		is_query=true
		;;
	    (\?)
		printf "%s\n" "" >&2
		usage
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -ne $arg_count ]; then
	abort_wrong_arguments
    fi

    if [ $# -gt 0 ]; then
	askpass_helper=$1
    fi
}

usage() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
	printf "%s\n" "" >&2
    fi

    cat >&2 <<-EOM
	Usage: $0 ASKPASS_HELPER
	       $0 -h
	       $0 -q
	EOM
}

parse_arguments "$@"

if [ $is_query = true ]; then
    get-askpass
else
    set-askpass $askpass_helper
fi
