#!/usr/bin/env run-python
# -*- Mode: Python -*-

# brew-list-keg-only: print list of HomeBrew packages which are "keg-only"
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import json
import os
import subprocess
import sys

COMMAND = ['/bin/sh', '-c', 'brew info --installed --json 2>/dev/null']

s = subprocess.run(COMMAND, stdout=subprocess.PIPE).stdout.decode('utf-8')

if s:
    print('\n'.join([p['name'] for p in json.loads(s) if p['keg_only']]))
