#!/usr/bin/env python3

# brew-list-keg-only: print list of HomeBrew packages which are "keg-only"
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import json
import os
import subprocess
import sys

BREW = '/usr/local/bin/brew'
COMMAND = [BREW, 'info', '--installed', '--json']

if os.path.isfile(BREW):
    s = subprocess.run(COMMAND, stdout=subprocess.PIPE).stdout.decode('utf-8')
    print('\n'.join([p['name'] for p in json.loads(s) if p['keg_only']]))
else:
    print('{}: No such file'.format(BREW), file=sys.stderr)
    exit(1)
