#!/bin/sh -eu

# brew: run Homebrew with Artifactory settings scoped to this process
# Copyright (C) 2026  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CONFIG="$HOME/.config/homebrew/artifactory.sh"
HOMEBREW_DIRS="/opt/homebrew /usr/local /home/linuxbrew/.linuxbrew \
$HOME/.linuxbrew"

get_brew_command() {
    for dir in ${HOMEBREW_PREFIX-} $HOMEBREW_DIRS; do
	if [ -x "$dir/bin/brew" ] && [ "$dir/bin/brew" != "$0" ]; then
	    printf '%s\n' "$dir/bin/brew"
	    return 0
	fi
    done

    printf '%s: Homebrew not found\n' "$(basename "$0")" >&2
    return 1
}

brew=$(get_brew_command)

if [ -r "$CONFIG" ]; then
    . "$CONFIG"
fi

exec "$brew" "$@"
