#!/bin/sh -eu

# check-python.: check that Python version meets requirement
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

if [ $# -lt 1 ]; then
    abort "%s: Not enough arguments\n" "$0"
elif [ $# -gt 1 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

. utility-functions.sh

version="$("$1" --version | awk '{print $2'})"

if [ -n "$version" ]; then
    check_python "$1" "$version"
fi
