#!/bin/sh -eu

# chown-user: change owner of file to real user
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

chown_real_user() {
    user_name=$(get_real_user)

    if [ -n "$user_name" ]; then
        user_id=$(get_user_id $user_name)
	group_id=$(get_group_id $user_name)
	chown "$user_id${group_id:+:$group_id}" "$@"
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath || true)

    if [ -n "$realpath" ]; then
        $realpath "$@"
    else
        for file; do
            if expr "$file" : '/.*' >/dev/null; then
                printf "%s\n" "$file"
            else
                printf "%s\n" "$PWD/${file#./}"
            fi
        done
    fi
)

case "$0" in
    (*/*)
        script_dir=$(get_realpath "$(dirname "$0")")
        ;;
    (*)
        script_dir=
        ;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

chown_real_user "$@"
