#!/bin/sh -eu

# clean-pipenv: remove PipEnv virtual environments
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

clean_up_pipenv() {
    pipenv=$(get_command pipenv || true)

    if [ -n "$pipenv" ]; then
	if $pipenv --venv >/dev/null 2>&1; then
	    $pipenv --rm
	fi
    fi
}

usage_error() {
    printf "$@" >&2
    exit 2
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"
. "${script_prefix}utility-functions.sh"

export LANG=${LANG-en_US.UTF-8}
export LC_ALL=${LC_ALL-en_US.UTF-8}

if [ $# -gt 0 ]; then
    usage_error '%s: Too many arguments\n' "$script"
fi

set_user_profile "$script_dir"
clean_up_pipenv
