#!/bin/sh

# clean-up-zfs-snapshots: clean up ZFS snapshots on Solaris
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
}

clean_up_zfs_snapshots() {
    validate_platform
    snapshots="$(zfs list -t snapshot | awk 'NR > 1 {print $1}')"
    for snapshot in $snapshots; do zfs destroy -R $snapshot; done
}

validate_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (solaris)
		return
    		;;
	esac
    done

    abort_not_supported "Operating system"
}

eval $(get-os-release -x)

clean_up_zfs_snapshots
