#!/bin/sh -eu

# clean-up-virtualenv: remove Python virtual environments
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

clean_up_virtualenv() {
    for utility in ${pypi_utilities:-$PYPI_UTILITIES}; do
	case "$utility" in
	    (pipenv)
		run_unpriv "${script_prefix}clean-up-pipenv"
		;;
	    (pip)
		/bin/rm -rf ${VENV_DIRECTORY-venv}
		;;
	esac
    done
}

configure_platform() {
    case "${uname_kernel=$(uname -s)}" in
	(CYGWIN_NT-*)
	    pypi_utilities=pip
	    ;;
	(MINGW64_NT-*)
	    pypi_utilities=pip
	    ;;
	(*)
	    pypi_utilities=
	    ;;
    esac
}

usage_error() {
    printf "$@" >&2
    exit 2
}

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script=$(basename "$0")

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

if [ $# -gt 0 ]; then
    usage_error '%s: Too many arguments\n' "$script"
fi

eval $("${script_prefix}get-configuration" app.ini)
configure_platform
clean_up_virtualenv
