#!/bin/sh -eu

# configure-hyper-v-guest: configure Hyper-V guest resolution
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

GRUB_COMMANDS="grubby grub2-mkconfig update-grub false"
GRUB_CONFIG=/etc/default/grub
KERNEL_ARG=video=hyperv_fb:1920x1080
KERNEL_VAR=GRUB_CMDLINE_LINUX_DEFAULT
SED_FORMAT='s/\\(%s\\)="\\(.*\\)"/\\1="\\2 %s"/'

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

configure_grub() {
    if [ ! -e $GRUB_CONFIG ]; then
	return
    fi

    if [ -w $GRUB_CONFIG ]; then
        options=-i
    elif [ -r $GRUB_CONFIG ]; then
        options=
    fi

    if ! grep $KERNEL_ARG $GRUB_CONFIG; then
	sed ${options:+$options }"$(get_sed_expr $KERNEL_ARG)" $GRUB_CONFIG
    fi
}

configure_hyper_v_guest() {
    configure_platform

    if configure_grub; then
	update_grub
    fi
}

configure_platform() {
    vendor=$(get_hypervisor_vendor || true)

    case "$vendor" in
        (Microsoft)
            true
            ;;
        ('')
            abort "%s: No hypervisor detected\n" "$0"
            ;;
        (*)
            abort "%s: %s hypervisor not supported\n" "$0" "$vendor"
            ;;
    esac

    for command in $GRUB_COMMANDS; do
	if which $command >/dev/null 2>&1; then
            method=$command
	    break
	fi
    done
}

get_awk_command() {
    case "$kernel_name" in
        (SunOS)
            printf "%s" /usr/gnu/bin/awk
            ;;
        (*)
            printf "%s" /usr/bin/awk
            ;;
    esac
}

get_hypervisor_vendor() (
    awk="$(get_awk_command)"
    (lscpu 2>/dev/null | $awk -f "${script_prefix}get-hypervisor-vendor")
)

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
        $realpath "$@"
    else
        for file; do
            if expr "$file" : '/.*' >/dev/null; then
                printf "%s\n" "$file"
            else
                printf "%s\n" "$PWD/${file#./}"
            fi
        done
    fi
)

get_sed_expr() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]
    printf "$SED_FORMAT\n" "$KERNEL_VAR" "$1"
}

update_grub() {
    case "$method" in
	(grubby)
            grubby --update-kernel=ALL --args="$KERNEL_ARG"
	    ;;
	(grub2-mkconfig)
            grub2-mkconfig -o /boot/grub2/grub.cfg
	    ;;
	(update-grub)
            update-grub
	    ;;
    esac
}

case "$0" in
    (*/*)
        script_dir=$(get_realpath "$(dirname "$0")")
        ;;
    (*)
        script_dir=
        ;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

eval $("${script_prefix}get-os-release" -X)
configure_hyper_v_guest
