#!/bin/sh -eu

# configure-emacs: download and configure emacs
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

GNU_BASE_URL=https://mirrors.ocf.berkeley.edu/gnu

if [ -z "${EMACS_PREFIX-}" ]; then
    EMACS_PREFIX=/usr/local
fi

if [ -z "${EMACS_VERSION-}" ]; then
    EMACS_VERSION=26.3
fi

abort() {
    printf "$@" >&2
    exit 1
}

abort_invalid_prefix() {
    usage "%s: invalid prefix -- %s\n" "$0" "$*"
    exit 2
}

abort_invalid_version() {
    usage "%s: invalid version -- %s\n" "$0" "$*"
    exit 2
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

abort_too_many_arguments() {
    usage "%s: too many arguments -- %s\n" "$0" "$*"
    exit 2
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

configure_emacs() {
    validate_platform
    parse_arguments "$@"

    basename=emacs-$EMACS_VERSION

    archive_dir="$HOME/Downloads/GNU"
    build_dir="$HOME/Documents/build/$basename"
    src_dir="$HOME/Documents/src/GNU/$basename"

    filename=$basename.tar.xz

    pathname=$archive_dir/$filename
    url=$GNU_BASE_URL/emacs/$filename

    mkdir -p "$build_dir" "$(dirname "$src_dir")" "$archive_dir"

    if [ ! -r "$pathname" ]; then
	cd "$archive_dir"
	wget $url
    fi

    if [ ! -r "$src_dir/configure" ]; then
	cd "$(dirname "$src_dir")"
	tar -xvf "$pathname"
    fi

    if [ ! -r "$build_dir/config.status" ]; then
	cd "$build_dir"
        options=$(get_configure_options)
	"$src_dir/configure" ${options-} "$@"
    fi
}

get_configure_options() {
    case "$kernel_name" in
        (Linux)
            case "$ID" in
                (rhel|ol|centos)
		    case "$VERSION_ID" in
			(8|8.[01])
			    printf "%s\n" "--with-gif=no"
			    ;;
		    esac
		    ;;
            esac
	    ;;
    esac
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

parse_arguments() {
    is_forcing=false
    emacs_prefix=$EMACS_PREFIX
    emacs_version=$EMACS_VERSION

    while getopts fp:v:h opt; do
	case $opt in
	    (f)
		is_forcing=true
		;;
	    (p)
		case $OPTARG in
		    ($HOME|/opt/*|/usr|/usr/local)
			if [ -d $OPTARG ]; then
			    emacs_prefix=$OPTARG
			else
			    abort_invalid_prefix $OPTARG
			fi
			;;
		    (*)
			abort_invalid_prefix $OPTARG
			;;
		esac
		;;
	    (v)
		case $OPTARG in
		    (2[6789].[0-9]|2[6789].[1-9][0-9])
			emacs_version=$OPTARG
			;;
		    (*)
			abort_invalid_version $OPTARG
			;;
		esac
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		printf "%s\n" "" >&2
		usage
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))
}

usage() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
	printf "%s\n" "" >&2
    fi

    cat <<-EOF >&2
	Usage: $0 [-f][-p PREFIX][-v VERSION]
	       $0 -h
	EOF
}

validate_platform() {
    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian|ubuntu|linuxmint|neon|kali)
		    :
	    	    ;;
		(opensuse-*|fedora|rhel|ol|centos)
		    :
	    	    ;;
		(*)
		    abort_not_supported Distro
		    ;;
	    esac
	    ;;
	(FreeBSD|SunOS)
	    :
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

configure_emacs "$@"
