#!/bin/sh -eux

# configure-python: download and configure python
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


BASE_URL=https://www.python.org/ftp
PYTHON_VERSION=3.7.1

PYTHON_BASENAME=Python-$PYTHON_VERSION

ARCHIVE_DIR="$HOME/Downloads/Python"
BUILD_DIR="$HOME/Documents/build/$PYTHON_BASENAME"
SRC_DIR="$HOME/Documents/src/Python/$PYTHON_BASENAME"

PYTHON_FILENAME=$PYTHON_BASENAME.tar.xz

PYTHON_PATHNAME=$ARCHIVE_DIR/$PYTHON_FILENAME
PYTHON_URL=$BASE_URL/python/$PYTHON_VERSION/$PYTHON_FILENAME

abort() {
    printf "$@" >&2
    exit 1
}

kernel_name=$(get-os-kernel-name)

case "$kernel_name" in
    (Linux|FreeBSD|SunOS|NT)
	mkdir -p "$BUILD_DIR" "$(dirname "$SRC_DIR")" "$ARCHIVE_DIR"

	if [ ! -r "$PYTHON_PATHNAME" ]; then
	    cd "$ARCHIVE_DIR"
	    wget $PYTHON_URL
	fi

	if [ ! -r "$SRC_DIR/configure" ]; then
	    cd $(dirname "$SRC_DIR")
	    tar -xvf "$PYTHON_PATHNAME"
	fi

	if [ ! -r "$BUILD_DIR/config.status" ]; then
	    cd "$BUILD_DIR"
	    "$SRC_DIR/configure" "$@"
	fi
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac
