#!/bin/sh -eu

cd $HOME/git

if [ ! -d ctags ]; then
    git clone https://github.com/universal-ctags/ctags.git
fi

cd ctags

if [ ! -e configure ]; then
    ./autogen.sh
fi

if [ ! -e Makefile ]; then
    ./configure
fi

make
make install # may require extra privileges depending on where to install
find . -user root
