#!/bin/sh -eu

# configure-sbcl: download and configure Steel Bank Common Lisp
# Copyright (C) 2022  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

SBCL_ARCHIVE_DIR="$HOME/Downloads/SBCL"
SBCL_ARCHIVE_SUFFIX=.tar.bz2

SBCL_OPT_PREFIX=/opt/%s
SBCL_PROJECT_NAME=sbcl
SBCL_PROJECT_VERSION=2.5.3

abort() {
    printf "$@" >&2
    exit 1
}

abort_invalid_prefix() {
    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
}

abort_invalid_version() {
    usage_error '%s: invalid version -- %s\n' "$script" "$*"
}

abort_not_supported() {
    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

configure_paths() {
    archive_dirname="$SBCL_ARCHIVE_DIR"
    archive_basename=$SBCL_PROJECT_NAME-$version-source
    src_dirname="$HOME/Documents/src/SBCL/${archive_basename%-source}"
    archive_filename=$archive_basename$SBCL_ARCHIVE_SUFFIX
    archive_pathname="$archive_dirname/$archive_filename"
}

configure_sbcl() {
    umask 0022

    if [ "$force" = true ]; then
	/bin/rm -rf "$src_dirname"
    fi

    mkdir -p "$(dirname "$src_dirname")"
    extract_archive "$archive_pathname" "$src_dirname"
    cd "$src_dirname"

    if [ "$build" = true ]; then
	build_prefix=$(get_prefix)
	sh make.sh --prefix="$build_prefix"

	if [ "$docs" = true ]; then
	    (cd ./doc/manual && make)
	fi
    fi

    if [ "$check" = true ]; then
	(cd ./tests && sh run-tests.sh)
    fi
}

get_dependencies() {
    get-packages $SBCL_PROJECT_NAME-build
}

get_prefix() {
    printf "$prefix" "$SBCL_PROJECT_NAME-$version"
}

install_sbcl() {
    if [ "$install" != true ]; then
	return 0
    elif [ "$ID" != windows -a "$(id -u)" -gt 0 ]; then
	return 0
    fi

    umask 0022
    cd "$src_dirname"
    install_prefix=$(get_prefix)
    INSTALL_ROOT="$install_prefix" sh install.sh
    install_project_link "$install_prefix"
}

parse_arguments() {
    build=true
    check=false
    docs=false
    force=false
    install=false
    keep=false
    prefix=$SBCL_OPT_PREFIX
    version=$SBCL_PROJECT_VERSION

    while getopts bcdfiknp:v:h opt; do
	case $opt in
	    (b)
		build=true
		;;
	    (c)
		check=true
		;;
	    (d)
		docs=true
		;;
	    (f)
		build=true
		force=true
		;;
	    (i)
		install=true
		;;
	    (k)
		keep=true
		;;
	    (n)
		build=false
		force=false
		;;
	    (p)
		case $OPTARG in
		    ($HOME/.local|$LOCAL_PREFIX|$SBCL_OPT_PREFIX)
			prefix=$OPTARG
			;;
		    (*)
			abort_invalid_prefix $OPTARG
			;;
		esac
		;;
	    (v)
		case $OPTARG in
		    ([12].[1-9]|[12].[1-9].[1-9]|[12].[1-9].[1-9][0-9])
			version=$OPTARG
			;;
		    (*)
			abort_invalid_version $OPTARG
			;;
		esac
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error '%s: Too many arguments\n' "$script"
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script [-b] [-c] [-d] [-f] [-i] [-k] [-n] [-p PREFIX] [-v VERSION]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

validate_platform() {
    case "$ID" in
	(centos)
	    case "$VERSION_ID" in
		(7)
		    return
		    ;;
		(8)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    return
	    ;;
	(fedora)
	    return
	    ;;
	(opensuse-*)
	    return
	    ;;
	(rhel|ol|almalinux)
	    case "$VERSION_ID" in
		(7.*)
		    return
		    ;;
		(8.*)
		    return
		    ;;
		(9.*)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(rocky)
	    case "$VERSION_ID" in
		(7.*)
		    return
		    ;;
		(8.*)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(ubuntu)
	    return
	    ;;
	(freebsd)
	    return
	    ;;
	(illumos)
	    return
	    ;;
	(macos)
	    return
	    ;;
	(netbsd)
	    return
	    ;;
	(solaris)
	    return
	    ;;
	(windows)
	    return
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"
. "${script_prefix}config-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
validate_platform
parse_arguments "$@"
configure_paths

if [ "$keep" != true ]; then
    install_dependencies
fi

if [ "$(id -u)" -eq 0 ]; then
    run_unpriv /bin/sh -c "$0 $*"
else
    configure_sbcl
fi

install_sbcl
