#!/bin/sh -eux

# configure-uwsgi: download and configure uwsgi
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BASE_URL=https://projects.unbit.it/downloads
VERSION=2.0.17.1

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

basename=uwsgi-$VERSION

archive_dir="$HOME/Downloads/uWSGI"
src_dir="$HOME/Documents/src/uWSGI/$basename"

filename=$basename.tar.gz

pathname=$archive_dir/$filename
url=$BASE_URL/$filename

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

case "$kernel_name" in
    (Linux|GNU)
	case "$ID" in
	    (debian|raspbian|ubuntu|opensuse-*|fedora)
		:
	    	;;
	    (*)
		abort_not_supported Distro
		;;
	esac
	;;
    (FreeBSD|SunOS|CYGWIN_NT-*)
	:
    	;;
    (*)
	abort_not_supported "Operating system"
	;;
esac

install-python3-build-deps

mkdir -p "$(dirname "$src_dir")" "$archive_dir"

if [ ! -r "$pathname" ]; then
    cd "$archive_dir"
    wget $url || exit $?
fi

if [ ! -r "$src_dir/INSTALL" ]; then
    cd $(dirname "$src_dir")
    tar -xvf "$pathname"
fi
