#!/bin/sh -eu

# configure-git: download and configure Git
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

GIT_ARCHIVE_DIR="$HOME/Downloads/Git"
GIT_ARCHIVE_SUFFIX=.tar.gz

GIT_MIRROR_BASE_URL=https://www.kernel.org/pub/software/scm/git

GIT_OPT_PREFIX=/opt/%s
GIT_PROJECT_NAME=git
GIT_PROJECT_VERSION=2.35.1

abort() {
    printf "$@" >&2
    exit 1
}

abort_invalid_prefix() {
    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
}

abort_invalid_version() {
    usage_error '%s: invalid version -- %s\n' "$script" "$*"
}

abort_not_supported() {
    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

configure_git() {
    umask 0022

    if [ "$force" = true ]; then
	rm -rf "$src_dirname" "$archive_pathname"
    fi

    mkdir -p "$src_dirname" "$archive_dirname"
    download_archive "$archive_pathname" "$archive_url"
    extract_archive "$archive_pathname" "$src_dirname"
    cd "$src_dirname"

    command=$(get_configure_command .)
    printf '%s\n' "$command"
    eval $command

    if [ ! -r configure ]; then
	$make configure
    fi

    command=$(get_configure_command $src_dirname)
    printf '%s\n' "$command"
    eval $command

    if [ "$build" = true ]; then
	make_build all doc
    fi

    if [ "$check" = true ]; then
	make_check "test"
    fi
}

configure_paths() {
    archive_dirname="$GIT_ARCHIVE_DIR"
    archive_basename=$GIT_PROJECT_NAME-$version
    src_dirname="$HOME/Documents/src/Git/$archive_basename"
    archive_filename=$archive_basename$GIT_ARCHIVE_SUFFIX
    archive_pathname="$GIT_ARCHIVE_DIR/$archive_filename"
    archive_url=$GIT_MIRROR_BASE_URL/$archive_filename
}

download_archive() {
    assert [ $# -eq 2 ]
    assert [ -n "$1" ]
    assert [ -n "$2" ]

    if [ ! -r "$1" ]; then
	cd "$(dirname "$1")"
	wget $2
    fi
}

get_configure_options() (
    if [ -n "${prefix-}" ]; then
        options="${options:+$options }--prefix=$(get_prefix)"
    fi

    if [ -n "${options:-}" ]; then
	printf '%s\n' "$options"
    fi
)

get_dependencies() {
    get-packages $GIT_PROJECT_NAME-build $GIT_PROJECT_NAME-test
}

get_prefix() {
    printf "$prefix" "$GIT_PROJECT_NAME-$version"
}

install_git() {
    if [ "$install" != true ]; then
	return 0
    elif [ "$ID" != macos -a "$ID" != windows -a "$(id -u)" -gt 0 ]; then
	return 0
    fi

    umask 0022
    cd "$src_dirname"
    install_prefix=$(get_prefix)
    make_install prefix="$install_prefix" install install-doc install-html
    install_project_link "$install_prefix"

    if [ "$(id -u)" -eq 0 ]; then
	find "$src_dirname" -user root -type d | xargs chown-real-user
	find "$src_dirname" -user root -type f | xargs chown-real-user
    fi
}

parse_arguments() {
    build=true
    check=false
    force=false
    install=false
    keep=false
    prefix=$GIT_OPT_PREFIX
    version=$GIT_PROJECT_VERSION

    while getopts bcfiknp:h opt; do
	case $opt in
	    (b)
		build=true
		;;
	    (c)
		check=true
		;;
	    (f)
		build=true
		force=true
		;;
	    (i)
		install=true
		;;
	    (k)
		keep=true
		;;
	    (n)
		build=false
		force=false
		;;
	    (p)
		case $OPTARG in
		    ($HOME/.local|$LOCAL_PREFIX|$GIT_OPT_PREFIX)
			prefix=$OPTARG
			;;
		    (*)
			abort_invalid_prefix $OPTARG
			;;
		esac
		;;
	    (v)
		case $OPTARG in
		    (2.[0-9]|2.[1-9][0-9]|2.[1-9][0-9].[0-9])
			version=$OPTARG
			;;
		    (*)
			abort_invalid_version $OPTARG
			;;
		esac
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error '%s: Too many arguments\n' "$script"
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script [-b] [-c] [-f] [-i] [-k] [-n] [-p PREFIX] [-v VERSION]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

validate_platform() {
    case "$ID" in
	(centos)
	    case "$VERSION_ID" in
		(7)
		    return
		    ;;
		(8)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    return
	    ;;
	(fedora)
	    return
	    ;;
	(opensuse-*)
	    return
	    ;;
	(rhel|ol)
	    case "$VERSION_ID" in
		(7.*)
		    return
		    ;;
		(8.*)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(rocky)
	    case "$VERSION_ID" in
		(8.*)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(ubuntu)
	    return
	    ;;
	(freebsd)
	    return
	    ;;
	(illumos)
	    return
	    ;;
	(macos)
	    return
	    ;;
	(netbsd)
	    return
	    ;;
	(solaris)
	    return
	    ;;
	(windows)
	    return
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"
. "${script_prefix}config-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
validate_platform
configure_platform
parse_arguments "$@"
configure_paths

if [ "$keep" != true ]; then
    install_dependencies
fi

if [ "$(id -u)" -eq 0 ]; then
    run_unpriv /bin/sh -c "$0 $*"
else
    configure_git
fi

install_git
