#!/bin/sh -eu

# configure-docker-proxy: configure Docker proxy settings
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

INPUT=/etc/environment
OUTPUT=/etc/systemd/system/docker.service.d/http-proxy.conf

tmpfile=$(mktemp)
trap "/bin/rm -f $tmpfile" EXIT INT QUIT TERM

printf '[%s]\n' "Service" >$tmpfile

if [ -f $INPUT ]; then
    cat $INPUT
else
    printenv | grep -Ei '^(ftp|http|https|no)_proxy='
fi | while read statement; do
    printf 'Environment="%s"\n' "$statement" >>$tmpfile
done

if [ "$(wc -l <$tmpfile)" -gt 1 ]; then
    if [ -w $OUTPUT ]; then
        mkdir -p $(dirname $OUTPUT)
        chmod a+r $tmpfile
        /bin/mv -f $tmpfile $OUTPUT
        systemctl daemon-reload
        systemctl restart docker
    else
        cat $tmpfile
    fi
fi
