#!/bin/sh -eu

# configure-python: download and configure python
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PYTHON_ARCHIVE_DIR="$HOME/Downloads/Python"
PYTHON_ARCHIVE_SUFFIX=.tar.xz

PYTHON_MIRROR_BASE_URL=https://www.python.org/ftp

PYTHON_OPT_PREFIX=/opt/%s
PYTHON_PROJECT_NAME=python
PYTHON_PROJECT_VERSION=3.10.2

abort() {
    printf "$@" >&2
    exit 1
}

abort_invalid_prefix() {
    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
}

abort_invalid_version() {
    usage_error '%s: invalid version -- %s\n' "$script" "$*"
}

abort_not_supported() {
    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

configure_paths() {
    basename=Python-$version
    build_dir="$HOME/Documents/build/$basename"
    filename=$basename$PYTHON_ARCHIVE_SUFFIX
    pathname="$PYTHON_ARCHIVE_DIR/$filename"
    src_dir="$HOME/Documents/src/Python/$basename"
}

configure_python() {
    mkdir -p "$build_dir" "$(dirname "$src_dir")" "$PYTHON_ARCHIVE_DIR"
    download_archive
    extract_files
    cd "$build_dir"

    if [ "$force" = true ]; then
	clean_build
    elif [ ! -r config.status ]; then
	true
    else
	return 0
    fi

    command=$(get_configure_command $src_dir)
    printf '%s\n' "$command"
    eval $command

    if [ "$build" = true ]; then
	make_build
    fi

    if [ "$check" = true ]; then
	make_check "test"
    fi
}

download_archive() {
    url=$PYTHON_MIRROR_BASE_URL/python/$version/$filename

    if [ ! -r "$pathname" ]; then
	cd "$PYTHON_ARCHIVE_DIR"
	wget $url
    fi
}

get_configure_options() (
    if [ -n "${prefix-}" ]; then
        options="${options:+$options }--prefix=$(get_prefix)"
    fi

    if [ -n "${options:-}" ]; then
	printf '%s\n' "$options"
    fi
)

get_dependencies() {
    get-packages bootstrap python-build
}

get_prefix() {
    printf "$prefix" "python-$version"
}

install_python() {
    if [ "$install" != true ]; then
	return 0
    elif [ "$ID" != macos -a "$ID" != windows -a "$(id -u)" -gt 0 ]; then
	return 0
    fi

    umask 0022
    cd "$build_dir"
    install_prefix=$(get_prefix)
    make_install prefix="$install_prefix" install
    install_project_link "$install_prefix"

    if [ "$(id -u)" -eq 0 ]; then
	find "$src_dir" -user root -type d | xargs chown-real-user
	find "$src_dir" -user root -type f | xargs chown-real-user
    fi
}

parse_arguments() {
    build=true
    check=false
    force=false
    install=false
    prefix=$PYTHON_OPT_PREFIX
    version=$PYTHON_PROJECT_VERSION

    while getopts bcfip:v:h opt; do
	case $opt in
	    (b)
		build=true
		;;
	    (c)
		check=true
		;;
	    (f)
		force=true
		;;
	    (i)
		install=true
		;;
	    (p)
		case $OPTARG in
		    ($HOME/.local|$LOCAL_PREFIX|$PYTHON_OPT_PREFIX)
			prefix=$OPTARG
			;;
		    (*)
			abort_invalid_prefix $OPTARG
			;;
		esac
		;;
	    (v)
		case $OPTARG in
		    (3.[0-9].[0-9])
			version=$OPTARG
			;;
		    (3.[0-9].[1-9][0-9])
			version=$OPTARG
			;;
		    (3.[1-9][0-9].[0-9])
			version=$OPTARG
			;;
		    (3.[1-9][0-9].[1-9][0-9])
			version=$OPTARG
			;;
		    (*)
			abort_invalid_version $OPTARG
			;;
		esac
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error '%s: Too many arguments\n' "$script"
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script [-b] [-c] [-f] [-g] [-i] [-n] [-p PREFIX] [-v VERSION]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

validate_platform() {
    case "$ID" in
	(debian|raspbian)
	    return
	    ;;
	(opensuse-*)
	    return
	    ;;
	(rhel|centos|fedora)
	    return
	    ;;
	(freebsd)
	    return
	    ;;
	(macos)
	    return
	    ;;
	(netbsd)
	    return
	    ;;
	(solaris)
	    return
	    ;;
	(windows)
	    return
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"
. "${script_prefix}config-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
validate_platform
configure_platform
parse_arguments "$@"
configure_paths
install_dependencies

if [ "$(id -u)" -eq 0 ]; then
    run_unpriv /bin/sh -c "$0 $*"
else
    configure_python
fi

install_python
