#!/bin/sh -eu

# create-symlinks: create symlinks
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DOCUMENTS="$HOME/Documents"
SUBDIRS="build git logs src"
MODE=go-w

abort() {
    printf "$@" >&2
    exit 1
}

create_symbolic_links() {
    absolute_dir=$DOCUMENTS
    relative_dir=$(basename "$DOCUMENTS")

    if [ ! -d "$absolute_dir" ]; then
	exit 0
    fi

    cd "$absolute_dir"
    mkdir -m $MODE -p $SUBDIRS
    cd

    if [ ! -d "$relative_dir/bin" ]; then
	mkdir -m $MODE -p "$relative_dir"

	if [ -d bin ]; then
	    /bin/mv bin "$relative_dir/bin"
	else
	    mkdir -m $MODE "$relative_dir/bin"
	fi
    fi

    for dir in bin $SUBDIRS; do
	if [ -e "$relative_dir/$dir" -a ! -e $dir ]; then
	    ln -s "$relative_dir/$dir" "$HOME/$dir"
	fi
    done
}

create_symbolic_links
