#!/bin/sh -eu

# create-docker-bridge: create Docker bridge network
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

create_docker_bridge() {
    docker network create $(get_options) $network
}

get_gw() {
    net=$(get_net $1)
    octet=$(get_octets $net 4)
    printf '%s.%s\n' $(get_octets $net 1,2,3) $((octet + 1))
}

get_net() {
    printf '%s\n' $1 | cut -d/ -f 1
}

get_octets() {
    printf '%s\n' $1 | cut -d. -f ${2:-1,2,3,4}
}

get_options() {
    if [ -n "${interface-}" ]; then
	if [ "$macvlan" = true ]; then
	    driver=macvlan
	else
	    driver=ipvlan
	fi

	if [ "$dhcp" = true ]; then
	    ipam_driver=dhcp
	    ipam_opt=dhcp_interface=$interface
	else
	    ipam_driver=default
	    ipam_opt=
	fi

	printf '%s\n' \
	       --driver=$driver \
	       --ipam-driver=$ipam_driver \
	       ${ipam_opt:+--ipam-opt=$ipam_opt} \
	       --opt=parent=$interface
    fi

    if [ -n "${net-}" ]; then
	printf '%s\n' --subnet=$net

	if [ "$first" = true ]; then
	    printf '%s\n' --gateway=$(get_gw $net)
	elif [ -n "${gateway-}" ]; then
	    printf '%s\n' --gateway=$gateway
	fi
    fi
}

parse_arguments() {
    dhcp=false
    first=false
    gateway=
    interface=
    macvlan=false
    net=

    while getopts dfg:i:mn:h opt; do
	case $opt in
	    (d)
		dhcp=true
		;;
	    (f)
		first=true
		;;
	    (g)
		gateway=$OPTARG
		;;
	    (i)
		interface=$OPTARG
		;;
	    (m)
		macvlan=true
		;;
	    (n)
		net=$OPTARG
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		printf "%s\n" "" >&2
		usage
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))
    network=${1:-alternate}
}

usage() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
	printf "%s\n" "" >&2
    fi

    cat <<-EOF >&2
	Usage: $0 [-d] [-f] [-g GATEWAY] [-m] [-n SUBNET] [NETWORK]
	       $0 -h
	EOF
}

parse_arguments "$@"
create_docker_bridge
