#!/bin/sh -eu

# create-symlinks: create symlinks
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DIRS="build git logs src"
MODE=go-w

abort() {
    printf "$@" >&2
    exit 1
}

create_directories() (
    cd "$HOME/Documents"
    mkdir -m $MODE -p $DIRS
)

create_symbolic_links() {
    create_directories
    cd

    if [ ! -d Documents/bin ]; then
        mkdir -m $MODE -p Documents

        if [ -d bin ]; then
	    /bin/mv bin Documents/bin
        else
	    mkdir -m $MODE Documents/bin
        fi
    fi

    for dir in bin $DIRS; do
        if [ -e Documents/$dir -a ! -e $dir ]; then
	    ln -s Documents/$dir $HOME/$dir
        fi
    done
}

create_symbolic_links
