#!/bin/bash -eu

# create-oracle-databases: create Oracle databases
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

ORACLE_BASE=/opt/oracle

create_database() {
    export ORACLE_SID=$1

    cat >$ORACLE_HOME/dbs/init$ORACLE_SID.ora <<EOF
db_name='$ORACLE_SID'
processes=150
audit_file_dest='$audit_dir'
audit_trail='db'
db_block_size=8192
db_domain=''
db_recovery_file_dest='$recovery_dir'
db_recovery_file_dest_size=2G
diagnostic_dest='$ORACLE_BASE'
dispatchers='(PROTOCOL=TCP) (SERVICE=ORCLXDB)'
open_cursors=300
remote_login_passwordfile='EXCLUSIVE'
undo_management=AUTO
control_files=(ora_control1, ora_control2)
compatible='11.2.0'
EOF

    sqlplus / as sysdba <<EOF
CREATE SPFILE FROM PFILE;
STARTUP NOMOUNT;
CREATE DATABASE $ORACLE_SID;
SHUTDOWN IMMEDIATE;
EOF
}

if [ -d $ORACLE_BASE ]; then
    audit_dir=$ORACLE_BASE/admin/orcl/adump
    recovery_dir=$ORACLE_BASE/fast_recovery_area
    mkdir -p $audit_dir $recovery_dir

    for database; do
        create_database $database
    done
fi
