#!/bin/sh -eu

# create-docker-volume-devices: create Docker volume devices
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

VOLUME_GID=500
VOLUME_UID=500

VOLUME_COMMENT='Docker Volume Account'
VOLUME_FILE=docker-volumes.txt
VOLUME_HOME=/local/volumes
VOLUME_SHELL=/sbin/nologin
VOLUME_USER=docker-volume

VOLUME_NAME_RE='[a-z][0-9_a-z-]+'
VOLUME_PATH_RE="(\\/${VOLUME_NAME_RE})+"
VOLUME_RE="\\.{,2}(${VOLUME_PATH_RE})?:${VOLUME_PATH_RE}(:${VOLUME_NAME_RE})?"

BSD_AWK_RE='awk version \([1-9][0-9]*\)'
BSD_AWK_VERSION=20190529
GNU_AWK_RE='GNU Awk \([1-9][0-9]*\(\.[0-9][0-9]*\)*\)'
GNU_AWK_VERSION=4.0.0

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
}

compare_versions() (
    assert [ $# -eq 3 ]
    assert [ -n "$3" ]

    if [ -z "$1" -a -z "$2" -o "$3" -le 0 ]; then
	printf '%s\n' 0
    else
	m=$(printf '%s\n' "${1:-0}" | cut -d. -f 1)
	n=$(printf '%s\n' "${2:-0}" | cut -d. -f 1)
	delta=$((m - n))

	if [ "$delta" -ne 0 ]; then
	    printf '%s\n' $delta
	else
	    printf '%s\n' "$(compare_versions ${1#*.} ${2#*.} $(($3 - 1)))"
	fi
    fi
)

configure_platform() {
    case "${uname_kernel=$(uname -s)}" in
	(FreeBSD)
	    pw=pw
	    pw_mask='*'
	    ;;
	(*)
	    pw=
	    pw_mask='x'
	    ;;
    esac
}

create_docker_volume_devices() {
    validate_platform
    configure_platform
    volume_file=$(find_file $VOLUME_FILE)

    if [ ! -f $volume_file ]; then
	abort '%s: %s: No such volume file\n' "$script" "$volume_file"
    fi

    umask 0022
    create_home_directory

    get_volumes | while read device mount name; do
	create_volume_device "$device"
    done

    create_volume_group
    create_volume_user
    modify_permissions
    modify_user
}

create_home_directory() {
    mkdir -p "$volume_home"

    if [ ! -d "$volume_home" ]; then
	abort '%s: %s: No such directory\n' "$script" "$volume_home"
    elif [ ! -w "$volume_home" ]; then
	abort '%s: %s: No write permissions\n' "$script" "$volume_home"
    elif [ ! -x "$volume_home" ]; then
	abort '%s: %s: No execute permissions\n' "$script" "$volume_home"
    fi

    if [ -n "$template_dir" -a -d "$template_dir" ]; then
	/bin/cp -R $template_dir/* "$volume_home"
    fi
}

create_volume_device() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]

    if expr "$1" : "$volume_home"'/' >/dev/null; then
	mkdir -p $1
    fi
}

create_volume_group() {
    volume_group_args=$(print_volume_group_args)
    volume_group_data=$(get_volume_group_data || true)

    if [ -z "$volume_group_data" ]; then
	eval ${pw:+pw }groupadd $volume_group_args
    elif [ "$volume_group_data" != "$(print_volume_group_data)" ]; then
	eval ${pw:+pw }groupmod $volume_group_args
    fi
}

create_volume_user() {
    volume_passwd_data=$(get_volume_passwd_data || true)
    volume_useradd_args=$(print_volume_useradd_args)
    volume_usermod_args=$(print_volume_usermod_args)

    if [ -z "$volume_passwd_data" ]; then
	eval ${pw:+pw }useradd $volume_useradd_args
    elif [ "$volume_passwd_data" != "$(print_volume_passwd_data)" ]; then
	eval ${pw:+pw }usermod $volume_usermod_args
    fi
}

find_file() {
    for dir in . .. "$HOME"; do
	file="$dir/$1"

	if [ -f "$file" ]; then
	    printf '%s\n' "$file"
	    return 0
	fi
    done

    printf '%s\n' "$1"
}

get_length() {
    printf '%s\n' "${1-}" | wc -c
}

get_version_string() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]
    "$1" --version 2>/dev/null | head -n 1
}

get_volume_group_data() {
    getent group $VOLUME_GID | cut -d: -f 1-3
}

get_volume_group_name() {
    getent group $VOLUME_GID | cut -d: -f 1
}

get_volume_passwd_data() {
    getent passwd $VOLUME_UID
}

get_volumes() {
    if [ -n "$volume_home" ]; then
	sed -e 's|^\.\./volumes/|'"$volume_home"'/|' \
	    -e 's|^~/|'"$volume_home"'/|' $volume_file
    else
	cat $volume_file
    fi | awk -F: '/^'"$VOLUME_RE"'$/ {print $1, $2, $3}'
}

is_valid_name() {
    expr "${1-}" : '[a-z][0-9_a-z-]*$' >/dev/null
}

modify_permissions() {
    chown -R $VOLUME_UID:$VOLUME_GID "$volume_home"
    find "$volume_home" -type d | xargs chmod a+rx
}

modify_user() {
    volume_group_name=$(get_volume_group_name)

    if [ "$(id -u)" -eq 0 -a -n "$SUDO_USER" ]; then
	user=$SUDO_USER
    elif [ -n "$USER" ]; then
	user=$USER
    fi

    usermod_args=$(print_usermod_args $volume_group_name $user)

    if [ -n "$usermod_args" ]; then
	${pw:+pw }usermod $usermod_args
    fi
}

parse_arguments() {
    template_dir=
    volume_comment=$VOLUME_COMMENT
    volume_home=$VOLUME_HOME
    volume_user=$VOLUME_USER

    while getopts c:d:n:t:h opt; do
	case $opt in
	    (c)
		volume_comment=$OPTARG
		;;
	    (d)
		volume_home=$OPTARG
		;;
	    (n)
		parse_volume_user "$OPTARG"
		;;
	    (t)
		parse_template_dir "$OPTARG"
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error "%s: Too many arguments\n" "$script"
    fi
}

parse_template_dir() {
    if [ -d "$1" ]; then
	template_dir=$1
    else
	usage_error "%s: %s: No such directory\n" "$script" "$1"
    fi
}

parse_volume_user() {
    if is_valid_name "$1" && [ "$(get_length "$1")" -le 16 ]; then
	volume_user=$1
    else
	usage_error "%s: %s: Invalid user name\n" "$script" "$1"
    fi
}

print_usermod_args() {
    assert [ $# -eq 2 ]
    assert [ -n "$1" ]
    assert [ -n "$2" ]

    case "${uname_kernel=$(uname -s)}" in
	(FreeBSD)
	    true
	    ;;
	(*)
	    printf '%s\n' \
		   -aG "$1" \
		   "$2"
	    ;;
    esac
}

print_volume_group_args() {
    case "${uname_kernel=$(uname -s)}" in
	(FreeBSD)
	    printf '%s\n' \
		   -g $VOLUME_GID \
		   -n "$volume_user"
	    ;;
	(*)
	    printf '%s\n' \
		   -g $VOLUME_GID \
		   "$volume_user"
	    ;;
    esac
}

print_volume_group_data() {
    printf '%s:%s:%s\n' \
	   "$volume_user" \
	   "$pw_mask" \
	   "$VOLUME_GID"
}

print_volume_passwd_data() {
    printf '%s:%s:%s:%s:%s:%s:%s\n' \
	   "$volume_user" \
	   "$pw_mask" \
	   "$VOLUME_UID" \
	   "$VOLUME_GID" \
	   "$volume_comment" \
	   "$volume_home" \
	   "$VOLUME_SHELL"
}

print_volume_useradd_args() {
    case "${uname_kernel=$(uname -s)}" in
	(FreeBSD)
	    printf '%s\n' \
		   -c '"'"$volume_comment"'"' \
		   -d "$volume_home" \
		   -g $VOLUME_GID \
		   -s $VOLUME_SHELL \
		   -u $VOLUME_UID \
		   -n "$volume_user"
	    ;;
	(*)
	    printf '%s\n' \
		   -Nr \
		   -c '"'"$volume_comment"'"' \
		   -d "$volume_home" \
		   -g $VOLUME_GID \
		   -s $VOLUME_SHELL \
		   -u $VOLUME_UID \
		   "$volume_user"
	    ;;
    esac
}

print_volume_usermod_args() {
    case "${uname_kernel=$(uname -s)}" in
	(FreeBSD)
	    printf '%s\n' \
		   -c '"'"$volume_comment"'"' \
		   -d "$volume_home" \
		   -g $VOLUME_GID \
		   -s $VOLUME_SHELL \
		   -u $VOLUME_UID \
		   -n "$volume_user"
	    ;;
	(*)
	    printf '%s\n' \
		   -c '"'"$volume_comment"'"' \
		   -d "$volume_home" \
		   -g $VOLUME_GID \
		   -s $VOLUME_SHELL \
		   -u $VOLUME_UID \
		   "$volume_user"
	    ;;
    esac
}

usage() {
    cat <<EOF >&2
Usage: $script [-d VOLUME-HOME] [-n VOLUME-USER] [-t TEMPLATE-DIR]
       $script -h

Create and populate Docker volume account and device directories.

  -d VOLUME-HOME   use VOLUME-HOME as the account home directory
		   (default value is $VOLUME_HOME)
  -h               print this help text (all other options are ignored)
  -n VOLUME-USER   use VOLUME-USER as the account name
		   (default value is $VOLUME_USER)
  -t TEMPLATE-DIR  populate home directory from TEMPLATE-DIR
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

validate_bsd_awk() {
    validate_version "$1" "$BSD_AWK_RE" $BSD_AWK_VERSION 'BSD Awk'
}

validate_gnu_awk() {
    validate_version "$1" "$GNU_AWK_RE" $GNU_AWK_VERSION 'GNU Awk'
}

validate_platform() {
    case "${uname_kernel=$(uname -s)}" in
	(FreeBSD)
	    true
	    ;;
	(Linux)
	    true
	    ;;
	(*)
	    abort '%s: %s: Operating system not supported\n' \
	    	  "$script" \
		  "$uname_kernel"
	    ;;
    esac

    version_string=$(get_version_string awk)

    if expr "$version_string" : "$GNU_AWK_RE" >/dev/null; then
	validate_gnu_awk "$version_string"
    elif expr "$version_string" : "$BSD_AWK_RE" >/dev/null; then
	validate_bsd_awk "$version_string"
    else
	abort '%s: BSD/GNU Awk is required\n' "$script"
    fi
}

validate_version() {
    assert [ $# -eq 4 ]
    assert [ -n "$1" ]
    assert [ -n "$2" ]
    assert [ -n "$3" ]
    assert [ -n "$4" ]
    version=$(expr "$1" : "$2" || true)

    if [ -n "$version" ]; then
	nf=$(printf '%s\n' "$3" | awk -F. '{print NF}')
	delta=$(compare_versions "$version" "$3" "$nf")

	if [ -n "$delta" -a "$delta" -ge 0 ]; then
	    return 0
	fi
    fi

    abort '%s: %s version %s or greater is required\n' \
	  "$script" \
	  "$4" \
	  "$3"
}

script=$(basename "$0")
parse_arguments "$@"
create_docker_volume_devices
