#!/bin/sh -eu

# create-symlinks: create symlinks
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DOCUMENTS="$HOME/Documents"
SUBDIRS="build git logs src"
MODE=go-w

abort() {
    printf "$@" >&2
    exit 1
}

create_symbolic_links() {
    if [ ! -d "$DOCUMENTS" ]; then
	exit 0
    fi

    cd "$DOCUMENTS"
    mkdir -m $MODE -p $SUBDIRS
    cd

    if [ ! -d "$DOCUMENTS/bin" ]; then
	mkdir -m $MODE -p "$DOCUMENTS"

	if [ -d bin ]; then
	    /bin/mv bin "$DOCUMENTS/bin"
	else
	    mkdir -m $MODE "$DOCUMENTS/bin"
	fi
    fi

    for dir in bin $SUBDIRS; do
	if [ -e "$DOCUMENTS/$dir" -a ! -e $dir ]; then
	    ln -s "$DOCUMENTS/$dir" "$HOME/$dir"
	fi
    done
}

create_symbolic_links
