#!/bin/sh -eu

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

if [ $# -lt 1 ]; then
    abort "%s: Not enough arguments\n" "$0"
elif [ $# -gt 1 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

docker exec -it $1 bash
