#!/bin/sh -eu

# docker-run-database-server: run Oracle server in container
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

ENV_FILE=$HOME/.env

IMAGE_NAME=oracle/database
IMAGE_TAG=19.3.0-se2

PORTS="1521 5500"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

docker_run_oracle_server() {
    set_options
    docker run $options $IMAGE_NAME:$IMAGE_TAG
}

parse_arguments() {
    if [ $# -gt 0 ]; then
        user_options="$@"
    else
        user_options="-d"
    fi
}

set_options() {
    env_options="-e ORACLE_PWD=$DATABASE_PASSWORD"

    for port in $PORTS; do
        port_options="${port_options+$port_options }-p $port:$port"
    done

    options="$env_options $port_options $user_options"
}

if [ ! -r $ENV_FILE ]; then
    abort "%s: %s: No such environment file\n" "$0" $ENV_FILE
fi

. $ENV_FILE

parse_arguments "$@"
docker_run_oracle_server
