#!/bin/sh -eu

# docker-exec-oracle-client: run Oracle client in container
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

usage_error() {
    printf "$@" >&2
    exit 2
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}oracle-config.sh"

if [ $# -lt 1 ]; then
    usage_error '%s: Not enough arguments\n' "$script"
elif [ $# -gt 1 ]; then
    usage_error '%s: Too many arguments\n' "$script"
fi

if [ -r $HOME/.env-oracle ]; then
    . $HOME/.env-oracle
fi

if [ -r $HOME/${ENV_FILE-.env} ]; then
    . $HOME/${ENV_FILE-.env}
fi

docker exec -it $1 sqlplus "system/$DATABASE_PASSWORD@//localhost:1521/ORCLCDB"
