#!/bin/sh -eu

# docker-run-database-server: run SQL DBMS server
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_database_image_name() {
    case "$DATABASE_DIALECT" in
	(mysql)
	    printf "%s\n" mysql
	    ;;
	(postgresql)
	    printf "%s\n" postgres
	    ;;
    esac
}

get_docker_database_options() {
    case "$DATABASE_DIALECT" in
	(mysql)
	    . ./.env-mysql
	    printf "%s\n" \
		   -e MYSQL_DATABASE=$MYSQL_DATABASE \
		   -e MYSQL_USER=$MYSQL_USER \
		   -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
		   -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
	    ;;
	(postgresql)
	    . ./.env-postgres
	    printf "%s\n" \
		   -e POSTGRES_DB=$POSTGRES_DB \
		   -e POSTGRES_USER=$POSTGRES_USER \
		   -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
	    ;;
    esac
}

. ./.env
docker run -d \
       $(get_docker_database_options) \
       --network=host "$@" \
       $(get_database_image_name)
