#!/bin/sh -eu

# docker-run-oracle-server: run Oracle server in container
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

ENV_FILE=$HOME/.env

IMAGE_NAME=oracle/database
IMAGE_TAG=19.3.0-se2

NAMES="startup setup"
PORTS="1521 5500"

SCRIPTS=/opt/oracle/scripts

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

docker_run_oracle_server() {
    set_options
    docker run $opts $IMAGE_NAME:$IMAGE_TAG
}

parse_arguments() {
    if [ $# -gt 0 ]; then
        user_opts="$@"
    else
        user_opts="-d"
    fi
}

set_options() {
    env_opts="-e ORACLE_PWD=$DATABASE_PASSWORD"
    port_opts=
    vol_opts=

    for port in $PORTS; do
        port_opts="${port_opts:+$port_opts }-p $port:$port"
    done

    for name in $NAMES; do
	host_dir=$HOME/oracle/$name

	if [ -d $host_dir ]; then
	    vol_opts="${vol_opts:+$vol_opts }-v $host_dir:$SCRIPTS/$name"
	fi
    done

    opts="$env_opts ${port_opts:+$port_opts }${vol_opts:+$vol_opts }$user_opts"
}

if [ ! -r $ENV_FILE ]; then
    abort "%s: %s: No such environment file\n" "$0" $ENV_FILE
fi

. $ENV_FILE

parse_arguments "$@"
docker_run_oracle_server
