#!/bin/sh -eu

# edit-software-properties: invoke software properties dialog
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

abort_desktop_not_supported() {
    abort "%s: %s: Desktop not supported\n" "$0" "$desktop_name"
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}


edit_software_properties() {
    if [ -z "${DISPLAY:-}" ]; then
	abort "%s: No DISPLAY variable set\n" "$0"
    fi

    desktop_name=$(get-desktop-name)

    if [ -z "${desktop_name:-}" ]; then
	abort "%s: Desktop not specified\n" "$0"
    fi

    case "$ID" in
	(debian|raspbian|ubuntu)
	    case "$desktop_name" in
		(GNOME*|*:GNOME|MATE)
		    software-properties-gtk
		    ;;
		(KDE*)
		    software-properties-kde
		    ;;
		(*)
		    abort_desktop_not_supported
		    ;;
	    esac
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

eval $(get-os-release -x)
edit_software_properties
