#!/bin/sh -eu

# enable-sudo: install sudo and add supplemental group sudo
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="sudo"

abort() {
    printf "$@" >&2
    exit 1
}

system_name="$(uname -s)"
pretty_name=$(sh -eu $script_dir/get-os-release -p)

case "$system_name" in
    (Linux)
	if [ -r /etc/os-release ]; then
	    . /etc/os-release
	    case "$ID" in
		(debian|ubuntu)
		    su -c "apt-get install $DEBIAN_PKGS"
		    ;;
		(*)
		    abort "%s: Distro not supported\n" "$pretty_name"
		    ;;
	    esac
	else
	    abort "Distro not supported\n"
	fi
	;;
    (*)
	abort "%s: Operating system not supported\n" "$pretty_name"
	;;
esac

if su -c "usermod -a -G sudo $USER"; then
    printf "Please restart before using sudo\n"
fi
