#!/bin/sh -eu

# format-python-packages: format Python package package names
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

format_python_packages() {
    data=$("${script_prefix}get-python-metadata")

    package_name=$(printf "%s" "$data" | awk '{print $1}')
    package_modifier=$(printf "%s" "$data" | awk '{print $2}')

    printf "%s\n" $package_name

    for package in "$@"; do
	case $package in
	    (*%s*|*%.[1-9]s*)
		printf "$package\n" $package_modifier
		;;
	    (*)
		printf "%s\n" $package
		;;
	esac
    done
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

case "$0" in
    (*/*)
	script_dir=$(dirname "$0")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$(get_realpath "$script_dir")/}

. "${script_prefix}common-functions.sh"

eval $("${script_prefix}get-os-release" -x)
format_python_packages "$@"
