#!/bin/sh -eu

# generate-docker-compose: print configuration file docker-compose.yaml
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

COMPOSE_VERSION=3.3
ENV_FILE=docker-environment.txt
NAME_FILE=docker-names.txt
PORT_FILE=docker-ports.txt
VOLUME_FILE=docker-volumes.txt

generate_docker_compose() {
    printf '%s: "%s"\n' "version" "$COMPOSE_VERSION"
    print_services
    print_volumes
}

get_environment_value() {
    awk -F= '$1 == "'"$1"'" {print $2}' $ENV_FILE
}

get_environment_vars() {
    awk -F= '/^[A-Z][0-9A-Z_]+=.+/ {print $1}' $ENV_FILE
}

get_name_value() {
    awk -F= '$1 == "'"$1"'" {print $2}' $NAME_FILE
}

get_ports() {
    awk '/^([0-9-]+:|)[0-9-]+(|\/(tcp|udp))$/ {print $0}' $PORT_FILE
}

get_volume_count() {
    awk -F: '/^[a-z][0-9_a-z-]+:.+/ {++n} END {print n}' $VOLUME_FILE
}

get_volume_device() {
    awk -F: '$1 == "'"$1"'" {print $3}' $VOLUME_FILE
}

get_volume_mount() {
    awk -F: '$1 == "'"$1"'" {print $2}' $VOLUME_FILE
}

get_volumes() {
    awk -F: '/^[a-z][0-9_a-z-]+:.+/ {print $1}' $VOLUME_FILE
}

print_service_environment() {
    printf '        %s:\n' "environment"

    get_environment_vars | while read var; do
	value=$(get_environment_value $var)
	printf '            - %s=%s\n' "$var" "$value"
    done
}

print_service_ports() {
    printf '        %s:\n' "ports"

    get_ports | while read port; do
	if expr "$port" : '^[0-9-]*$' >/dev/null; then
	    printf '            - %s:%s\n' "$port" "$port"
	else
	    printf '            - %s\n' "$port"
	fi
    done
}

print_service_volumes() {
    volume_count=$(get_volume_count)

    if [ "$volume_count" -eq 0 ]; then
	return 0
    fi

    printf '        %s:\n' "volumes"

    get_volumes | while read volume; do
	mount=$(get_volume_mount $volume)
	printf '            - %s:%s\n' "$volume" "$mount"
    done
}

print_services() {
    container_name=$(get_name_value container_name)
    docker_image=$(get_name_value docker_image)
    service_name=$(get_name_value service_name)
    printf '%s\n' ""
    printf '%s:\n' "services"
    printf '%s\n' ""
    printf '    %s:\n' "$service_name"
    printf '        %s: %s\n' "container_name" "$container_name"
    print_service_environment
    printf '        %s: %s\n' "image" "$docker_image"
    print_service_ports
    print_service_volumes
}

print_volumes() {
    volume_count=$(get_volume_count)

    if [ "$volume_count" -eq 0 ]; then
	return 0
    fi

    printf '%s\n' ""
    printf '%s:\n' "volumes"

    get_volumes | while read volume; do
	device=$(get_volume_device $volume)
	printf '%s\n' ""
	printf '    %s:\n' "$volume"
	printf '        %s: %s\n' "driver" "local"
	printf '        %s:\n' "driver_opts"
	printf '            %s: %s\n' "o" "bind"
	printf '            %s: %s\n' "type" "none"
	printf '            %s: %s\n' "device" "$device"
    done
}

generate_docker_compose
