#!/bin/sh -eu

# generate-proxy-parameters: generate a list of proxy parameters
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

KEYS="all ftp http https no"
NO_PROXY="localhost,127.0.0.1"

get_proxy_parameters() {
    for key in $KEYS; do
	case "$key" in
	    (no)
		value=$no_proxy
		;;
	    (*)
		value=$proxy
		;;
	esac

	var_lower=$(printf '%s_proxy' "$key" | to_lower)
	var_upper=$(printf '%s_proxy' "$key" | to_upper)
	printf '%s=%s\n' "$var_upper" "$value"
	printf '%s=%s\n' "$var_lower" "$value"
    done
}

is_valid_cidr() {
    is_valid_ipv4 "${1%/*}" && is_valid_number "${1#*/}" 0 32
}

is_valid_fqdn() (
    case "$1" in
	(''|.*|*.|*..*)
	    return 1
	    ;;
    esac

    IFS=.

    for word in $1; do
	if ! is_valid_name "$word"; then
	    return 1
	fi
    done
)

is_valid_ipv4() (
    case "$1" in
	(''|.*|*.|*..*)
	    return 1
	    ;;
    esac

    IFS=.
    set -- $1

    if [ $# -ne 4 ]; then
	return 1
    fi

    for octet; do
	if ! is_valid_number "$octet" 0 255; then
	    return 1
	fi
    done
)

is_valid_name() {
    expr "${1-}" : '[0-9A-Za-z][-0-9A-Za-z]*$' >/dev/null
}

is_valid_no_proxy() (
    IFS=,

    for word in $1; do
	if ! is_valid_no_proxy_entry "$word"; then
	    return 1
	fi
    done
)

is_valid_no_proxy_entry() {
    case "$1" in
	('*'|localhost|::1)
	    true
	    ;;
	(*/*)
	    is_valid_cidr "$1"
	    ;;
	('*.'*)
	    is_valid_fqdn "${1#??}"
	    ;;
	(.*)
	    is_valid_fqdn "${1#.}"
	    ;;
	(*)
	    is_valid_fqdn "$1"
	    ;;
    esac
}

is_valid_number() {
    expr "${1-}" : '[0-9][0-9]*$' >/dev/null && \
	[ "$1" -ge "$2" ] && [ "$1" -le "$3" ]
}

# Accepts http[s]://[userinfo@]host[:port][/path]
is_valid_proxy() (
    case "$1" in
	(http://*|https://*)
	    authority=${1#*://}
	    ;;
	(*)
	    return 1
	    ;;
    esac

    authority=${authority%%/*}
    host_port=${authority##*@}

    case "$host_port" in
	(*:*)
	    is_valid_fqdn "${host_port%:*}" && \
		is_valid_number "${host_port##*:}" 1 65535
	    ;;
	(*)
	    is_valid_fqdn "$host_port"
	    ;;
    esac
)

parse_arguments() {
    no_proxy=$NO_PROXY

    while getopts n:h opt; do
	case $opt in
	    (n)
		parse_no_proxy "$OPTARG"
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -eq 0 ]; then
	usage_error '%s: Not enough arguments\n' "$script"
    fi

    parse_proxy "$1"
    shift

    if [ $# -gt 0 ]; then
	usage_error '%s: Too many arguments\n' "$script"
    fi
}

parse_no_proxy() {
    if is_valid_no_proxy "$1"; then
	no_proxy="$1"
    else
	usage_error '%s: %s: Invalid proxy exception list\n' "$script" "$1"
    fi
}

parse_proxy() {
    if is_valid_proxy "$1"; then
	proxy="$1"
    else
	usage_error '%s: %s: Invalid proxy URL\n' "$script" "$1"
    fi
}

to_lower() {
    tr '[:upper:]' '[:lower:]'
}

to_upper() {
    tr '[:lower:]' '[:upper:]'
}

usage() {
    cat <<EOF >&2
Usage: $script [-n NO-PROXY] PROXY-URL
       $script -h

Generate FTP/HTTP/HTTPS proxy parameter list.

  -h           print this help text (all other options are ignored)
  -n NO-PROXY  interpret NO-PROXY as a comma-separated list of exceptions

Example NO-PROXY:

  localhost,127.0.0.0/8

Example PROXY-URL:

  http://proxy.com:80
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script=$(basename "$0")
# Wildcard no-proxy entries must not undergo pathname expansion
set -f
parse_arguments "$@"
get_proxy_parameters
