#!/bin/sh -eu

# get-package-managers: get names of package manager utilities
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_package_managers() {
    case "$kernel_name" in
	(Linux|GNU)
	    for id in $ID $ID_LIKE; do
		case "$id" in
		    (debian)
			printf "%s\n" apt-get
			return
			;;
		    (opensuse)
			printf "%s\n" zypper
			return
			;;
		    (fedora)
			printf "%s\n" dnf
			return
			;;
		    (rhel|centos)
			case "$VERSION_ID" in
			    (7|7.[78])
				printf "%s\n" yum /usr/pkg/bin/pkgin
				;;
			    (8|8.[01])
				printf "%s\n" dnf
				;;
			esac

			return
			;;
		esac
	    done
	    ;;
	(Darwin)
	    case "$ID" in
		(macos)
		    printf "%s\n" /usr/local/bin/brew /opt/pkg/bin/pkgin
		    ;;
	    esac
	    ;;
	(FreeBSD)
	    case "$ID" in
		(freebsd)
		    printf "%s\n" pkg
		    ;;
	    esac
	    ;;
	(NetBSD)
	    printf "%s\n" pkgin
	    ;;
	(SunOS)
	    printf "%s\n" pkg pkgin
	    ;;
    esac
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)

get_package_managers
