#!/bin/bash -eu

# get-release-name: print name of Linux distribution release
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

keys="os centos fedora redhat system"

case "$(get-platform-name)" in
    (Linux)
	for key in $keys; do
	    file=/etc/$key-release

	    if [ -r $file ]; then
		case ${file#/etc/} in
		    (os-release)
			(source $file && printf "%s\n" "$VERSION_ID")
			exit 0
			;;
		    (*-release)
			awk '{print $4}' $file
			exit 0
			;;
		esac
	    fi
	done

	if [ -x /usr/bin/lsb_release ]; then
	    /usr/bin/lsb_release -rs
	fi
	;;
    (FreeBSD)
	uname -r
	;;
    (SunOS)
	os_version=$(uname -v)
	printf "%s\n" "${os_version#*-}"
	;;
    (CYGWIN_NT-*)
	uname -r
	;;
esac
