#!/bin/sh -eu

# get-app-status: print last few lines of service log file
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_service_parameters() {
    if [ -z "${SYSTEM_PYTHON_VERSION-}" ]; then
	SYSTEM_PYTHON_VERSION="$(get_python_version $SYSTEM_PYTHON)"
    fi

    cat <<EOF
             Name: $APP_NAME
             Port: $APP_PORT
   Python version: $(print_parameter $SYSTEM_PYTHON_VERSION)
   Server version: $(print_parameter "$(get_uwsgi_version)")
    User/Group ID: $APP_UID/$APP_GID
    Configuration: $(print_path $APP_CONFIG)
Program directory: $(print_path $APP_DIR)
      Python file: $(print_parameter $SYSTEM_PYTHON)
      Server file: $(print_path "$(get_uwsgi_binary_path)")
      Plugin file: $(print_path "$(get_uwsgi_plugin_path)")
Working directory: $(print_path $APP_VARDIR)
         Log file: $(print_path $APP_LOGFILE)
         PID file: $(print_path $APP_PIDFILE)
           Socket: $(print_path $APP_SOCKET)
EOF
}

print_parameter() {
    if [ -n "${1-}" ]; then
	printf "%s\n" "$1"
    else
	printf "%s\n" "<none>"
    fi
}

print_path() {
    if [ -n "${1-}" ]; then
	if [ -e $1 ]; then
	    printf "%s\n" "$1"
	else
	    printf "%s\n" "$1 (not found)"
	fi
    else
	printf "%s\n" "<none>"
    fi
}

print_app_parameters() {
    get_service_parameters | print_table "${1-}" "SERVICE PARAMETER: VALUE"
}

print_status() {
    border=1

    for item in parameters log_file processes; do
	eval print_app_$item $border
	border=0
    done

    printf "Service %s is %s\n" "$APP_NAME" "$1"
}

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}utility-functions.sh"
. "${script_prefix}restapi-functions.sh"
. "${script_prefix}restapi-parameters.sh"

configure_all
print_status $(get_app_status)
