#!/bin/sh -eu

# get-kubernetes-dependencies: list Kubernetes dependency package names
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CENTOS_7_PKGS="redhat-lsb-core yum-utils"
CENTOS_8_PKGS="dnf-utils redhat-lsb-core"

DEBIAN_PKGS="apt-transport-https ca-certificates curl gnupg2 \
software-properties-common"

FEDORA_PKGS="dnf-utils redhat-lsb-core"

ORACLE_7_PKGS="redhat-lsb-core yum-utils"
ORACLE_8_PKGS="redhat-lsb-core yum-utils"

REDHAT_7_PKGS="redhat-lsb-core yum-utils"
REDHAT_8_PKGS="redhat-lsb-core yum-utils"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
}

get_kubernetes_dependencies() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (centos)
		case "$VERSION_ID" in
		    (7)
			packages=$CENTOS_7_PKGS
			;;
		    (8)
			packages=$CENTOS_8_PKGS
			;;
		esac
		;;
	    (debian)
		packages=$DEBIAN_PKGS
		;;
	    (fedora)
		packages=$FEDORA_PKGS
		;;
	    (ol)
		case "$VERSION_ID" in
		    (7.*)
			packages=$ORACLE_7_PKGS
			;;
		    (8.*)
			packages=$ORACLE_8_PKGS
			;;
		esac
		;;
	    (rhel)
		case "$VERSION_ID" in
		    (7.*)
			packages=$REDHAT_7_PKGS
			;;
		    (8.*)
			packages=$REDHAT_8_PKGS
			;;
		esac
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    if [ -n "${packages-}" ]; then
	printf '%s\n' ${packages-}
    fi
}

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

eval $("${script_prefix}get-os-release" -x)
get_kubernetes_dependencies
