#!/bin/sh -eu

# get-mysql-common-packages: get MySQL database common package names
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_PKG=""

DEBIAN_10_PKG="mariadb-common"

FEDORA_PKG=""

FREEBSD_PKG=""

ILLUMOS_PKG=""

NETBSD_PKG=""

OPENSUSE_PKG=""

REDHAT_PKG=""

SOLARIS_PKG=""

UBUNTU_18_04_PKG="mariadb-common"
UBUNTU_19_10_PKG="mariadb-common"

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_mysql_common_packages() {
    packages=

    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian)
		    case "$VERSION_ID" in
			(10)
			    packages=$DEBIAN_10_PKG
			    ;;
		    esac
		    ;;
		(ubuntu|neon)
		    case "$VERSION_ID" in
			(18.04)
			    packages=$UBUNTU_18_04_PKG
			    ;;
			(19.10)
			    packages=$UBUNTU_19_10_PKG
			    ;;
		    esac
		    ;;
		(linuxmint)
		    case "$VERSION_ID" in
			(19.2)
			    packages=$UBUNTU_18_04_PKG
			    ;;
		    esac
		    ;;
		(kali)
		    case "$VERSION_ID" in
			(2019.3)
			    packages=$DEBIAN_10_PKG
			    ;;
		    esac
		    ;;
		(opensuse-*)
		    packages=$OPENSUSE_PKG
		    ;;
		(fedora)
		    packages=$FEDORA_PKG
		    ;;
		(rhel|ol|centos)
		    packages=$REDHAT_PKG
		    ;;
	    esac
	    ;;
	(Darwin)
	    packages=$DARWIN_PKG
	    ;;
	(FreeBSD)
	    packages=$FREEBSD_PKG
	    ;;
	(NetBSD)
	    packages=$NETBSD_PKG
	    ;;
	(SunOS)
	    case "$ID" in
		(illumos)
		    packages=$ILLUMOS_PKG
		    ;;
		(solaris)
		    packages=$SOLARIS_PKG
		    ;;
	    esac
	    ;;
    esac

    printf "%s\n" ${packages-}
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_mysql_common_packages
