#!/bin/sh -eu

# get-tk-build-deps: get list of Tcl/Tk build dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Wiki page: https://github.com/pyenv/pyenv/wiki

DEBIAN_PKGS="tk-dev"

FREEBSD_PKGS="tcl86 tk86"

OPENSUSE_PKGS="tk-devel"

REDHAT_PKGS="tk-devel"

SOLARIS_PKGS=""

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_tk_build_deps() {
    packages=

    case "$ID" in
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
	    	    packages=$DEBIAN_PKGS
		    ;;
	    esac
	    ;;
	(opensuse-*)
	    packages=$OPENSUSE_PKGS
	    ;;
	(rhel|ol|centos|fedora|amzn)
	    packages=$REDHAT_PKGS
	    ;;
	(ubuntu)
	    packages=$DEBIAN_PKGS
	    ;;
	(freebsd)
	    packages=$FREEBSD_PKGS
	    ;;
	(illumos)
	    packages=$SOLARIS_PKGS
	    ;;
	(solaris)
	    packages=$SOLARIS_PKGS
	    ;;
    esac

    format-python-packages ${packages-}
}

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_tk_build_deps
