#!/bin/sh -eu

# get-os-release: print OS distro/release information
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FILE=/etc/release
OS_FILE=/etc/os-release

export_all() {
    export_basic
    export_extended
}

export_basic() {
    printf "ID=%s\n" "$ID"
    printf "NAME=\"%s\"\n" "$NAME"
    printf "PRETTY_NAME=\"%s\"\n" "$PRETTY_NAME"
    printf "VERSION_ID=%s\n" "$VERSION_ID"
}

export_extended() {
    printf "distro_name=%s\n" "$ID"
    printf "kernel_name=%s\n" "$kernel_name"
    printf "kernel_release=%s\n" "$kernel_release"
    printf "pretty_name=\"%s\"\n" "$PRETTY_NAME"
}

print_id() {
    if [ -n "${ID:-}" ]; then
	printf "%s\n" "$ID"
    fi
}

print_name() {
    if [ -n "${NAME:-}" ]; then
	printf "%s\n" "$NAME"
    fi
}

print_kernel_name() {
    if [ -n "${kernel_name:-}" ]; then
	printf "%s\n" "$kernel_name"
    fi
}

print_kernel_release() {
    if [ -n "${kernel_release:-}" ]; then
	printf "%s\n" "$kernel_release"
    fi
}

print_pretty_name() {
    if [ -n "${PRETTY_NAME:-}" ]; then
	printf "%s\n" "$PRETTY_NAME"
    fi
}

print_version_id() {
    if [ -n "${VERSION_ID:-}" ]; then
	printf "%s\n" "$VERSION_ID"
    fi
}

usage() {
    printf "Usage: %s: [-a|-b|-h|-i|-k|-n|-p|-r]\n" $(basename "$0")
}

input=$(uname -sr)
kernel_name=${input% *}
kernel_release=${input#* }

case "$kernel_name" in
    (Linux)
	. $OS_FILE
	;;

    (SunOS)
	input=$(awk 'NR == 1 {printf("%s %s:%s\n", $1, $2, $3)}' $FILE)
	NAME=${input%:*}
	VERSION=${input#*:}
	ID=$(printf "%s\n" "${NAME% *}" | tr '[:upper:]' '[:lower:]')
	;;

    (Darwin)
	NAME=$(sw_vers -productName)
	VERSION=$(sw_vers -productVersion)
	ID=macos
	;;

    (CYGWIN_NT-*)
	kernel_release=$(printf "%s\n" "$kernel_release" | sed -e 's/(.*)//')
	NAME="Microsoft Windows"
	VERSION=${kernel_name#*-}
	ID=ms-windows
	VERSION_ID=$VERSION
	;;

    (*)
	NAME=$kernel_name
	VERSION=$kernel_release
	ID=$kernel_name
	VERSION_ID=$kernel_release
	PRETTY_NAME=$input
	;;

esac

if [ -z "${VERSION_ID-}" ]; then
    VERSION_ID="$VERSION"
fi

if [ -z "${PRETTY_NAME-}" ]; then
    PRETTY_NAME="$NAME $VERSION"
fi

if [ $# -eq 0 ]; then
    print_pretty_name
    exit 0
fi

while getopts Xhiknprvx opt
do
     case $opt in
	 (X)
	     export_all
	     ;;
	 (h)
	     usage
	     ;;
	 (i)
	     print_id
	     ;;
	 (k)
	     print_kernel_name
	     ;;
	 (n)
	     print_name
	     ;;
	 (p)
	     print_pretty_name
	     ;;
	 (r)
	     print_kernel_release
	     ;;
	 (v)
	     print_version_id
	     ;;
	 (x)
	     export_basic
	     ;;
	 (?)
	     usage
	     exit 2
	     ;;
     esac
done
