#!/usr/bin/env python3
"""Print configuration parameters."""

import argparse
import configparser

TRANSLATE = str.maketrans('-', '_')


def format_key(key: str, prefix: str):
    """Format application configuration parameter key."""
    return '_'.join([prefix, key]).translate(TRANSLATE).upper()


def format_pair(key: str, value: str, prefix: str):
    """Format application configuration parameter key and value."""
    return "{0}='{1}'".format(format_key(key, prefix), value)


def parse_args():
    """Parse script arguments."""
    description = 'Print application configuration parameters'
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('files',
                        metavar='FILES',
                        nargs='*',
                        help='read from files FILES')
    parser.add_argument('--prefix',
                        metavar='PREFIX',
                        nargs='?',
                        help='prepend string PREFIX')
    parser.add_argument('--sections',
                        metavar='SECTIONS',
                        nargs='*',
                        help='read sections SECTIONS')
    return parser.parse_args()


def main():
    """Print configuration parameters."""
    args = parse_args()
    config = configparser.ConfigParser()

    for filename in args.files:
        config.read(filename)

        for section in (args.sections if args.sections else config.sections()):
            prefix = args.prefix if args.prefix else section

            for key, value in config[section].items():
                print(format_pair(key, value, prefix))


if __name__ == '__main__':
    main()
