#!/bin/bash -eu

# get-askpass: print filename of SSH "askpass" helper binary
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function abort() {
    printf "$@" >&2
    exit 1
}

if [ -z "${DISPLAY:-}" ]; then
    abort "No DISPLAY variable set\n"
fi

askpass_re='/.*/(bin|lib|libexec)/.+askpass$'
desktop_name=$(get-de-name)
distro_name=$(get-distro-name)
platform_name=$(get-platform-name)

case "$platform_name" in
    (Linux)
	case "${distro_name,,[A-Z]}" in
	    (debian|ubuntu)
		case "${desktop_name,,[A-Z]}" in
		    (gnome*|ubuntu:gnome)
			package_name=ssh-askpass-gnome
			;;
		    (kde*|plasma*)
			package_name=ksshaskpass
			;;
		    (*)
			abort "%s: Desktop not supported\n" "$desktop_name"
			;;
		esac
		;;
	    (centos|redhat)
		case "${desktop_name,,[A-Z]}" in
		    (gnome*)
			package_name=openssh-askpass
			;;
		    (kde*|plasma*)
			package_name=ksshaskpass
			;;
		    (*)
			abort "%s: Desktop not supported\n" "$desktop_name"

			;;
		esac
		;;
	    (fedora)
		case "${desktop_name,,[A-Z]}" in
		    (gnome*)
			package_name=openssh-askpass-gnome
			;;
		    (kde*|plasma*)
			package_name=ksshaskpass
			;;
		    (*)
			abort "%s: Desktop not supported\n" "$desktop_name"
			;;
		esac
		;;
	    (opensuse|opensuse-*)
		case "${desktop_name,,[A-Z]}" in
		    (gnome*)
			package_name=openssh-askpass-gnome
			;;
		    (kde*|plasma*)
			package_name=ksshaskpass5
			;;
		    (*)
			abort "%s: Desktop not supported\n" "$desktop_name"
			;;
		esac
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (FreeBSD)
	case "${desktop_name,,[A-Z]}" in
	    (kde*|plasma*)
		package_name=ksshaskpass
		;;
	    (*)
		abort "%s: Desktop not supported\n" "$desktop_name"
		;;
	esac
	;;
    (SunOS)
	case "$distro_name" in
	    (illumos)
		case "${desktop_name,,[A-Z]}" in
		    (mate)
			package_name=ssh-askpass
			;;
		    (*)
			abort "%s: Desktop not supported\n" "$desktop_name"
			;;
		    esac
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (CYGWIN_NT-*)
	case "${desktop_name,,[A-Z]}" in
	    (mate)
		askpass_helper=/usr/libexec/gnome-ssh-askpass.exe
		;;
	    (*)
		abort "%s: Desktop not supported\n" "$desktop_name"
		;;
	esac

	if [ -x "$askpass_helper" ]; then
	    printf "%s\n" "${askpass_helper%.exe}"
	    exit 0
	else
	    abort "%s: No such askpass helper\n" "$askpass_helper"
	fi
	;;
    (*)
	abort "%s: Platform not supported\n" "$platform_name"
	;;
esac

get-package-filenames "$package_name" | egrep "$askpass_re" | head -n 1
