#!/bin/sh -eu

# get-homebrew-packages: get list of Homebrew prequisite packages
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_10_PKGS="linuxbrew-wrapper"

FEDORA_PKGS="file git ruby rubygems"

OPENSUSE_PKGS="file git ruby"

REDHAT_7_PKGS="file git ruby rubygems"
REDHAT_8_PKGS="file git ruby rubygems"

UBUNTU_18_PKGS="file git ruby rubygems"
UBUNTU_19_PKGS="linuxbrew-wrapper"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_homebrew_packages() {
    get-bootstrap-packages
    packages=

    for id in $ID $ID_LIKE; do
	case "$id" in
	    (centos)
		case "$VERSION_ID" in
		    (7)
			packages=$REDHAT_7_PKGS
			;;
		    (8)
			packages=$REDHAT_8_PKGS
			;;
		esac
		;;
	    (debian)
		case "$VERSION_ID" in
		    (10)
			packages=$DEBIAN_10_PKGS
			;;
		esac
		;;
	    (fedora)
		packages=$FEDORA_PKGS
		;;
	    (kali)
		case "$VERSION_ID" in
		    (2019.3)
			packages=$DEBIAN_10_PKGS
			;;
		esac
		;;
	    (linuxmint)
		case "$VERSION_ID" in
		    (19.2)
			packages=$DEBIAN_10_PKGS
			;;
		esac
		;;
	    (opensuse)
		packages=$OPENSUSE_PKGS
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (7.*)
			packages=$REDHAT_7_PKGS
			;;
		    (8.*)
			packages=$REDHAT_8_PKGS
			;;
		esac
		;;
	    (ubuntu)
		case "$VERSION_ID" in
		    (18.04)
			packages=$UBUNTU_18_PKGS
			;;
		    (19.10)
			packages=$UBUNTU_19_PKGS
			;;
		esac
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_homebrew_packages
