#!/bin/bash -eu

# get-git-credential-binary: print filename of git-credential-libsecret binary
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function abort() {
    echo $1 >&2
    exit 1
}

distro_name=$(get-distro-name)
platform_name=$(get-platform-name)

case "$platform_name" in
    (Linux)
	case "$distro_name" in
	    (Debian)
		helper_source="$(get-git-credential-source)"
		helper_binary="${helper_source%.c}"

		if [ "$helper_binary" = cache -o -e "$helper_binary" ]; then
		    echo "$helper_binary"
		else
		    abort "$helper_binary: No such credential helper"
		fi
		;;
	    (Ubuntu)
		echo cache
		;;
	    (CentOS)
		echo cache
		;;
	    (openSUSE)
		get-package-filenames git-credential-libsecret
		;;
	    (*)
		abort "$distro_name: Distro not supported"
		;;
	esac
	;;
    (FreeBSD)
	echo cache
	;;
    (SunOS)
	case "$distro_name" in
	    (illumos)
		echo cache
		;;
	esac
	;;
    (*)
	abort "$platform_name: Platform not supported"
	;;
esac
