#!/bin/sh -eu

# get-os-pretty-name: print short name of OS distribution
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

KEYS="os centos fedora redhat system"

kernel_name="$(get-os-kernel-name)"

case "$kernel_name" in
    (Linux)
	for key in $KEYS; do
	    file=/etc/$key-release

	    if [ -r $file ]; then
		case ${file#/etc/} in
		    (os-release)
			 (. $file && printf "%s\n" "$PRETTY_NAME")
			exit 0
			;;
		    (*-release)
			awk '{print $1}' $file
			exit 0
			;;
		esac
	    fi
	done

	if [ -x /usr/bin/lsb_release ]; then
	    /usr/bin/lsb_release -drs
	fi
	;;
    (SunOS)
	printf "%s\n" "$(uname -sv)"
	;;
    (NT)
	printf "%s %s\n" "Cygwin NT" "$(get-os-release-name)"
	;;
esac
