#!/bin/sh -eu

# get-python-sqlalchemy-packages: get list of Python SQLAlchemy packages names
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="%s-sqlalchemy"

FEDORA_PKGS="%s-sqlalchemy"

FREEBSD_PKGS="%s-sqlalchemy12"

ILLUMOS_PKGS=":%s-sqlalchemy"

NETBSD_PKGS="%s-sqlalchemy"

OPENSUSE_PKGS="%s-SQLAlchemy"

UBUNTU_PKGS="%s-sqlalchemy"

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_sqlalchemy_python_packages() {
    packages=

    case "$ID" in
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
		    packages=$DEBIAN_PKGS
		    ;;
	    esac
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    packages=$UBUNTU_PKGS
		    ;;
		(19.10)
		    packages=$UBUNTU_PKGS
		    ;;
		(20.04)
		    packages=$UBUNTU_PKGS
		    ;;
	    esac
	    ;;
	(fedora)
	    packages=$FEDORA_PKGS
	    ;;
	(opensuse-*)
	    packages=$OPENSUSE_PKGS
	    ;;
	(freebsd)
	    packages=$FREEBSD_PKGS
	    ;;
	(illumos)
	    packages=$ILLUMOS_PKGS
	    ;;
	(netbsd)
	    packages=$NETBSD_PKGS
	    ;;
    esac

    format-python-packages ${packages-}
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_sqlalchemy_python_packages
