#!/bin/sh -eu

# get-uninstalled-packages: filter installed packages from list
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_uninstalled_packages() {
    create_tmpfile
    gnu_grep=$(get_gnu_grep_command)
    "${script_prefix}get-installed-packages" >$tmpfile

    for package; do
	if ! grep_package $gnu_grep $package $tmpfile; then
	   printf "%s\n" "$package"
	fi
    done
}

grep_package() {
    assert [ $# -eq 3 ]
    assert [ -n "$1" ]
    assert [ -n "$2" ]
    assert [ -n "$3" ]
    quoted_package=$(printf "%s\n" "$2" | sed -e 's/\+/\\\+/g')
    "$1" -Eq '^'"$quoted_package"'([0-9]*|-[0-9\.]+)?(nb[0-9]+)?$' "$3"
}

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

eval $("${script_prefix}get-os-release" -x)
get_uninstalled_packages "$@"
