#!/bin/sh -eu

# get-emacs-build-extras: get list of GNU Emacs build extras
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="libgif-dev libgnutls28-dev libgpm-dev libjpeg-dev \
libncurses5-dev libtiff5-dev libwebkit2gtk-4.0-dev libxpm-dev"

FEDORA_PKGS="cairo-devel GConf2-devel giflib-devel gnutls-devel gpm-devel \
gtk3-devel ImageMagick-devel lcms2-devel libacl-devel libICE-devel \
libjpeg-turbo-devel libpng-devel librsvg2-devel libSM-devel libtiff-devel \
libX11-devel libXaw-devel libXext-devel libXi-devel libxml2-devel \
libXmu-devel libXpm-devel libXrandr-devel libXt-devel libXtst-devel \
libXv-devel libxml2-devel make m17n-lib-devel openjpeg-devel ncurses-devel \
webkit2gtk3-devel Xaw3d-devel zlib-devel"

ILLUMOS_PKGS="developer/build/autoconf developer/build/automake \
developer/build/gnu-make developer/build/libtool developer/build/pkg-config \
developer/illumos-gcc image/library/librsvg library/desktop/cairo
library/gnutls library/ncurses library/zlib system/header"

OPENSUSE_PKGS="autoconf automake gcc cairo-devel gconf2-devel giflib-devel \
gpm-devel gtk3-devel ImageMagick-devel libacl-devel libgnutls-devel \
libjpeg62-devel libICE-devel liblcms2-devel libpng16-devel librsvg-devel \
libSM-devel libtiff-devel libtool libX11-devel libXaw3d-devel libXext-devel \
libXi-devel libXmu-devel libXpm-devel libXrandr-devel libXt-devel \
libXtst-devel libXv-devel libxml2-devel make m17n-lib-devel \
ncurses5-devel webkit2gtk3-devel zlib-devel"

REDHAT_7_PKGS="autoconf automake cairo-devel GConf2-devel giflib-devel \
gnutls-devel gpm-devel gtk3-devel ImageMagick-devel lcms2-devel libacl-devel \
libICE-devel libjpeg-turbo-devel libotf-devel libpng-devel librsvg2-devel \
libSM-devel libtiff-devel libtool libX11-devel libXaw-devel libXext-devel \
libXi-devel libxml2-devel libXmu-devel libXpm-devel libXrandr-devel \
libXt-devel libXtst-devel libXv-devel make m17n-lib-devel ncurses-devel \
openjpeg-devel pkgconfig webkitgtk4-devel Xaw3d-devel zlib-devel"

REDHAT_8_PKGS="cairo-devel gnutls-devel gpm-devel gtk3-devel libacl-devel \
libICE-devel libjpeg-turbo-devel libpng-devel librsvg2-devel libSM-devel \
libtiff-devel libX11-devel libXaw-devel libXext-devel libXi-devel \
libxml2-devel libXmu-devel libXpm-devel libXrandr-devel libXt-devel \
libXtst-devel libXv-devel make ncurses-devel webkit2gtk3-devel zlib-devel"

SOLARIS_PKGS="developer/build/autoconf developer/build/automake \
developer/build/gnu-make developer/build/libtool developer/build/pkg-config \
developer/developerstudio-126/cc developer/developerstudio-126/library/c-libs \
image/library/librsvg library/desktop/cairo library/desktop/webkitgtk4 \
library/gnome/dconf library/gnutls library/ncurses library/zlib system/header \
:CSWlibgif-dev"

UBUNTU_PKGS="libdbus-1-dev libgif-dev libgnutls28-dev libgpm-dev libjpeg-dev \
liblcms2-dev libm17n-dev libncurses5-dev libotf-dev librsvg2-dev libtiff5-dev \
libwebkit2gtk-4.0-dev libxml2-dev libxpm-dev"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}


get_emacs_build_deps() {
    packages=

    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
		packages=$DEBIAN_PKGS
		;;
	    (fedora)
		packages=$FEDORA_PKGS
		;;
	    (opensuse)
		packages=$OPENSUSE_PKGS
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (7|7.[78])
			packages=$REDHAT_7_PKGS
			;;
		    (8|8.[01])
			packages=$REDHAT_8_PKGS
			;;
		esac
		;;
	    (ubuntu)
		packages=$UBUNTU_PKGS
		;;
	    (illumos)
		packages=$ILLUMOS_PKGS
		;;
	    (solaris)
		packages=$SOLARIS_PKGS
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)

get_emacs_build_deps
