#!/usr/bin/env python3

# get-odbc-driver-info: print installed ODBC driver details
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import configparser
import os
import re

DRIVER_MSSQL = re.compile(r'libmsodbcsql-\d+\.\d+\.so\.\d+\.\d+')
DRIVER_MYSQL = re.compile(r'libmyodbc\d+w\.so')
DRIVER_POSTGRES = re.compile(r'psqlodbcw\.so')

ODBC_DRIVERS = '/etc/odbcinst.ini'

SQL_DIALECTS = {
    'mssql': (DRIVER_MSSQL, 1403, 'sa', 'MSSQL'),
    'mysql': (DRIVER_MYSQL, 3306, 'root', 'MySQL'),
    'postgres': (DRIVER_POSTGRES, 5432, 'postgres', 'PostgreSQL'),
}


def enumerate_drivers():
    inifile = configparser.ConfigParser()
    inifile.read(ODBC_DRIVERS)
    drivers = {}

    for driver in inifile.sections():
        pathname = inifile[driver]['Driver']
        filename = os.path.basename(pathname)

        for dialect in SQL_DIALECTS:
            sql_dialect = SQL_DIALECTS[dialect]
            regex = sql_dialect[0]

            if regex.fullmatch(filename):
                drivers[dialect] = driver

    return drivers


def main():
    drivers = enumerate_drivers()
    print(drivers)

    for driver in drivers:
        print(SQL_DIALECTS[driver])


if __name__ == '__main__':
    main()
