#!/bin/sh -eu

# get-python3-development-tools: get list of Python 3 development tools
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_PKGS=""

DEBIAN_PKGS="%s-pip %s-virtualenv"

FEDORA_PKGS="%s-pip %s-virtualenv"

FREEBSD_PKGS="%s-pip %s-virtualenv"

OPENSUSE_PKGS="%s-pip %s-virtualenv"

REDHAT_PKGS=":%s-pip :%s-virtualenv"

SUNOS_PKGS="pip-%s"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

case "$kernel_name" in
    (Linux|GNU)
	case "$ID" in
	    (debian|raspbian|ubuntu|linuxmint|neon|kali)
	    	packages=$DEBIAN_PKGS
	    	;;
	    (opensuse-*)
	    	packages=$OPENSUSE_PKGS
	    	;;
	    (fedora)
	    	packages=$FEDORA_PKGS
	    	;;
	    (ol|centos)
		packages=$REDHAT_PKGS
		;;
	esac
	;;
    (Darwin)
	packages=$DARWIN_PKGS
	;;
    (FreeBSD)
	packages=$FREEBSD_PKGS
	;;
    (SunOS)
	packages=$SUNOS_PKGS
	;;
esac

data=$("$script_dir/get-python-metadata")
package_name=$(printf "%s" "$data" | awk '{print $1}')
package_modifier=$(printf "%s" "$data" | awk '{print $2}')

# printf "%s\n" $package_name

for package in ${packages-}; do
    case $package in
	(*%s*)
	    printf "$package\n" $package_modifier
	    ;;
	(*)
	    printf "%s\n" $package
	    ;;
    esac
done
