#!/bin/sh -eu

# get-kubernetes-packages: list Kubernetes package names
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="kubeadm kubectl kubelet"

REDHAT_PKGS="kubeadm kubectl kubelet"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
}

get_docker_ce_packages() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (centos)
		packages=$REDHAT_PKGS
		;;
	    (debian)
		packages=$DEBIAN_PKGS
		;;
	    (fedora)
		packages=$REDHAT_PKGS
		;;
	    (rhel|ol)
		packages=$REDHAT_PKGS
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    if [ -n "${packages-}" ]; then
	printf '%s\n' $packages
    fi
}

eval $(get-os-release -x)

get_docker_ce_packages
