#!/bin/bash -eu

# get-askpass: print filename of SSH "askpass" helper binary
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

case "$(get-platform-name)" in
    (Linux)
	case "$(get-distro-name)" in
	    (Debian)
		case "$(get-de-name)" in
		    (gnome*)
			package_name=ssh-askpass-gnome
			;;
		    (kde*|plasma*)
			package_name=kaskpass
			;;
		    esac
		;;
	    (openSUSE)
		case "$(get-de-name)" in
		    (gnome*)
			package_name=openssh-askpass-gnome
			;;
		    (kde*|plasma*)
			package_name=ksshaskpass5
			;;
		    esac
		;;
	esac
	;;
esac

if [ -n "$package_name" ]; then
    get-package-filenames "$package_name" | grep 'askpass$'
fi
