#!/bin/sh -eu

# get-realpath: print resolved, absolute path names (following links)
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

get_realpath() {
    if [ -x /bin/realpath ]; then
	exec /bin/realpath "$@"
    else
	error=false
	quiet=false

	while getopts qh opt; do
	    case $opt in
		(q)
		    quiet=true
		    ;;
		(h)
		    usage
		    exit 0
		    ;;
		(\?)
		    exit 2
		    ;;
	    esac
	done

	shift $(($OPTIND - 1))

	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		if [ -d "$(dirname "$file")" -o "$quiet" = true ]; then
		    printf '%s\n' "$file"
		else
		    printf '%s: %s: No such file or directory\n' \
			   "$script" "$file" >&2
		    error=true
		fi
	    else
		printf '%s\n' "$PWD/${file#./}"
	    fi
	done
    fi

    if [ "$error" = true ]; then
	return 1
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script [-q] PATH [PATH [...]]

Print resolved, absolute path names.
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

get_realpath "$@"
