#!/bin/sh -eu

# get-emacs-build-extras: get list of GNU Emacs build extras
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="libgif-dev libgnutls28-dev libgpm-dev libjpeg-dev \
libncurses5-dev libtiff5-dev libwebkit2gtk-4.0-dev libxpm-dev"

FEDORA_PKGS="GConf2-devel giflib-devel gnutls-devel gpm-devel gtk3-devel \
ImageMagick-devel lcms2-devel libacl-devel libICE-devel libjpeg-turbo-devel \
libpng-devel libSM-devel libtiff-devel libX11-devel libXaw-devel \
libXext-devel libXi-devel libXmu-devel libXpm-devel libXrandr-devel \
libXt-devel libXtst-devel libXv-devel libxml2-devel make m17n-lib-devel \
openjpeg-devel ncurses-devel zlib-devel webkit2gtk3-devel Xaw3d-devel"

REDHAT_7_PKGS="GConf2-devel giflib-devel gnutls-devel gpm-devel gtk3-devel \
ImageMagick-devel lcms2-devel libacl-devel libICE-devel libjpeg-turbo-devel \
libpng-devel libSM-devel libtiff-devel libX11-devel libXaw-devel \
libXext-devel libXi-devel libXmu-devel libXpm-devel libXrandr-devel \
libXt-devel libXtst-devel libXv-devel libxml2-devel make m17n-lib-devel \
openjpeg-devel ncurses-devel zlib-devel Xaw3d-devel"

REDHAT_8_PKGS="gnutls-devel gpm-devel gtk3-devel libacl-devel libICE-devel \
libjpeg-turbo-devel libpng-devel libSM-devel libtiff-devel libX11-devel \
libXaw-devel libXext-devel libXi-devel libXmu-devel libXpm-devel \
libXrandr-devel libXt-devel libXtst-devel libXv-devel libxml2-devel make \
ncurses-devel zlib-devel"

OPENSUSE_PKGS="gcc gconf2-devel giflib-devel gpm-devel gtk3-devel \
ImageMagick-devel libacl-devel libgnutls-devel libjpeg62-devel \
libICE-devel liblcms2-devel libpng16-devel libSM-devel libtiff-devel \
libX11-devel libXaw3d-devel libXext-devel libXi-devel libXmu-devel \
libXpm-devel libXrandr-devel libXt-devel libXtst-devel libXv-devel \
libxml2-devel make m17n-lib-devel ncurses5-devel zlib-devel \
webkit2gtk3-devel"

SOLARIS_PKGS="developer/build/make developer/build/pkg-config \
image/library/libpng10 library/gnutls library/libjpeg \
library/ncurses library/zlib"

UBUNTU_PKGS="libgif-dev libgnutls28-dev libgpm-dev libjpeg-dev \
libncurses5-dev libtiff5-dev libwebkit2gtk-4.0-dev libxpm-dev"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}


get_emacs_build_extras() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (ms-windows)
		break
		;;
	    (debian)
		packages=$DEBIAN_PKGS
		;;
	    (fedora)
		packages=$FEDORA_PKGS
	    	;;
	    (opensuse)
		packages=$OPENSUSE_PKGS
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (7|7.[78])
			packages=$REDHAT_7_PKGS
			;;
		    (8|8.[01])
			packages=$REDHAT_8_PKGS
			;;
		esac
		;;
	    (freebsd)
		break
		;;
	    (solaris)
		packages=$SOLARIS_PKGS
		;;
	    (ubuntu)
		packages=$UBUNTU_PKGS
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)

get_emacs_build_extras
