#!/bin/sh -eu

# get-uwsgi-packages: get uWSGI app server package names
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_10_PKGS="util-linux uwsgi uwsgi-plugin-%s"

FEDORA_PKGS="util-linux uwsgi uwsgi-plugin-%s"

FREEBSD_PKGS="uwsgi"

MACOS_PKGS=":%s-uwsgi"

NETBSD_PKGS="%s-uwsgi"

OPENSUSE_PKGS="system-user-wwwrun util-linux uwsgi uwsgi-%s"

REDHAT_7_PKGS=":%s-uwsgi"
REDHAT_8_PKGS="util-linux uwsgi uwsgi-plugin-%s"

SOLARIS_PKGS=":%s-uwsgi"

UBUNTU_18_PKGS="setpriv uwsgi uwsgi-plugin-%s"
UBUNTU_19_PKGS="util-linux uwsgi uwsgi-plugin-%s"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_uwsgi_packages() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
		packages=$DEBIAN_10_PKGS
		;;
	    (ubuntu)
		case "$VERSION_ID" in
		    (18.*)
			packages=$UBUNTU_18_PKGS
			;;
		    (19.*)
			packages=$UBUNTU_19_PKGS
			;;
		esac
		;;
	    (opensuse-)
		packages=$OPENSUSE_PKGS
		;;
	    (fedora)
		packages=$FEDORA_PKGS
		;;
	    (rhel|ol|centos)
		case "$VERSION_ID" in
		    (7|7.*)
			packages=$REDHAT_7_PKGS
			;;
		    (8|8.*)
			packages=$REDHAT_8_PKGS
			;;
		esac
		;;
	    (freebsd)
		packages=$FREEBSD_PKGS
		;;
	    (macos)
		packages=$MACOS_PKGS
		;;
	    (netbsd)
		packages=$NETBSD_PKGS
		;;
	    (solaris)
		packages=$SOLARIS_PKGS
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    get-python-packages ${packages-}
}

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_uwsgi_packages
