#!/bin/sh -eu

# get-docker-packages: get Docker package names
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_PKG="docker"

DEBIAN_10_PKG="docker.io"

FEDORA_PKG="docker"

FREEBSD_PKG="docker-machine"
FREEBSD_PKGS="docker"

OPENSUSE_PKG="docker"

REDHAT_PKG="podman"
REDHAT_PKGS="podman-docker"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_docker_packages() {
    package=$("$script_dir/get-installed-docker-package")

    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian|kali)
		    case "$VERSION_ID" in
			(10)
			    packages="${package:-$DEBIAN_10_PKG} ${DEBIAN_10_PKGS-}"
			    ;;
		    esac
		    ;;
		(ubuntu|linuxmint|neon)
		    packages="${package:-$DEBIAN_10_PKG} ${DEBIAN_10_PKGS-}"
		    ;;
		(opensuse-leap)
		    packages="${package:-$OPENSUSE_PKG} ${OPENSUSE_LP_PKGS-}"
		    ;;
		(opensuse-tumbleweed)
		    packages="${package:-$OPENSUSE_PKG} ${OPENSUSE_TW_PKGS-}"
		    ;;
		(fedora)
		    packages="${package:-$FEDORA_PKG} ${FEDORA_PKGS-}"
		    ;;
		(ol|rhel)
		    case "$VERSION_ID" in
			(8|8.*)
			    packages="${package:-$REDHAT_PKG} ${REDHAT_PKGS-}"
			    ;;
		    esac
		    ;;
	    esac
	    ;;
	(Darwin)
	    packages="${package:-$DARWIN_PKG} ${DARWIN_PKGS-}"
	    ;;
	(FreeBSD)
	    packages="${package:-$FREEBSD_PKG} ${FREEBSD_PKGS-}"
	    ;;
    esac

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

get_docker_packages
