#!/bin/sh -eu

# get-askpass-package: get name of package with askpass helper
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
}

get_askpass_package() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
		case "$desktop_name" in
		    (GNOME|GNOME*|*:GNOME|LXDE|X-Cinnamon|'')
			package=ssh-askpass-gnome
			;;
		    (KDE*)
			package=ksshaskpass
			;;
		    (*)
			break
			;;
		esac
		;;
	    (opensuse)
		case "$desktop_name" in
		    (GNOME|GNOME*|*:GNOME|'')
			package=openssh-askpass-gnome
			;;
		    (KDE*)
			package=ksshaskpass5
			;;
		    (*)
			break
			;;
		esac
		;;
	    (rhel|fedora)
		case "$desktop_name" in
		    (GNOME|GNOME*|*:GNOME|'')
			package=openssh-askpass
			;;
		    (KDE*)
			package=ksshaskpass
			;;
		    (*)
			break
			;;
		esac
		;;
	    (freebsd)
		case "$desktop_name" in
		    (GNOME|GNOME*|MATE|'')
			package=gnome-ssh-askpass
			;;
		    (KDE*)
			package=ksshaskpass
			;;
		    (*)
			break
			;;
		esac
		;;
	    (macos)
		break
		;;
	    (netbsd)
		break
		;;
	    (solaris)
		break
		;;
	    (windows)
		break
		;;
	esac

	if [ -n "${package-}" ]; then
	    break
	fi
    done

    if [ -n "${package-}" ]; then
	printf "%s\n" $package
    fi
}

parse_arguments() {
    while getopts h opt; do
	case $opt in
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -eq 1 ]; then
	desktop_name="$1"
    else
	desktop_name=$("${script_prefix}get-desktop-name")
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script [DESKTOP-ENVIRONMENT]
       $script -h
EOF
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

eval $("${script_prefix}get-os-release" -x)
parse_arguments "$@"
get_askpass_package
