#!/bin/sh -eu

# get-python-devel-packages: get list of Python PIP packages
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AMAZON_2_PKGS="%s-pip"

DEBIAN_PKGS="%s-packaging %s-pip %s-wheel"

FREEBSD_PKGS="%s-packaging %s-pip"

FEDORA_PKGS="%s-packaging %s-pip"

ILLUMOS_PKGS=":%s-packaging :%s-pip"

MACOS_HOMEBREW_PKGS=

NETBSD_PKGS="%s-packaging %s-pip"

OPENSUSE_PKGS="%s-packaging %s-pip %s-wheel"

REDHAT_7_PKGS=":%s-packaging :%s-pip"
REDHAT_8_PKGS="%s-pip"

SOLARIS_PKGS="library/python/pip-%s"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_python_pip_packages() {
    packages=

    case "$ID" in
	(amzn)
	    case "$VERSION_ID" in
		(2)
		    packages=$AMAZON_2_PKGS
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    packages="$DEBIAN_PKGS pylint3"
	    ;;
	(opensuse)
	    packages=$OPENSUSE_PKGS
	    ;;
	(fedora)
	    packages=$FEDORA_PKGS
	    ;;
	(rhel|ol|centos)
	    case "$VERSION_ID" in
		(7|7.*)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8|8.*)
		    packages=$REDHAT_8_PKGS
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    packages="$DEBIAN_PKGS pylint3"
		    ;;
		(19.10)
		    packages="$DEBIAN_PKGS pylint"
		    ;;
		(20.04)
		    packages="$DEBIAN_PKGS pylint"
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
	(freebsd)
	    packages=$FREEBSD_PKGS
	    ;;
	(illumos)
	    packages=$ILLUMOS_PKGS
	    ;;
	(macos)
	    packages=$MACOS_HOMEBREW_PKGS
	    ;;
	(netbsd)
	    packages=$NETBSD_PKGS
	    ;;
	(solaris)
	    packages=$SOLARIS_PKGS
	    ;;
    esac

    get-python-packages ${packages-}
}

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_python_pip_packages
