#!/bin/sh -eu

# get-mysql-client-packages: get MySQL database client package names
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_10_PKG="mariadb-client-10.3"

FEDORA_PKG="mariadb"

FREEBSD_PKG="mariadb103-client"

ILLUMOS_PKG="database/mariadb-101/client"

MACOS_HOMEBREW_PKG="mariadb"

NETBSD_PKG="mariadb-client"

OPENSUSE_PKG="mariadb-client"

REDHAT_PKG="mariadb"

SOLARIS_PKG="database/mysql-57/client"

UBUNTU_18_PKG="mariadb-client-10.1"
UBUNTU_19_PKG="mariadb-client-10.3"
UBUNTU_20_PKG="mariadb-client-10.3"

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_mysql_client_packages() {
    package=$(get-installed-mysql-package client)

    case "$package" in
	(*-client-core-*)
	    package=$(printf "%s\n" $package | sed -e 's/-core-/-/')
	    ;;
    esac

    case "$ID" in
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
		    packages="${package:-$DEBIAN_10_PKG}"
		    ;;
	    esac
	    ;;
	(fedora)
	    packages="${package:-$FEDORA_PKG}"
	    ;;
	(opensuse-*)
	    packages="${package:-$OPENSUSE_PKG}"
	    ;;
	(rhel|ol|centos)
	    packages="${package:-$REDHAT_PKG}"
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    packages="${package:-$UBUNTU_18_PKG}"
		    ;;
		(19.10)
		    packages="${package:-$UBUNTU_19_PKG}"
		    ;;
		(20.04)
		    packages="${package:-$UBUNTU_20_PKG}"
		    ;;
	    esac
	    ;;
	(freebsd)
	    packages="${package:-$FREEBSD_PKG}"
	    ;;
	(illumos)
	    packages="${package:-$ILLUMOS_PKG}"
	    ;;
	(macos)
	    packages="${package:-$MACOS_HOMEBREW_PKG}"
	    ;;
	(netbsd)
	    packages="${package:-$NETBSD_PKG}"
	    ;;
	(solaris)
	    packages="${package:-$SOLARIS_PKG}"
	    ;;
    esac

    printf "%s\n" ${packages-}
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_mysql_client_packages
