#!/bin/sh -eu

# get-git-credential-binary: print filename of git-credential-libsecret binary
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CREDENTIAL_HELPER_RE='/.+/git-credential-libsecret$'

abort() {
    printf "$@" >&2
    exit 1
}

distro_name=$(get-distro-name | to-lower)
platform_name=$(get-platform-name)

case "$platform_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
		helper_source="$(get-git-credential-source)"
		helper_binary="${helper_source%.c}"

		if [ "$helper_binary" = cache -o -x "$helper_binary" ]; then
		    printf "%s\n" "$helper_binary"
		else
		    abort "%s: No such credential helper\n" "$helper_binary"
		fi
		;;
	    (fedora)
		get-package-filenames git | egrep "$CREDENTIAL_HELPER_RE"
		;;
	    (opensuse|opensuse-*)
		get-package-filenames git-credential-libsecret
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (CYGWIN_NT-*)
	helper_binary=/usr/libexec/git-core/git-credential-manager.exe

	if [ -x "$helper_binary" ]; then
	    printf "%s\n" "${helper_binary%.exe}"
	else
	    abort "%s: No such credential helper\n" "$helper_binary"
	fi
	;;
    (*)
	abort "%s: Platform not supported\n" "$platform_name"
	;;
esac
