#!/bin/sh -eu

# get-system-name: print short name of operating system family
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

kernel_name="$(get-os-kernel-name)"

case "$kernel_name" in
    (NT)
	echo Windows
	;;
    (Darwin|FreeBSD)
	echo BSD
	;;
    (GNU)
	echo $kernel_name
	;;
    (Linux)
	echo GNU/$kernel_name
	;;
    (SunOS)
	echo Unix
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac
