#!/bin/sh -eu

# get-oracle-client-packages: get list of Oracle client packages
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_10_PKGS="libaio1 libodbc1"

REDHAT_7_PKGS="libaio"
REDHAT_8_PKGS="libaio"

UBUNTU_18_PKGS="libaio1 libodbc1"
UBUNTU_19_PKGS="libaio1 libodbc1"
UBUNTU_20_PKGS="libaio1 libodbc1"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_oracle_client_packages() {
    packages=

    case "$ID" in
	(centos)
	    case "$VERSION_ID" in
		(7)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8)
		    packages=$REDHAT_8_PKGS
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
		    packages=$DEBIAN_10_PKGS
		    ;;
	    esac
	    ;;
	(rhel|ol)
	    case "$VERSION_ID" in
		(7.*)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8.*)
		    packages=$REDHAT_8_PKGS
		    ;;
	    esac
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    packages=$UBUNTU_18_PKGS
		    ;;
		(19.10)
		    packages=$UBUNTU_19_PKGS
		    ;;
		(20.04)
		    packages=$UBUNTU_20_PKGS
		    ;;
		(20.10)
		    packages=$UBUNTU_20_PKGS
		    ;;
	    esac
	    ;;
    esac

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

eval $("${script_prefix}get-os-release" -x)
get_oracle_client_packages
