#!/bin/sh -eu

# get-package-filenames: print filenames associated with package
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWK_EXPR='{ printf("/%s\n", $0) }'

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_path() {
    assert [ -d "$1" ]
    command=$(which realpath)

    if [ -n "$command" ]; then
	$command "$1"
    elif expr "$1" : '/.*' >/dev/null; then
	printf "%s\n" "$1"
    else
	printf "%s\n" "$PWD/${1#./}"
    fi
}

if [ $# -eq 0 ]; then
    abort "%s: Not enough arguments\n" "$0"
fi

script_dir=$(get_path "$(dirname "$0")")

eval $($script_dir/get-os-release -X)

case "$kernel_name" in
    (Linux)
	case "$ID" in
	    (debian|ubuntu)
		dpkg --listfiles "$1"
		;;
	    (opensuse-*|fedora|redhat|centos)
		rpm --query --list "$1"
		;;
	    (*)
		abort_not_supported Distro
		;;
	esac
	;;
    (FreeBSD)
	pkg query %Fp "$1"
	;;
    (SunOS)
	case "$ID" in
	    (openindiana)
		pkg search -H -o search.match "basename:$1" | awk "$AWK_EXPR"
		;;
	    (*)
		abort_not_supported Distro
		;;
	esac
	;;
    (*)
	abort_not_supported "Operating system"
	;;
esac
