#!/bin/sh -eu

# get-package-install-options: get package installation options
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_package_install_options() {
    options=

    for id in $ID $ID_LIKE; do
	case "$id" in
	    (amzn)
		case "$VERSION_ID" in
		    (2)
			if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
			    options="${options:+$options }-y"
			else
			    break
			fi
			;;
		    (*)
			if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
			    options="${options:+$options }-y"
			else
			    break
			fi
			;;
		esac
		;;
	    (centos)
		case "$VERSION_ID" in
		    (7)
			if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
			    options="${options:+$options }-y"
			else
			    break
			fi
			;;
		    (8)
			if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
			    options="${options:+$options }-y"
			fi

			options="${options:+$options }--nobest"
			;;
		    (*)
			if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
			    options="${options:+$options }-y"
			else
			    break
			fi
			;;
		esac
		;;
	    (debian)
		if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
		    options="${options:+$options }-y"
		fi

		options="${options:+$options }--no-install-recommends"
		;;
	    (fedora)
		if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
		    options="${options:+$options }-y"
		fi

		options="${options:+$options }--allowerasing"
		;;
	    (opensuse)
		options="${options:+$options }--no-recommends"
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (8.*)
			if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
			    options="${options:+$options }-y"
			fi

			options="${options:+$options }--nobest"
			;;
		    (*)
			if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
			    options="${options:+$options }-y"
			else
			    break
			fi
			;;
		esac
		;;
	    (solaris)
		options="${options:+$options }--accept"
		;;
	esac

	if [ -n "${options-}" ]; then
	    break
	fi
    done

    if [ $# -gt 0 ]; then
	options="${options:+$options }$@"
    fi

    if [ -n "${options-}" ]; then
	printf "%s\n" "$options"
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

eval $("${script_prefix}get-os-release" -x)
get_package_install_options "$@"
