#!/bin/sh -eu

# get-git-build-packages: get list of Git build dependencies
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AMAZON_2_PKGS=""

DEBIAN_PKGS=""

FEDORA_PKGS=""

ILLUMOS_PKGS=""

MACOS_HOMEBREW_PKGS=""

OPENSUSE_PKGS=""

REDHAT_7_PKGS="curl-devel expat-devel openssl-devel"

FREEBSD_11_PKGS=""
FREEBSD_12_RELEASE_PKGS=""
FREEBSD_12_STABLE_PKGS=""

SOLARIS_PKGS=""

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_git_packages() {
    packages=

    case "$ID" in
	(amazon)
	    case "$VERSION_ID" in
		(2)
		    packages=$AMAZON_2_PKGS
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
	(centos)
	    case "$VERSION_ID" in
		(7)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8)
		    packages=$REDHAT_8_PKGS
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    packages=$DEBIAN_PKGS
	    ;;
	(fedora)
	    packages=$FEDORA_PKGS
	    ;;
	(opensuse-*)
	    packages=$OPENSUSE_PKGS
	    ;;
	(rhel|ol)
	    case "$VERSION_ID" in
		(7.*)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8.*)
		    packages=$REDHAT_8_PKGS
		    ;;
	    esac
	    ;;
	(freebsd)
	    case "$VERSION_ID" in
		(11.3-*)
		    packages=$FREEBSD_11_PKGS
		    ;;
		(12.1-RELEASE-*)
		    packages=$FREEBSD_12_RELEASE_PKGS
		    ;;
		(12.1-STABLE)
		    packages=$FREEBSD_12_STABLE_PKGS
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
	(illumos)
	    packages=$ILLUMOS_PKGS
	    ;;
	(macos)
	    packages=$MACOS_HOMEBREW_PKGS
	    ;;
	(solaris)
	    packages=$SOLARIS_PKGS
	    ;;
    esac

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_git_packages
