#!/bin/sh -eu

# get-install-command: get package manager install command
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_install_command() {
    case "$1" in
	(apt-get|*/apt-get)
	    install=install
	    ;;
	(brew|*/brew)
	    install=install
	    ;;
	(dnf|*/dnf)
	    install=install
	    ;;
	(pkg|*/pkg)
	    install=install
	    ;;
	(pkgin|*/pkgin)
	    install=install
	    ;;
	(pkgutil|*/pkgutil)
	    install=install
	    ;;
	(yum|*/yum)
	    install=install
	    ;;
	(zypper|*/zypper)
	    install=install
	    ;;
	(*)
	    install=install
	    ;;
    esac

    if [ "${install-}" ]; then
	printf "%s\n" "$install"
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

if [ $# -eq 0 ]; then
    abort "%s: Not enough arguments\n" "$0"
fi

if [ $# -gt 1 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

get_install_command "$@"
