#!/bin/sh -eu

# get-os-release: print OS distro/release information
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FILE=/etc/release
OS_FILE=/etc/os-release

system_name="$(uname -s)"

case "$system_name" in
    (Linux)
	. $OS_FILE
	;;
    (Darwin|FreeBSD|GNU|Minix)
	ID=
	PRETTY_NAME=$(uname -sr)
	VERSION_ID=$(uname -r)
	;;
    (SunOS)
	ID=$(awk 'NR == 1 {print $1}' $FILE | tr '[:upper:]' '[:lower:]')
	PRETTY_NAME=$(awk 'NR == 1 {printf("%s %s %s\n", $1, $2, $3)}' $FILE)
	VERSION_ID=$(awk 'NR == 1 {print $3}' $FILE)
	;;
    (CYGWIN_NT-*)
	ID=
	PRETTY_NAME=$system_name
	VERSION_ID=${system_name#*-}
	;;
esac

while getopts hipr opt
do
     case $opt in
	 (h)
	     printf "Usage: %s: [-h|-i|-p|-r]\n" $(basename "$0")
	     ;;
	 (i)
	     if [ -n "${ID:-}" ]; then
		 printf "%s\n" "$ID"
	     fi
	     ;;
	 (p)
	     if [ -n "${PRETTY_NAME:-}" ]; then
		 printf "%s\n" "$PRETTY_NAME"
	     fi
	     ;;
	 (r)
	     if [ -n "${VERSION_ID:-}" ]; then
		 printf "%s\n" "$VERSION_ID"
	     fi
	     ;;
	 (?)
	     printf "Usage: %s: [-d | -p | -r]\n" $(basename "$0")
	     exit 2
	     ;;
     esac
done

shift $(($OPTIND - 1))
