#!/bin/sh

# get-mysql-errors: get MySQL server log contents
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

configure_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
		log_dir=/var/log/mysql
		log_file=error.log
		;;
	    (fedora)
		log_dir=/var/log/mariadb
		log_file=mariadb.log
		;;
	    (opensuse)
		log_dir=/var/log/mysql
		log_file=mysqld.log
		;;
	    (rhel)
		log_dir=/var/log/mariadb
		log_file=mariadb.log
		;;
	    (illumos)
		log_dir=/var/mariadb/*/data
		log_file=$(hostname).err
		;;
	    (solaris)
		log_dir=/var/mysql/*/data
		log_file=$(hostname).err
		;;
	esac

	if [ -n "${log_dir-}" ]; then
	    break
	elif [ -n "${log_file-}" ]; then
	    break
	fi
    done
}

get_mysql_errors() {
    validate_platform
    configure_platform
    cat "$log_dir/$log_file"
}

validate_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
		return
		;;
	    (fedora)
		return
		;;
	    (opensuse)
		return
		;;
	    (rhel)
		return
		;;
	    (freebsd)
		break
		;;
	    (macos)
		break
		;;
	    (netbsd)
		break
		;;
	    (solaris)
		return
		;;
	esac
    done

    abort_not_supported "Operating system"
}

eval $(get-os-release -x)

get_mysql_errors
