#!/bin/sh -eu

# get-emacs-build-extras: get list of GNU Emacs build extras
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="libgnutls28-dev libgpm-dev libwebkit2gtk-4.0-dev"

REDHAT_PKGS="GConf2-devel giflib-devel gnutls-devel gpm-devel gtk3-devel \
ImageMagick-devel lcms2-devel libacl-devel libICE-devel libjpeg-turbo-devel \
libpng-devel libSM-devel libtiff-devel libungif-devel libX11-devel \
libXaw-devel libXext-devel libXi-devel libXmu-devel libXpm-devel \
libXrandr-devel libXt-devel libXtst-devel libXv-devel libxml2-devel \
make m17n-lib-devel openjpeg-devel ncurses-devel zlib-devel \
webkit2gtk3-devel Xaw3d-devel"

OPENSUSE_PKGS="gconf2-devel giflib-devel gpm-devel gtk3-devel \
ImageMagick-devel libacl-devel libgnutls-devel libjpeg62-devel \
libICE-devel liblcms2-devel libpng16-devel libSM-devel \
libtiff-devel libX11-devel libXaw3d-devel libXext-devel libXi-devel \
libXmu-devel libXpm-devel libXrandr-devel libXt-devel libXTrap-devel \
libXtst-devel libXv-devel libxml2-devel make m17n-lib-devel \
ncurses5-devel zlib-devel webkit2gtk3-devel"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

case "$kernel_name" in
    (Linux|GNU)
	case "$ID" in
	    (debian|raspbian|ubuntu|linuxmint|neon)
		packages=$DEBIAN_PKGS
		;;
	    (opensuse-*)
		packages=$OPENSUSE_PKGS
		;;
	    (fedora|ol|centos)
		packages=$REDHAT_PKGS
	    	;;
	esac
	;;
    (FreeBSD|SunOS|CYGWIN_NT-*)
	:
	;;
esac

if [ -n "${packages-}" ]; then
    printf "%s\n" $packages
fi
