#!/bin/sh -eu

# get-python-postgres-packages: get list of Python PostgreSQL package names
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

MACOS_HOMEBREW_PKGS="libpq"

REDHAT_8_PKGS="libpq-devel %s-psycopg2"

UBUNTU_PKGS="libpq-dev postgresql-common %s-psycopg2"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_python_postgres_packages() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (centos)
		case "$VERSION_ID" in
		    (7)
			break
			;;
		    (8)
			packages=$REDHAT_8_PKGS
			;;
		    (*)
			break
			;;
		esac
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (7.*)
			break
			;;
		    (8.*)
			packages=$REDHAT_8_PKGS
			;;
		    (*)
			break
			;;
		esac
		;;
	    (ubuntu)
		packages=$UBUNTU_PKGS
		;;
	    (macos)
		packages=$MACOS_HOMEBREW_PKGS
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    get-python-packages ${packages-}
}

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_python_postgres_packages
