#!/bin/sh -eu

# get-python3-packages: get list of Python 3 packages
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CENTOS_7_PKGS="python3"
CENTOS_8_PKGS="python3"

DEBIAN_10_PKGS="python3"

FEDORA_PKGS="python3"

FREEBSD_PKGS="python3"

ILLUMOS_PKGS="python3"

MACOS_HOMEBREW_PKGS="python3"

NETBSD_PKGS="python3"

OPENSUSE_PKGS="python3"

REDHAT_7_PKGS="python3"
REDHAT_8_PKGS="python3"

SOLARIS_PKGS="python3"

UBUNTU_18_PKGS="python3"
UBUNTU_20_PKGS="python3"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
}

get_python3_packages() {
    packages=

    case "$ID" in
	(centos)
	    case "$VERSION_ID" in
		(7)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8)
		    packages=$REDHAT_8_PKGS
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
		    packages=$DEBIAN_10_PKGS
		    ;;
	    esac
	    ;;
	(fedora)
	    packages=$FEDORA_PKGS
	    ;;
	(opensuse-*)
	    packages=$OPENSUSE_PKGS
	    ;;
	(rhel|ol)
	    case "$VERSION_ID" in
		(7.*)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8.*)
		    packages=$REDHAT_8_PKGS
		    ;;
	    esac
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    packages=$UBUNTU_18_PKGS
		    ;;
		(20.04)
		    packages=$UBUNTU_20_PKGS
		    ;;
		(20.10)
		    packages=$UBUNTU_20_PKGS
		    ;;
	    esac
	    ;;
	(freebsd)
	    packages=$FREEBSD_PKGS
	    ;;
	(macos)
	    packages=$MACOS_HOMEBREW_PKGS
	    ;;
    esac

    if [ -n "${packages-}" ]; then
	printf '%s\n' $packages
    fi
}

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_python3_packages
