#!/bin/sh -eu

# get-installed-mysql-package: get installed database package name
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_installed_mysql_package() {
    create_tmpfile
    get-installed-packages >$tmpfile
    grep-mysql-package $mode-core <$tmpfile || \
	grep-mysql-package $mode <$tmpfile || \
	grep-mysql-package <$tmpfile || \
	true
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

parse_arguments() {
    mode=$1

    case "$mode" in
	(client)
	    true
	    ;;
	(server)
	    true
	    ;;
	(*)
	    abort "%s: Invalid argument -- %s\n" "$0" "$1"
	    ;;
    esac
}

usage_error() {
    printf "$@" >&2
    exit 2
}

if [ $# -lt 1 ]; then
    usage_error "%s: Not enough arguments\n" "$0"
elif [ $# -gt 1 ]; then
    usage_error "%s: Too many arguments\n" "$0"
fi

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
parse_arguments "$@"
get_installed_mysql_package
