#!/bin/bash -eu

# get-package-filenames: print filenames associated with package
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function abort() {
    echo $1 >&2
    exit 1
}

distro_name=$(get-distro-name)
platform_name=$(get-platform-name)

case "$platform_name" in
    (Linux)
	case "$distro_name" in
	    (Debian|Ubuntu)
		dpkg --listfiles "$1"
		;;
	    (openSUSE)
		rpm --query --list "$1"
		;;
	    (*)
		abort "$distro_name: distro not supported"
		;;
	esac
	;;
    (SunOS)
	case "$distro_name" in
	    (illumos)
		for filename in $(pkg search -H -o search.match "basename:$1"); do
		    echo "/$filename"
		done
		;;
	esac
	;;
    (*)
	abort "$platform_name: platform not supported"
	;;
esac
