#!/bin/sh -eu

# get-emacs-build-deps: get list of Emacs build dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CATEGORIES="development image-library toolkit-library utility-library"

ILLUMOS_PKGS="developer/build/autoconf developer/build/automake \
developer/build/gnu-make developer/build/libtool developer/build/pkg-config \
developer/illumos-gcc image/library/librsvg library/desktop/cairo
library/gnutls library/ncurses library/zlib system/header"

UBUNTU_PKGS="libdbus-1-dev libgif-dev libgnutls28-dev libgpm-dev libjpeg-dev \
liblcms2-dev libm17n-dev libncurses5-dev libotf-dev librsvg2-dev libtiff5-dev \
libwebkit2gtk-4.0-dev libxml2-dev libxpm-dev"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_emacs_build_deps() {
    get_packages_in $CATEGORIES | sort -u
}

get_packages_in() {
    for category; do
	"$script_dir/get-$category-packages"
    done
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)

get_emacs_build_deps
