#!/bin/sh -eu

# get-toolkit-library-packages: get list of toolkit library packages
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="libgtk-3-dev libice-dev libsm-dev libx11-dev libxaw7-dev \
libxext-dev libxi-dev libxmu-dev libxpm-dev libxrandr-dev \
libxt-dev libxtst-dev"

FEDORA_PKGS="gtk3-devel libICE-devel libSM-devel libX11-devel libXaw-devel \
libXext-devel libXi-devel libXmu-devel libXpm-devel libXrandr-devel \
libXt-devel libXtst-devel"

OPENSUSE_PKGS="gtk3-devel libICE-devel libSM-devel libX11-devel libXaw-devel \
libXext-devel libXi-devel libXmu-devel libXpm-devel libXrandr-devel \
libXt-devel libXtst-devel"

REDHAT_7_PKGS="gtk3-devel libICE-devel libSM-devel libX11-devel libXaw-devel \
libXext-devel libXi-devel libXmu-devel libXpm-devel libXrandr-devel \
libXt-devel libXtst-devel"

REDHAT_8_PKGS="gtk3-devel libICE-devel libSM-devel libX11-devel libXaw-devel \
libXext-devel libXi-devel libXmu-devel libXpm-devel libXrandr-devel \
libXt-devel libXtst-devel"

SOLARIS_PKGS="x11/library/libice x11/library/libsm x11/library/libx11 \
x11/library/libxext x11/library/libxi x11/library/libxmu x11/library/libxpm \
x11/library/libxrandr x11/library/libxt x11/library/libxtst \
x11/library/toolkit/libxaw7 x11/library/toolkit/libxt"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}


get_emacs_build_deps() {
    packages=

    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
		packages=$DEBIAN_PKGS
		;;
	    (fedora)
		packages=$FEDORA_PKGS
		;;
	    (opensuse)
		packages=$OPENSUSE_PKGS
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (7|7.[78])
			packages=$REDHAT_7_PKGS
			;;
		    (8|8.[01])
			packages=$REDHAT_8_PKGS
			;;
		esac
		;;
	    (solaris)
		packages=$SOLARIS_PKGS
		;;
	esac

	if [ -n "${packages-}" ]; then
	    break
	fi
    done

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)

get_emacs_build_deps
