#!/usr/bin/env python3

# get-odbc-driver-info: print installed ODBC driver details
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import configparser
import json
import os
import re

DRIVER_MSSQL = re.compile(r'libmsodbcsql-\d+\.\d+\.so\.\d+\.\d+')
DRIVER_MYSQL = re.compile(r'libmyodbc\d+[aw]\.so')
DRIVER_POSTGRES = re.compile(r'psqlodbc[aw]\.so')

ODBC_DIALECTS = {
    DRIVER_MSSQL: 'mysql',
    DRIVER_MYSQL: 'mysql',
    DRIVER_POSTGRES: 'postgres',
}

ODBC_DRIVERS = '/etc/odbcinst.ini'


def enumerate_drivers() -> list:
    inifile = configparser.ConfigParser()
    inifile.read(ODBC_DRIVERS)
    drivers = []

    for section in inifile.sections():
        driver = inifile[section]
        dialect = get_dialect(driver)
        items = {k: driver[k] for k in driver}
        row = [dialect, section, items]
        drivers.append(tuple(row))

    return sorted(drivers)


def get_dialect(driver: dict) -> str:
    dialect = 'unknown'
    library = os.path.basename(driver['driver'])

    for pattern in ODBC_DIALECTS:
        if pattern.fullmatch(library):
            dialect = ODBC_DIALECTS[pattern]

    return dialect


def main():
    print(json.dumps(enumerate_drivers(), indent=4, sort_keys=True))


if __name__ == '__main__':
    main()
