#!/bin/bash -eu

# get-distro-name: print short name of Linux/illumos distribution
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

case "$(get-platform-name)" in
    (Linux)
	if [ -x /usr/bin/lsb_release ]; then
	    /usr/bin/lsb_release -is
	elif [ -r /etc/os-release ]; then
	    (source /etc/os-release && echo $ID)
	else
	    for os in centos fedora redhat; do
		if [ -e /etc/$os-release ]; then
		    awk '{print $1}' /etc/$os-release
		    exit 0
		fi
	    done
	fi
	;;
    (SunOS)
	kernel=$(uname -o)
	echo ${kernel%-*}
	;;
esac
