#!/bin/sh -eu

# get-docker-group: get group id associated with Docker
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DOCKER_GROUP=docker

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_docker_group() {
    origin=$(get_docker_origin "$@")

    if [ -n "$origin" ]; then
	case "$origin" in
	    (docker.com)
		printf "%s\n" "$DOCKER_GROUP"
		;;
	    (native)
		printf "%s\n" "$DOCKER_GROUP"
		;;
	    (podman)
		:
		;;
	esac
    fi
}

get_docker_origin() {
    for package; do
	case $package in
	    (docker-ce|docker-ce-cli)
		origin=docker.com
		;;
	    (docker|docker.io)
		origin=native
		;;
	    (podman-docker)
		origin=podman
		;;
	esac

	if [ -n "${origin-}" ]; then
	    printf "%s\n" "$origin"
	    return
	fi
    done
}

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

eval $("${script_prefix}get-os-release" -x)
get_docker_group "$@"
