#!/bin/sh -eu

# get-pyenv-dependencies: get list of pyenv dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_PKGS="gdbm libffi openssl readline zlib"

DEBIAN_PKGS="bash curl libbz2-dev libffi-dev libreadline-dev libsqlite3-dev \
libssl1.0-dev make %s-dev %s-setuptools %s-wheel zlib1g-dev"

FEDORA_PKGS="bash bzip2-devel curl gcc libffi-devel make ncurses-devel \
openssl-devel %s-devel %s-pip readline-devel sqlite-devel zlib-devel"

FREEBSD_PKGS="bash bzip2 curl gcc gmake libffi ncurses readline sqlite3"

OPENSUSE_PKGS="bash curl gcc libbz2-devel libffi-devel libopenssl-devel \
make %s-devel %s-setuptools %s-wheel readline-devel sqlite3-devel"

REDHAT_PKGS="bash bzip2-devel curl gcc libffi-devel make ncurses-devel \
%s-devel %s-setuptools readline-devel sqlite-devel"

SUNOS_PKGS="bash gcc libffi make ncurses readline sqlite-3"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_path() {
    assert [ -d "$1" ]
    command=$(which realpath)

    if [ -n "$command" ]; then
	$command "$1"
    elif expr "$1" : '/.*' >/dev/null; then
	printf "%s\n" "$1"
    else
	printf "%s\n" "$PWD/${1#./}"
    fi
}

script_dir=$(get_path "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

case "$kernel_name" in
    (Linux)
	case "$ID" in
	    (debian|ubuntu)
	    	packages=$DEBIAN_PKGS
	    	;;
	    (opensuse-*)
	    	packages=$OPENSUSE_PKGS
	    	;;
	    (fedora)
	    	packages=$FEDORA_PKGS
	    	;;
	    (redhat|centos)
		packages=$REDHAT_PKGS
		;;
	esac
	;;
    (Darwin)
	packages=$DARWIN_PKGS
	;;
    (FreeBSD)
	packages=$FREEBSD_PKGS
	;;
    (SunOS)
	packages=$SUNOS_PKGS
	;;
esac

data=$("$script_dir/get-python-package")
package_name=$(printf "%s" "$data" | awk '{print $1}')
package_modifier=$(printf "%s" "$data" | awk '{print $2}')

for package in ${packages-}; do
    case $package in
	(*%s*)
	    printf "$package\n" $package_modifier
	    ;;
	(*)
	    printf "%s\n" $package
	    ;;
    esac
done
