#!/bin/bash -eu

# get-release-name: print name of Linux distribution release
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

files="/etc/os-release /usr/lib/os-release /etc/{centos,fedora,redhat}-release"

case "$(get-platform-name)" in
    (Linux)
	for file in $files; do
	    if [ -r $file ]; then
		case $file in
		    (/etc/os-release|/usr/lib/os-release)
			(source $file && echo $VERSION_ID)
			exit 0
			;;
		    (/etc/*-release)
			awk '{print $4}' $file
			exit 0
			;;
		esac
	    fi
	done

	if [ -x /usr/bin/lsb_release ]; then
	    /usr/bin/lsb_release -rs
	fi
	;;
    (SunOS)
	os_version=$(uname -v)
	echo ${os_version#*-}
	;;
    (CYGWIN_NT-*)
	uname -r
	;;
esac
