#!/bin/sh -eu

# get-lilith-os-packages: get list of Lilith OS build packages
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_10_PKGS="binutils-i686-gnu gcc-i686-linux-gnu qemu"

OPENSUSE_PKGS="cross-i386-binutils cross-i386-gcc9 qemu"

UBUNTU_18_PKGS="binutils-i686-gnu gcc-i686-linux-gnu qemu"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_lilith_os_packages() {
    packages=

    case "$ID" in
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
		    packages=$DEBIAN_10_PKGS
		    ;;
	    esac
	    ;;
	(opensuse-*)
	    packages=$OPENSUSE_PKGS
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    packages=$UBUNTU_18_PKGS
		    ;;
	    esac
	    ;;
    esac

    if [ -n "${packages-}" ]; then
	printf "%s\n" $packages
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath || true)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_lilith_os_packages
