#!/bin/sh -eu

# get-mysql-common-packages: get MySQL database common package names
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_PKG=""

DEBIAN_10_PKG=""
DEBIAN_PKGS=""

FEDORA_PKG=""
FEDORA_PKGS=""

FREEBSD_PKG=""
FREEBSD_PKGS=""

ILLUMOS_PKG=""
ILLUMOS_PKGS=""

NETBSD_PKG=""
NETBSD_PKGS=""

OPENSUSE_PKG=""
OPENSUSE_PKGS=""

REDHAT_PKG=""

SOLARIS_PKG=""

UBUNTU_18_04_PKG=""
UBUNTU_19_10_PKG=""
UBUNTU_PKGS=""

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_mysql_common_packages() {
    package=$(get-installed-mysql-package client)

    case "$package" in
	(*-client-core-*)
	    package=$(printf "%s\n" $package | sed -e 's/-core-/-/')
	    ;;
    esac

    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian)
		    case "$VERSION_ID" in
			(10)
			    packages="${package:-$DEBIAN_10_PKG} $DEBIAN_PKGS"
			    ;;
		    esac
		    ;;
		(ubuntu|neon)
		    case "$VERSION_ID" in
			(18.04)
			    packages="${package:-$UBUNTU_18_04_PKG} $UBUNTU_PKGS"
			    ;;
			(19.10)
			    packages="${package:-$UBUNTU_19_10_PKG} $UBUNTU_PKGS"
			    ;;
		    esac
		    ;;
		(linuxmint)
		    case "$VERSION_ID" in
			(19.2)
			    packages="${package:-$UBUNTU_18_04_PKG} $UBUNTU_PKGS"
			    ;;
		    esac
		    ;;
		(kali)
		    case "$VERSION_ID" in
			(2019.3)
			    packages="${package:-$DEBIAN_10_PKG} $DEBIAN_PKGS"
			    ;;
		    esac
		    ;;
		(opensuse-*)
		    packages="${package:-$OPENSUSE_PKG} $OPENSUSE_PKGS"
		    ;;
		(fedora)
		    packages="${package:-$FEDORA_PKG} $FEDORA_PKGS"
		    ;;
		(rhel|ol|centos)
		    packages="${package:-$REDHAT_PKG}"
		    ;;
	    esac
	    ;;
	(Darwin)
	    packages="${package:-$DARWIN_PKG}"
	    ;;
	(FreeBSD)
	    packages="${package:-$FREEBSD_PKG} $FREEBSD_PKGS"
	    ;;
	(NetBSD)
	    packages="${package:-$NETBSD_PKG} $NETBSD_PKGS"
	    ;;
	(SunOS)
	    case "$ID" in
		(illumos)
		    packages="${package:-$ILLUMOS_PKG} $ILLUMOS_PKGS"
		    ;;
		(solaris)
		    packages="${package:-$SOLARIS_PKG}"
		    ;;
	    esac
	    ;;
    esac

    get-python-packages ${packages-}
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_mysql_common_packages
