#!/bin/sh -eu

# get-git-credential-binary: print filename of git-credential-libsecret source
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

distro_name=$(get-distro-name)
platform_name=$(get-platform-name)

case "$platform_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
		get-package-filenames git | grep git-credential-libsecret.c
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (*)
	abort "%s: Platform not supported\n" "$platform_name"
	;;
esac
