#!/bin/sh -eu

# get-postgresql-odbc-packages: get PostgreSQL ODBC package names
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_10_PKGS="odbc-postgresql"

FEDORA_PKGS="postgresql-odbc"

REDHAT_7_PKGS="postgresql-odbc"
REDHAT_8_PKGS="postgresql-odbc"

UBUNTU_18_PKGS="odbc-postgresql"
UBUNTU_19_PKGS="odbc-postgresql"
UBUNTU_20_PKGS="odbc-postgresql"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_postgresql_odbc_packages() {
    packages=

    case "$ID" in
	(amzn)
	    case "$VERSION_ID" in
		(2)
		    packages=$REDHAT_7_PKGS
		    ;;
	    esac
	    ;;
	(centos)
	    case "$VERSION_ID" in
		(7)
		    packages=$REDHAT_7_PKGS
		    ;;
		(8)
		    packages=$REDHAT_8_PKGS
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
		    packages=$DEBIAN_10_PKGS
		    ;;
	    esac
	    ;;
	(fedora)
	    case "$VERSION_ID" in
		(32)
		    packages=$FEDORA_PKGS
		    ;;
	    esac
	    ;;
	(rhel|ol)
	    case "$VERSION_ID" in
		(8.*)
		    packages=$REDHAT_8_PKGS
		    ;;
	    esac
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    packages=$UBUNTU_18_PKGS
		    ;;
		(19.10)
		    packages=$UBUNTU_19_PKGS
		    ;;
		(20.04)
		    packages=$UBUNTU_20_PKGS
		    ;;
	    esac
	    ;;
    esac

    format-python-packages ${packages-}
}

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
get_postgresql_odbc_packages
