#!/bin/sh -eu

# get-package-uninstall-options: get package uninstallation options
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

add_option_confirm() {
    if [ "${CONFIRM_PACKAGE_INSTALL:-false}" = false ]; then
        add_options -y
    fi
}

add_options() {
    assert [ $# -ge 1 ]
    options="${options:+$options }$@"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_package_uninstall_options() {
    options=

    for id in $ID $ID_LIKE; do
        case "$id" in
            (amzn)
                add_option_confirm
                break
                ;;
            (centos)
                add_option_confirm

                if [ "$VERSION_ID" -ge 8 ]; then
                    add_options --nobest
                else
                    add_options --skip-broken
                fi

                break
                ;;
            (debian)
                add_option_confirm
                break
                ;;
            (fedora)
                add_option_confirm
                break
                ;;
            (opensuse)
                break
                ;;
            (rhel|ol)
                add_option_confirm

                if [ "$VERSION_ID" -ge 8 ]; then
                    add_options --nobest
                else
                    add_options --skip-broken
                fi

                break
                ;;
            (freebsd)
                add_option_confirm
                break
                ;;
            (solaris)
                add_options --accept
                break
                ;;
        esac
    done

    if [ $# -gt 0 ]; then
        add_options "$@"
    fi

    if [ -n "${options-}" ]; then
        printf '%s\n' "$options"
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath || true)

    if [ -n "$realpath" ]; then
        $realpath "$@"
    else
        for file; do
            if expr "$file" : '/.*' >/dev/null; then
                printf '%s\n' "$file"
            else
                printf '%s\n' "$PWD/${file#./}"
            fi
        done
    fi
)

case "$0" in
    (*/*)
        script_dir=$(get_realpath "$(dirname "$0")")
        ;;
    (*)
        script_dir=
        ;;
esac

script_prefix=${script_dir:+$script_dir/}

eval $("${script_prefix}get-os-release" -x)
get_package_uninstall_options "$@"
