#!/bin/sh -eu

# Copyright (C) 2022  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

MAXDEPTH=1
ROOTDIRS="$HOME/Documents/git $HOME/git"

get_root_dir() (
    for dir in $ROOTDIRS; do
	if cd "$dir" 2>/dev/null; then
	    printf '%s\n' "$dir"
	    break
	fi
    done
)

git_pull_dir() (
    cd "$1"
    git pull origin $(awk '$1 == "ref:" {print $2}' .git/HEAD)

    if [ -x install-scripts ]; then
	./install-scripts
    fi
)

git_pull_recursive() {
    rootdir=$(get_root_dir)
    dirs=$(find $rootdir -maxdepth $MAXDEPTH -type d)

    for dir in $dirs; do
	if [ -e "$dir/.git/HEAD" ]; then
	    git_pull_dir "$dir"
	fi
    done
}

git_pull_recursive
