#!/bin/sh -eu

# install-python-development-tools: install Python 3 development tools
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKG=python3-defaults

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

configure_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
		package=$DEBIAN_PKG
		break
		;;
	esac
    done
}

install_python_development_tools() {
    validate_platform
    configure_platform
    preinstall_python_development_tools

    packages=$("$script_dir/get-python-devel-packages")
    pattern=$("$script_dir/get-devel-pattern")

    if [ -n "$packages" ]; then
	"$script_dir/install-packages" ${pattern:+-p "$pattern" }$packages
    fi

    if [ -n "${package:-}" ]; then
	"$script_dir/install-build-deps" "$@" $package
    fi
}

preinstall_python_development_tools() {
    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(rhel|ol|centos)
                    case "$VERSION_ID" in
			(7|7.[78])
			    "$script_dir/install-epel"
                            ;;
		    esac
	    	    ;;
	    esac
	    ;;
    esac

}

validate_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (debian)
                case "$VERSION_ID" in
		    (10)
			return
                        ;;
                esac
	    	;;
	    (fedora)
		return
	    	;;
	    (opensuse)
		return
	    	;;
	    (rhel|ol|centos)
                case "$VERSION_ID" in
		    (7|7.*)
			return
                        ;;
		    (8|8.*)
			return
			;;
                esac
		;;
	    (ubuntu)
                case "$VERSION_ID" in
		    (18.*)
			return
                        ;;
		    (19.*)
			return
			;;
                esac
	    	;;
	    (darwin)
		return
    		;;
	    (freebsd)
		return
    		;;
	    (netbsd)
		return
		;;
	    (solaris)
		return
    		;;
	esac
    done

    abort_not_supported "Operating system"
}

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)

install_python_development_tools "$@"
