#!/bin/sh -eu

# install-docker-compose: install Docker Compose from GitHub
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BASE_URL=https://github.com/docker/compose/releases

COMPOSE_FILENAME=docker-compose
COMPOSE_VERSION=1.28.2

create_tmpfile() {
    dir=$(dirname "$1")
    file=$(basename "$1")

    if [ ! -d "$dir" ]; then
	mkdir ${target_mode:+-m $target_mode }-p "$dir"
    fi

    tmpfile=$(mktemp -p "$dir" -t "$file.XXXXXXXXXX.tmp")
    trap "/bin/rm -f \"$tmpfile\"" EXIT INT QUIT TERM
}

download_file() {
    options=$(get_curl_options)
    url=$(get_url)

    if [ "$silent" = false ]; then
	printf 'Downloading from %s\n' $(dirname "$url")
	printf '%s\n' ''
    fi

    if ! curl $options "$url" -o "$1" || [ ! -s "$1" ]; then
	print_newline
	return 1
    fi
}

get_compose_file() {
    printf '%s/%s\n' "$prefix" bin/$COMPOSE_FILENAME
}

get_file_version_number() {
    get_version_number $(get_file_version_string "$@")
}

get_file_version_string() {
    get_version_string "$1" | cut -d, -f 1
}

get_version_number() {
    printf '%s\n' "$*" | awk '{print $3}'
}

get_version_string() {
    if [ -n "$1" -a -x "$1" ]; then
	"$1" --version || true
    fi
}

get_curl_options() {
    printf '%s\n' -L -f

    if [ "$bar" = true ]; then
	printf '%s\n' -#
    elif [ "$silent" = true ]; then
	printf '%s\n' -s
    fi
}

get_filetype() {
    system=$(uname -s)

    case "$system" in
	(CYGWIN_NT-*)
	    printf '%s\n' exe
	    ;;
	(MINGW64_NT-*)
	    printf '%s\n' exe
	    ;;
    esac
}

get_hardware() {
    uname -m
}

get_platform() {
    system=$(uname -s)

    case "$system" in
	(CYGWIN_NT-*)
	    printf '%s\n' Windows
	    ;;
	(MINGW64_NT-*)
	    printf '%s\n' Windows
	    ;;
	(*)
	    printf '%s\n' "$system"
	    ;;
    esac
}

get_target_mode() {
    case "$1" in
	($HOME/*)
	    printf '%s\n' a+rx
	    ;;
	(*)
	    printf '%s\n' u=rwx,go=rx
	    ;;
    esac
}

get_url() {
    filetype=$(get_filetype)
    hardware=$(get_hardware)
    platform=$(get_platform)
    file="$COMPOSE_FILENAME-$platform-$hardware${filetype:+.$filetype}"
    dir="download/$version"
    url="$BASE_URL/$dir/$file"
    printf '%s\n' "$url"
}

install_docker_compose() {
    if [ -z "$prefix" ]; then
	if [ "$(id -u)" -eq 0 ]; then
	    prefix=/usr/local
	else
	    prefix=$HOME/.local
	fi
    fi

    target_file=$(get_compose_file)
    target_mode=$(get_target_mode "$target_file")
    version_before=$(get_file_version_number "$target_file")
    version_after=

    if [ $force = true -o "$version_before" != "$version" ]; then
	create_tmpfile "$target_file"

	if download_file "$tmpfile"; then
	    if install_file "$tmpfile" "$target_file"; then
		version_after=$(get_file_version_number "$target_file")
		print_newline
	    fi
	fi
    fi

    print_summary
}

install_file() {
    if [ "$silent" = false ]; then
	printf '%s\n' ''
	printf 'Installing %s %s as %s\n' \
	       "Docker Compose" \
	       "$version" \
	       "$2"
    fi

    if [ -n "$target_mode" ]; then
	chmod $target_mode "$1"
    fi

    /bin/mv -f "$1" "$2"
}

is_valid_version() {
    if expr "$1" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$'; then
	true
    elif expr "$1" : '[0-9][0-9]*\.[0-9][0-9]*$'; then
	true
    else
	false
    fi >/dev/null
}

parse_arguments() {
    bar=false
    force=false
    prefix=
    silent=false
    version=$COMPOSE_VERSION

    while getopts bfp:sv:h opt; do
	case $opt in
	    (b)
		bar=true
		;;
	    (f)
		force=true
		;;
	    (p)
		parse_prefix $OPTARG
		;;
	    (s)
		silent=true
		;;
	    (v)
		parse_version $OPTARG
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error "%s: Too many arguments\n" "$script"
    fi
}

parse_prefix() {
    case "$1" in
	($HOME/.local|/opt/*|/usr/local)
	    prefix=$1
	    ;;
	(*)
	    usage_error "%s: %s: Invalid prefix\n" "$script" "$1"
	    ;;
    esac

    if [ ! -d "$prefix/bin" ]; then
	usage_error "%s: %s: Invalid prefix\n" "$script" "$1"
    elif [ ! -w "$prefix/bin" ]; then
	usage_error "%s: %s: Invalid prefix\n" "$script" "$1"
    fi
}

parse_version() {
    if is_valid_version "$1"; then
	version="$1"
    else
	usage_error "%s: %s: Invalid version\n" "$script" "$1"
    fi
}

print_newline() {
    if [ "$silent" = false ]; then
	printf '%s\n' ''
    fi
}

print_summary() {
    if [ "$silent" = true ]; then
	return 0
    fi

    printf '%s\n' 'Installation Summary:'
    printf '%s\n' ''

    which -a $COMPOSE_FILENAME | while read file; do
	version_string=$(get_file_version_string "$file")

	if [ "$file" = "$target_file" ]; then
	    if [ -z "$version_before" ]; then
		status=installed
	    elif [ "$version_after" = "$version_before" ]; then
		status=reinstalled
	    elif [ -n "$version_after" ]; then
		status="upgraded from $version_before"
	    else
		status=unchanged
	    fi
	else
	    status=unchanged
	fi

	printf '%s: %s\n' \
	       "$version_string" \
	       "$file${status:+ ($status)}"

    done | sed "s/$COMPOSE_FILENAME version/Docker Compose/"
}

usage() {
    cat <<EOF >&2
Usage: $script [-b] [-f] [-p PREFIX] [-s] [-v VERSION]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script=$(basename "$0")
parse_arguments "$@"
install_docker_compose
