#!/bin/sh -eu

# install-sbcl: install SBCL
# Copyright (C) 2022  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

SBCL_ARCHIVE_DIR="$HOME/Downloads/SBCL"
SBCL_ARCHIVE_SUFFIX=.tar.bz2

SBCL_OPT_PREFIX=/opt/%s
SBCL_PROJECT_NAME=sbcl
SBCL_PROJECT_VERSION=2.2.8

abort() {
    printf "$@" >&2
    exit 1
}

abort() {
    printf "$@" >&2
    exit 1
}

abort_invalid_prefix() {
    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
}

abort_invalid_version() {
    usage_error '%s: invalid version -- %s\n' "$script" "$*"
}

abort_not_supported() {
    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

configure_paths() {
    archive_dirname="$SBCL_ARCHIVE_DIR"
    archive_basename=$(get_archive_basename)
    tmp_dirname=/var/tmp/${archive_basename%-binary}
    archive_filename=$archive_basename$SBCL_ARCHIVE_SUFFIX
    archive_pathname="$archive_dirname/$archive_filename"
}

extract_sbcl() {
    umask 0022

    if [ "$force" = true ]; then
	/bin/rm -rf "$tmp_dirname"
    fi

    extract_archive "$archive_pathname" "$tmp_dirname"
}

get_archive_basename() (
    arch=$(get_machine_architecture)
    os=$(get_operating_system)
    printf '%s-%s-%s-%s-%s\n' \
	   $SBCL_PROJECT_NAME \
	   $version \
	   $arch \
	   $os \
	   binary
)

get_machine_architecture() (
    arch=$(uname -m)

    case "$arch" in
	(aarch64)
	    printf '%s\n' arm64
	    ;;
	(*)
	    printf '%s\n' $arch
	    ;;
    esac
)

get_operating_system() {
    uname -s | tr '[:upper:]' '[:lower:]'
}

get_prefix() {
    printf "$prefix" "$SBCL_PROJECT_NAME-$version"
}

install_sbcl() {
    if [ "$ID" != windows -a "$(id -u)" -gt 0 ]; then
	return 0
    fi

    umask 0022
    cd "$tmp_dirname"
    install_prefix=$(get_prefix)
    INSTALL_ROOT="$install_prefix" sh install.sh
    install_project_link "$install_prefix"
}

parse_arguments() {
    force=false
    prefix=$SBCL_OPT_PREFIX
    version=$SBCL_PROJECT_VERSION

    while getopts fp:v:h opt; do
	case $opt in
	    (f)
		force=true
		;;
	    (p)
		case $OPTARG in
		    ($HOME/.local|$LOCAL_PREFIX|$SBCL_OPT_PREFIX)
			prefix=$OPTARG
			;;
		    (*)
			abort_invalid_prefix $OPTARG
			;;
		esac
		;;
	    (v)
		case $OPTARG in
		    ([12].[1-9]|[12].[1-9].[1-9]|[12].[1-9].[1-9][0-9])
			version=$OPTARG
			;;
		    (*)
			abort_invalid_version $OPTARG
			;;
		esac
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error '%s: Too many arguments\n' "$script"
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script [-f] [-p PREFIX] [-v VERSION]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

validate_platform() {
    case "$ID" in
	(centos)
	    case "$VERSION_ID" in
		(7)
		    return
		    ;;
		(8)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(debian|raspbian)
	    return
	    ;;
	(fedora)
	    return
	    ;;
	(opensuse-*)
	    return
	    ;;
	(rhel|ol|archlinux)
	    case "$VERSION_ID" in
		(7.*)
		    return
		    ;;
		(8.*)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(rocky)
	    case "$VERSION_ID" in
		(7.*)
		    return
		    ;;
		(8.*)
		    return
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(ubuntu)
	    return
	    ;;
	(freebsd)
	    return
	    ;;
	(illumos)
	    return
	    ;;
	(macos)
	    return
	    ;;
	(netbsd)
	    return
	    ;;
	(solaris)
	    return
	    ;;
	(windows)
	    return
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"
. "${script_prefix}config-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
validate_platform
parse_arguments "$@"
configure_paths

if [ "$(id -u)" -eq 0 ]; then
    run_unpriv /bin/sh -c "$0 $*"
else
    extract_sbcl
fi

install_sbcl
