#!/bin/sh

# install-docker: install Oracle VirtualBox Guest Additions dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PACKAGE_DIR=VBox_GAs_6.0.12

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_virtualbox_guest() {
    validate_platform
    preinstall_virtualbox_guest

    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(ol|centos)
		    if [ ! -d /run/media/mgmorey/$PACKAGE_DIR ]; then
			mount -r /dev/cdrom /run/media/mgmorey/$PACKAGE_DIR
		    fi

		    if [ -d /run/media/mgmorey/$PACKAGE_DIR ]; then
			cd /run/media/mgmorey/$PACKAGE_DIR
			sh VBoxLinuxAdditions.run
		    fi
		    ;;
	    esac
	    ;;
    esac
}

preinstall_virtualbox_guest() {
    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian|ubuntu|neon|linuxmint|kali)
		    apt-get install build-essential dkms linux-headers-$(uname -r)
		    ;;
		(ol|centos)
		    "$script_dir/install-epel"

		    case "$VERSION_ID" in
			(7|7.*|8|8.*)
			    if ! yum update 'kernel*'; then
				exit $?
			    fi

			    printf "Please reboot the machine with the new kernel (if updated).\n"

			    if ! yum install make gcc perl dkms bzip2 kernel-headers kernel-devel; then
				exit $?
			    fi

			    export KERN_DIR=/usr/src/kernels/`uname -r`
			    ;;
		    esac
		    ;;
	    esac
	    ;;
    esac
}

validate_platform() {
    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian|ubuntu|neon|linuxmint|kali)
		    :
		    ;;
		(ol|centos)
		    case "$VERSION_ID" in
			(7|7.*)
			    :
			    ;;
			(8|8.*)
			    :
			    ;;
			(*)
			    abort_not_supported Release
			    ;;
		    esac
		    ;;
		(*)
		    abort_not_supported Distro
		    ;;
	    esac
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

if [ $# -gt 0 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

install_virtualbox_guest
