#!/bin/sh -eu

# install-python-development-tools: install Python 3 development tools
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKG=python3-defaults

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_python_development_tools() {
    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian|ubuntu|linuxmint|neon|kali)
		    :
	    	    ;;
		(opensuse-*)
		    :
	    	    ;;
		(fedora)
		    :
	    	    ;;
		(ol|centos)
                    case "$VERSION_ID" in
			(7|7.*)
			    :
                            ;;
			(*)
			    :
			    ;;
                    esac
		    ;;
		(*)
		    abort_not_supported Distro
		    ;;
	    esac
	    ;;
	(Darwin|FreeBSD|SunOS|CYGWIN_NT-*)
	    :
    	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac

    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian|ubuntu|linuxmint|neon|kali)
		    package=$DEBIAN_PKG
		    ;;
		(opensuse-*|fedora|ol|centos)
		    :
		    ;;
		(*)
		    abort_not_supported Distro
		    ;;
	    esac
	    ;;
	(FreeBSD|SunOS|CYGWIN_NT-*)
	    :
    	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac

    packages=$("$script_dir/get-python-devel-packages")
    pattern=$("$script_dir/get-devel-pattern")

    if [ -n "$packages" ]; then
	"$script_dir/install-packages" ${pattern:+-p "$pattern" }$packages
    fi

    if [ -n "${package:-}" ]; then
	"$script_dir/install-build-deps" "$@" $package
    fi
}

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

install_python_development_tools "$@"
