#!/bin/sh -eux

# For AMD64 / x86_64
[ $(uname -m) = x86_64 ] && curl -Lo ~/.local/bin/kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
# For ARM64
[ $(uname -m) = aarch64 ] && curl -Lo ~/.local/bin/kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-arm64
chmod +x ~/.local/bin/kind
