#!/bin/sh -eu

# install-kubernetes: install Kubernetes container orchestration system
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BASEURL=https://storage.googleapis.com/minikube/releases/latest
TMPDIR=${TMPDIR:-/tmp}

get_installer() {
    case "$ID" in
	(debian|ubuntu)
	    printf '%s\n' "dpkg -i"
	    ;;
	(*)
	    printf '%s\n' "rpm -Uvh"
	    ;;
    esac
}

get_package() {
    case "$ID" in
	(debian|ubuntu)
	    printf '%s\n' minikube_latest_amd64.deb
	    ;;
	(*)
	    printf '%s\n' minikube-latest.x86_64.rpm
	    ;;
    esac
}

install_minikube() {
    installer=$(get_installer)
    package=$(get_package)
    file="$TMPDIR/$package"
    url="$BASEURL/$package"
    tmpfiles="$file"
    trap clean_up EXIT INT QUIT TERM
    cd $TMPDIR
    curl -LO $url
    $installer $file
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
install_minikube
