#!/bin/sh -eu

# install-docker-credential-secretservice: install Docker binary
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BASENAME=docker-credential-secretservice
BASE_URL=https://github.com/docker/docker-credential-helpers/releases/download
PREFIX=/usr/local
VERSION=v0.6.3

PATHNAME=$PREFIX/bin/$BASENAME
SUFFIX=$VERSION-amd64.tar.gz

cd /tmp
wget $BASE_URL/$VERSION/$BASENAME-$SUFFIX
tar -xf $BASENAME-$SUFFIX
chmod +x $BASENAME
chown root:root $BASENAME

if [ -f $PATHNAME -a ! -f $PATHNAME~ ]; then
    /bin/mv -f $PATHNAME $PATHNAME~
fi

/bin/mv -f $BASENAME $PATHNAME
