#!/bin/sh

# install-presto-server: install Presto server packages
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BASE_URL=https://repo1.maven.org/maven2/io/prestosql/presto-server-rpm
PRESTO_VERSION=336

PKG_NAME=presto-server-rpm
RPM_FILE=presto-server-rpm-$PRESTO_VERSION.rpm

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_platform() {
    case "$ID" in
	(rhel|ol|centos)
	    install_rpm_files
	    ;;
	(opensuse-leap)
	    install_rpm_files
	    ;;
    esac
}

install_presto_server() (
    validate_platform
    install-packages java-11-openjdk-devel python2
    install_platform

)

install_python_symlink() {
    if ! which python >/dev/null 2>&1; then
    	for version in 3 2; do
    	    if which python$version >/dev/null 2>&1; then
    		ln -s "$(which python$version)" /usr/bin/python
    		break
    	    fi
    	done
    fi
}

install_rpm_files() {
    if ! rpm -q $PKG_NAME >/dev/null 2>&1; then
	cd /tmp
	curl --output $RPM_FILE $BASE_URL/$PRESTO_VERSION/$RPM_FILE
	rpm -ihv $RPM_FILE
    fi
}

validate_platform() {
    case "$ID" in
	(centos)
	    case "$VERSION_ID" in
		(8)
		    true
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(opensuse-leap)
	    case "$VERSION_ID" in
		(15.*)
		    true
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(rhel|ol)
	    case "$VERSION_ID" in
		(8.*)
		    true
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

if [ $# -gt 0 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

script_basename="$(basename "$0")"
script_dirname="$(get_realpath "$(dirname "$0")")"

. "$script_dirname/common-functions.sh"

set_user_profile "$script_dirname"
eval $(get-os-release -x)
install_presto_server
