#!/bin/sh -eu

# install-root-scripts: install root scripts to /usr/local/bin
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

INSTALL_EXEC="install -m u=rwx,go=rx"
INSTALL_NOEXEC="install -m u=rw,go=r"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_script_files() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]
    find "$1" \
	 -maxdepth 1 \
	 '(' \
	 -name get-python-interpreter \
	 -o \
	 -name run-python \
	 ')' \
	 -type f
}

install_script_files() {
    script_files="$(get_script_files "$source_dir")"

    if [ -n "$script_files" ]; then
	$INSTALL_EXEC $script_files "$target_dir"
    fi
}

install_scripts() {
    source_dir="$(get_realpath "$(pwd)")"

    if [ ! -e "$target_dir" ]; then
	mkdir -p "$target_dir"
    fi

    install_script_files
}

parse_arguments() {
    if [ $# -gt 0 ]; then
	target_dir="$1"
    else
	target_dir=/usr/local/bin
    fi
}

if [ $# -gt 1 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

parse_arguments "$@"
install_scripts
