#!/bin/sh -eu

# install-pipenv: install Python Environment Manager
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CATEGORIES="python-pip"

PIP_OPTIONS="--upgrade --user"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_packages() {
    for category in $CATEGORIES; do
	"${script_prefix}get-$category-packages"
    done | sort -u
}

get_pip_options() {
    options=$PIP_OPTIONS

    case $(pip_version) in
	(9.0.3)
	    true
	    ;;
	(*)
	    options="${options:+$options }--no-warn-script-location"
	    ;;
    esac

    options=${options:+$options }$PIP_OPTIONS
    printf "%s\n" $options
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_dependencies() {
    case "$ID" in
	(windows)
	    return 0
	    ;;
    esac

    "${script_prefix}install-packages" $(get_packages)
}

install_pipenv() {
    pip_install $(get_pip_options) pip pipenv
}

pip_install() {
    "${script_prefix}run-python" -m pip install "$@"
}

pip_version() {
    "${script_prefix}run-python" -m pip --version | awk '{print $2}'
}

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

eval $("${script_prefix}get-os-release" -x)

if [ "$(id -u)" -eq 0 ]; then
    install_dependencies
    run_unpriv "$0"
else
    install_dependencies
    install_pipenv
fi
