#!/bin/sh -eu

# install-pgdg: install PostgreSQL repository
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PGDG_INSTALLER=/usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
PGDG_LISTFILE=/etc/apt/sources.list.d/pgdg.list
PGDG_PACKAGE=pgdg-redhat-repo

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_pgdg() {
    validate_platform
    preinstall_platform
    install_platform
}

install_platform() {
    case "$ID" in
	(debian|ubuntu)
	    if [ ! -f $PGDG_LISTFILE ]; then
		sh $PGDG_INSTALLER
	    fi
	    ;;
	(rhel|ol)
	    if ! rpm -q $PGDG_PACKAGE >/dev/null 2>&1; then
		abort "%s: %s: No such package installed\n" "$0" $PGDG_PACKAGE
	    fi
	    ;;
    esac
}

preinstall_platform() {
    case "$ID" in
	(debian|ubuntu)
	    install-packages postgresql-common
	    ;;
    esac
}

validate_platform() {
    case "$ID" in
	(debian)
	    case "$VERSION_ID" in
		(10)
		    return
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
	(rhel|ol)
	    case "$VERSION_ID" in
		(8.*)
		    return
		    ;;
		(*)
		    return
		    ;;
	    esac
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    return
		    ;;
		(19.10)
		    return
		    ;;
		(*)
		    break
		    ;;
	    esac
	    ;;
    esac

    abort_not_supported "Operating system"
}

if [ $# -gt 0 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
install_pgdg
