#!/bin/sh -eu

# install-macos-sdk-headers: install macOS SDK headers for macOS 10.14
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_PKG_BASENAME=macOS_SDK_headers_for_macOS_%s.pkg
DARWIN_PKG_DIRNAME=/Library/Developer/CommandLineTools/Packages/

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_darwin_pkg_pathname() {
    printf "%s/$DARWIN_PKG_BASENAME\n" $DARWIN_PKG_DIRNAME $VERSION_ID
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath || true)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_macos_sdk_headers() {
    case "$kernel_name" in
	(Darwin)
	    case "$VERSION_ID" in
		(10.14.*|10.15.*)
		    darwin_pkg_pathname=$(get_darwin_pkg_pathname)

		    if [ -e $darwin_pkg_pathname ]; then
			installer -pkg $darwin_pkg_pathname -target /
		    fi
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

usage_error() {
    printf "$@" >&2
    exit 2
}

if [ $# -gt 0 ]; then
    usage_error "%s: Too many arguments\n" "$0"
fi

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

eval $("${script_prefix}get-os-release" -x)
install_macos_sdk_headers
