#!/bin/sh -eu

# install-python3-build-extras: install Python3 build extras
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# DEBIAN_PKGS=""

FEDORA_PKGS="bzip2-devel gdbm-devel lzma-sdk-devel mcpanel-devel \
ncurses-devel pyliblzma readline-devel sqlite-devel tk-devel"

abort() {
    printf "$@" >&2
    exit 1
}

distro_name=$(get-os-distro-name)
kernel_name=$(get-os-kernel-name)

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    # (debian|ubuntu)
	    # 	packages=$DEBIAN_PKGS
	    # 	;;
	    (fedora)
	    	packages=$FEDORA_PKGS
	    	;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac

install-packages "$@" $packages
