#!/bin/sh -eu

# install-adobe-source-code-pro: install Adobe Source Code Pro fonts
# Copyright (C) 2022  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FONT_CACHE_DIR=$HOME/.fonts/adobe-fonts/source-code-pro
FONT_URL=https://github.com/adobe-fonts/source-code-pro.git

mkdir -p $FONT_CACHE_DIR
git clone $FONT_URL $FONT_CACHE_DIR
fc-cache -f -v $FONT_CACHE_DIR
