#!/bin/sh -eu

# install-emacs-build-dependencies: install GNU Emacs build dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKG=emacs25
DEBIAN_PKGS="libgif-dev libjpeg-dev libncurses5-dev libtiff5-dev libxpm-dev"

OPENSUSE_PKGS="gcc"

REDHAT_PKG=emacs

abort() {
    printf "$@" >&2
    exit 1
}

distro_name=$(get-os-distro-name)
kernel_name=$(get-os-kernel-name)

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
		package=$DEBIAN_PKG
		packages=$DEBIAN_PKGS
		;;
	    (redhat|centos)
		package=$REDHAT_PKG
		;;
	    (opensuse-*)
		packages="$OPENSUSE_PKGS"
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (FreeBSD|SunOS|NT)
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac

if [ -z "${package:-}" ] || ! install-build-dependencies "$@" $package; then
    if [ -n "${packages:-}" ]; then
	install-packages "$@" $packages
    fi
fi
