#!/bin/sh -eu

# install-docker-ce: install Docker Community Edition
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="apt-transport-https ca-certificates curl gnupg2 \
software-properties-common"
DOCKER_BASE_URL=https://download.docker.com

distro_name=$(get-os-distro-name)
kernel_name=$(get-os-kernel-name)

case "$kernel_name" in
    (Linux)
	docker_url="$DOCKER_BASE_URL/linux/$distro_name"

	case "$distro_name" in
	    (debian|ubuntu)
		codename="$(lsb_release -cs)"
		repository="deb [arch=amd64] $docker_url $codename stable"
		sudo apt-get remove "$@" docker docker.io || true
		sudo apt-get install "$@" $DEBIAN_PKGS
		curl -fsSL $docker_url/gpg | sudo apt-key add -
		sudo add-apt-repository "$repository"
		sudo apt-get update
		sudo apt-get install "$@" docker-ce
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac
