#!/bin/sh

BOOTSTRAP_TAR="bootstrap-trunk-x86_64-20170127.tar.gz"
BOOTSTRAP_SHA="eb0d6911489579ca893f67f8a528ecd02137d43a"

cd /var/tmp

# Download the bootstrap kit to the current directory.
curl -O https://pkgsrc.joyent.com/packages/Linux/el7/bootstrap/${BOOTSTRAP_TAR}

# Verify the SHA1 checksum.
echo "${BOOTSTRAP_SHA}  ${BOOTSTRAP_TAR}" >check-shasum
sha1sum -c check-shasum

# Verify PGP signature.  This step is optional, and requires gpg.
if [ -n "$(which gpg 2>/dev/null)" ]; then
    curl -O https://pkgsrc.joyent.com/packages/Linux/el7/bootstrap/${BOOTSTRAP_TAR}.asc
    curl -sS https://pkgsrc.joyent.com/pgp/56AAACAF.asc | gpg --import
    gpg --verify ${BOOTSTRAP_TAR}{.asc,}
fi

# Install bootstrap kit to /usr/pkg
sudo tar -zxpf ${BOOTSTRAP_TAR} -C /
