#!/bin/sh -eu

# install-root-scripts: install root scripts to /usr/local/bin
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FILEMODE=u=rwx,go=rx

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_install_command() {
    case "$ID" in
	(illumos)
	    which install
	    ;;
	(*)
	    which install
	    ;;
    esac
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

get_script_files() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]
    find "$1" \
	 -maxdepth 1 \
	 '(' \
	 -name get-python-interpreter \
	 -o \
	 -name run-python \
	 ')' \
	 -type f
}

install_files() {
    if [ -z "$files" ]; then
	return
    fi

    install=$(get_install_command)

    case "$ID" in
	(illumos)
	    case "$install" in
		(/usr/gnu/bin/install)
		    $install -m $FILEMODE $files "$target_dir"
		    ;;
		(/usr/sbin/install)
		    for file in $files; do
			$install -f "$target_dir" -m $FILEMODE -s $file
		    done
		    ;;
	    esac
	    ;;
	(*)
	    $install -m $FILEMODE $files "$target_dir"
	    ;;
    esac
}

install_script_files() {
    files=$(get_script_files "$source_dir")
    install_files
}

install_root_scripts() {
    source_dir=$(get_realpath "$(pwd)")

    case "$(basename "$source_dir")" in
	(scripts|*-scripts)
	    true
	    ;;
	(*)
	    abort "%s: Please change to the source directory and try again\n" "$0"
	    ;;
    esac

    mkdir -p "$target_dir"
    install_script_files
}

parse_arguments() {
    if [ $# -gt 1 ]; then
	abort "%s: Too many arguments\n" "$0"
    fi

    if [ $# -gt 0 ]; then
	target_dir="$1"
    else
	target_dir=/usr/local/bin
    fi
}

case "$0" in
    (*/*)
	script_dir=$(dirname "$0")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$(get_realpath "$script_dir")/}

eval $("${script_prefix}get-os-release" -x)
parse_arguments "$@"
install_root_scripts
