#!/bin/sh -eu

# install-python-development-utilities: install Python 3 development utilities
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKG=python3-defaults

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

configure_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (rhel|ol)
		is_pattern_supported=true

		case "$VERSION_ID" in
		    (7.*)
			install-epel
			;;
		    (8.*)
			install-epel
			;;
		esac

		break
		;;
	esac
    done
}

install_python_development_utilities() {
    validate_platform
    configure_platform
    packages="$(get-python-utility-packages)"
    install-packages $packages
}

validate_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (amzn)
                case "$VERSION_ID" in
		    (2)
			return
                        ;;
                esac
		;;
	    (debian)
                case "$VERSION_ID" in
		    (10)
			return
                        ;;
                esac
	    	;;
	    (fedora)
		return
	    	;;
	    (opensuse)
		return
	    	;;
	    (rhel|ol|centos)
                case "$VERSION_ID" in
		    (7|7.*)
			return
                        ;;
		    (8|8.*)
			return
			;;
                esac
		;;
	    (ubuntu)
                case "$VERSION_ID" in
		    (18.*)
			return
                        ;;
		    (19.*)
			return
			;;
                esac
	    	;;
	    (freebsd)
		return
    		;;
	    (macos)
		return
    		;;
	    (netbsd)
		return
		;;
	    (solaris)
		return
    		;;
	esac
    done

    abort_not_supported "Operating system"
}

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
install_python_development_utilities "$@"
