#!/bin/sh -eu

# Copyright (C) 2025  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CERT_DIR=$HOME/certificates
PROFILE=$HOME/.bash_profile

install_user_ca_certificates() {
    files=$(find "$@" -type f -name '*.pem')

    if [ -n "$files" ]; then
	if [ -e $PROFILE -a -z "$SSL_CERT_DIR" ]; then
	    SSL_CERT_DIR=$CERT_DIR
	    print_command >>$PROFILE
	fi

	if [ ! -e "$SSL_CERT_DIR" ]; then
	    mkdir -p "$SSL_CERT_DIR"
	fi

	/bin/cp $files $SSL_CERT_DIR
    fi
}

print_command() {
    printf 'export %s=%s\n' SSL_CERT_DIR $SSL_CERT_DIR
}

install_user_ca_certificates "${@:-$HOME/Downloads}"
