#!/bin/sh -eu

# install-build-dependencies: install build dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_BUILD_TOOLS="build-essential"

REDHAT_BUILD_TOOLS="gcc make yum-utils"

abort() {
    printf "$@" >&2
    exit 1
}

distro_name=$(get-os-distro-name)
kernel_name=$(get-os-kernel-name)
package_manager=$(get-package-manager)

if [ -z "$package_manager" ]; then
    abort "%s\n" "No package manager"
fi

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
		install-packages $DEBIAN_BUILD_TOOLS
		sudo $package_manager build-dep "$@"
		;;
	    (fedora|redhat|centos)
		install-packages $REDHAT_BUILD_TOOLS
		sudo ${package_manager}-builddep "$@"
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac
