#!/bin/sh -eu

# install-xrdp: install and enable the xrdp remote desktop server

yum install -y epel-release
yum install -y xrdp
systemctl enable xrdp
systemctl start xrdp
firewall-cmd --add-port=3389/tcp --permanent
firewall-cmd --reload
