#!/bin/sh -eu

# install-docker-compose: install Docker Compose program script
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

COMPOSE_VERSION=1.28.2

BASE_URL=https://github.com/docker/compose/releases
TARGET_FILE=/usr/local/bin/docker-compose

get_compose_version() {
    get_version_string docker-compose | cut -d, -f 1
}

get_version_number() {
    printf '%s\n' "$*" | awk '{print $3}'
}

get_version_string() {
    if which "$1" >/dev/null 2>&1; then
	"$1" --version
    fi
}

get_compose_url() {
    file="docker-compose-$(uname -s)-$(uname -m)"
    dir="download/$COMPOSE_VERSION"
    url="$BASE_URL/$dir/$file"
    printf '%s\n' "$url"
}

install_binary_file() {
    tmpfile=$(mktemp -p $(dirname "$1") -t "$(basename "$1").XXXXXXXXXX.tmp")
    trap "/bin/rm -f $tmpfile" EXIT INT QUIT TERM
    curl -L $(get_compose_url) -o "$tmpfile"
    /bin/mv "$tmpfile" "$1"
    chmod a+x "$1"
}

install_docker_compose() {
    current=$(get_compose_version || true)

    if [ $(get_version_number $current) = "$COMPOSE_VERSION" ]; then
	exit 0
    fi

    prior=$current
    install_binary_file $TARGET_FILE
    current=$(get_compose_version || true)
    printf '%s\n' ''

    if [ -z "$prior" ]; then
	printf 'Installed %s\n' "$current"
    elif [ "$current" != "$prior" ]; then
	printf 'Upgraded from %s\n' "$prior"
	printf 'Upgraded to %s\n' "$current"
    fi
}

install_docker_compose
