#!/bin/sh -eu

# install-emacs-build-extras: install GNU Emacs build extras
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKGS="libgnutls28-dev libgpm-dev libwebkit2gtk-4.0-dev"

OPENSUSE_PKGS="gconf2-devel giflib-devel gpm-devel gtk3-devel \
ImageMagick-devel libacl-devel libgnutls-devel libjpeg62-devel \
libICE-devel liblcms2-devel libpng16-devel libSM-devel \
libtiff-devel libX11-devel libXaw3d-devel libXext-devel libXi-devel \
libXmu-devel libXpm-devel libXrandr-devel libXt-devel libXTrap-devel \
libXtst-devel libXv-devel libxml2-devel make m17n-lib-devel \
ncurses5-devel zlib-devel webkit2gtk3-devel"

abort() {
    printf "$@" >&2
    exit 1
}

distro_name=$(get-os-distro-name)
kernel_name=$(get-os-kernel-name)

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
		packages="$DEBIAN_PKGS"
		;;
	    (opensuse-*)
		packages="$OPENSUSE_PKGS"
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac

install-packages "$@" $packages
