#!/bin/sh

# pyenv-install-on-macos: install Python via pyenv on macOS
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_SDK_BASENAME=MacOSX%s.sdk
DARWIN_SDK_DIRNAME=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_darwin_sdkroot() {
    printf "%s/$DARWIN_SDK_BASENAME\n" $DARWIN_SDK_DIRNAME $VERSION_ID
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_pyenv_on_macos() {
    case "$kernel_name" in
	(Darwin)
	    case "$VERSION_ID" in
		(10.14.*|10.15.*)
		    darwin_sdkroot=$(get_darwin_sdkroot)

		    if [ -e $darwin_sdkroot ]; then
			export MACOSX_DEPLOYMENT_TARGET=$VERSION_ID
			export SDKROOT=$darwin_sdkroot
		    fi

		    brew install pyenv
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

usage_error() {
    printf "$@" >&2
    exit 2
}

if [ $# -gt 0 ]; then
    usage_error "%s: Too many arguments\n" "$0"
fi

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)
install_pyenv_on_macos "$@"
