#!/bin/sh -eu

# install-startup-files: install startup files in home directory
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

LEGACY_FILES=".bash_profile .emacs"
STARTUP_FILES=".bashrc .editorconfig .profile"
STARTUP_FILES_URL=https://mgmorey@github.com/mgmorey/startup-files.git

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_diff_command() {
    diff=

    for id in $ID $ID_LIKE; do
	case "$id" in
	    (solaris)
		diff=/usr/gnu/bin/diff
		;;
	esac

	if [ -n "${diff:-}" ]; then
	    break
	fi
    done

    printf "%s\n" "${diff:-diff}"
}

get_install_command() {
    install=

    for id in $ID $ID_LIKE; do
	case "$id" in
	    (solaris)
		install=/usr/gnu/bin/install
		;;
	esac

	if [ -n "${install:-}" ]; then
	    break
	fi
    done

    printf "%s\n" "${install:-install}"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_startup_files() {
    if [ ! -h $0 ]; then
	abort "Please change from source directory before running this script\n"
    fi

    if ! "$script_dir/install-git"; then
	abort "%s: Unable to install git\n" "$0"
    fi

    cd

    if [ ! -d Documents/git ]; then
	mkdir -p Documents

	if [ -d git ]; then
	    /bin/mv git Documents/git
	else
	    mkdir Documents/git
	fi
    fi

    if [ ! -e git ]; then
	/bin/ln -s Documents/git git
    fi

    cd git

    if [ ! -d startup-files ]; then
	git clone $STARTUP_FILES_URL
    fi

    cd

    for file in $STARTUP_FILES; do
	if is_to_be_installed $file; then
	    printf "Installing %s\n" $file
	    $install -bm 644 $HOME/git/startup-files/$file $file
	fi
    done

    if [ ! -d .emacs.d ]; then
	printf "Creating %s\n" .emacs.d
	mkdir .emacs.d
    fi

    if [ -d .emacs.d ]; then
	cd .emacs.d

	if [ ! -e init.el ]; then
	    printf "Installing %s\n" .emacs.d/init.el
	    $install -bm 644 $HOME/git/startup-files/.emacs.d/init.el init.el
	fi
    fi

    cd

    for file in $LEGACY_FILES; do
	if [ -e $file ]; then
	    printf "Renaming %s to %s\n" $file $file.orig
	    /bin/mv -f $file $file.orig
	fi
    done

    printf "Please log out and back in again to activate the new environment.\n"
}

is_to_be_installed() {
    if [ ! -r $1 ]; then
	return 0;
    elif [ ! -r /etc/skel/$1 ]; then
	return 1
    else
	$diff -qs /etc/skel/$1 $1
    fi
}

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -x)

diff="$(get_diff_command)"
install="$(get_install_command)"
install_startup_files
