#!/bin/sh -eu

# install-macos-sdk-headers: install macOS SDK headers for macOS 10.14
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DARWIN_PKG_DIR=/Library/Developer/CommandLineTools/Packages/
DARWIN_PKG_NAME=macOS_SDK_headers_for_macOS_10.14.pkg

DEBIAN_PKG=python3-defaults

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

install_macos_sdk_headers() {
    case "$kernel_name" in
	(Darwin)
	    case "$VERSION_ID" in
		(10.14.*)
		    installer -pkg $DARWIN_PKG_DIR/$DARWIN_PKG_NAME -target /
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

if [ $# -gt 0 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

eval $(get-os-release -x)

install_macos_sdk_headers
