#!/bin/sh -eu

# install-emacs-build-extras: install GNU Emacs build extras
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_emacs_build_extras() {
    case "$kernel_name" in
	(Linux|GNU)
	    case "$ID" in
		(debian|raspbian|ubuntu|linuxmint|neon)
		    :
		    ;;
		(opensuse-*)
		    :
		    ;;
		(fedora|ol|centos)
		    :
	    	    ;;
		(*)
		    abort_not_supported Distro
		    ;;
	    esac
	    ;;
	(FreeBSD|SunOS|CYGWIN_NT-*)
	    :
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac

    install_cmd=$("$script_dir/get-pattern-install-command")
    install_opts=$("$script_dir/get-package-install-options")
    installer=$("$script_dir/get-package-manager")
    packages=$("$script_dir/get-emacs-build-extras")
    pattern=$("$script_dir/get-devel-pattern")

    if [ -n "$pattern" ]; then
	$installer $install_cmd $install_opts "$pattern"
    fi

    if [ -n "$packages" ]; then
	$installer install $install_opts $packages
    fi
}

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

install_emacs_build_extras "$@"
