#!/bin/sh -eu

# install-homebrew: install the HomeBrew package manager brew
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BASE_URL=https://raw.githubusercontent.com
HOMEBREW_URL=$BASE_URL/Homebrew/install/master/install
LINUXBREW_URL=$BASE_URL/Homebrew/install/master/install.sh

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

configure_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (macos)
		PKG_DIR=/Library/Developer/CommandLineTools/Packages/
		PKG_NAME=macOS_SDK_headers_for_macOS_10.14.pkg
		break
		;;
	esac
    done
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_homebrew() {
    validate_platform
    configure_platform
    brew=$(which brew 2>/dev/null || true)

    if [ -n "$brew" ]; then
	if [ "$kernel_name" = Linux -a "$brew" = /usr/bin/brew ]; then
	    if [ -x $HOME/.linuxbrew ]; then
		return
	    elif [ -x /home/linuxbrew ]; then
		return
	    fi
	else
	    return
	fi
    fi

    preinstall_homebrew

    for id in $ID $ID_LIKE; do
	case "$id" in
	    (centos)
		case "$VERSION_ID" in
		    (7)
			install_linuxbrew
			break
			;;
		    (8)
			install_linuxbrew
			break
			;;
		    (*)
			break
			;;
		esac
		;;
	    (debian)
		case "$VERSION_ID" in
		    (10)
			install_linuxbrew
			break
			;;
		    (*)
			break
			;;
		esac
		;;
	    (fedora)
		install_linuxbrew
		break
		;;
	    (opensuse)
		install_linuxbrew
		break
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (7.*)
			install_linuxbrew
			break
			;;
		    (8.*)
			install_linuxbrew
			break
			;;
		    (*)
			break
			;;
		esac
		;;
	    (ubuntu)
		case "$VERSION_ID" in
		    (18.04)
			run_unpriv brew
			break
			;;
		    (20.04)
			run_unpriv brew
			break
			;;
		    (20.10)
			run_unpriv brew
			break
			;;
		    (*)
			break
			;;
		esac
		;;
	    (macos)
		run_unpriv /usr/bin/ruby -e "$(curl -fsSL $HOMEBREW_URL)"
		break
		;;
	esac
    done
}

install_linuxbrew() {
    run_unpriv /bin/sh -c "$(curl -fsSL $LINUXBREW_URL)"
}

preinstall_homebrew() {
    case "$kernel_name" in
	(Linux)
	    packages="$(get-homebrew-packages)"
	    pattern="$(get-development-pattern)"
	    install-packages ${pattern:+-p "$pattern" }$packages
	    ;;
	(Darwin)
	    installer -allowUntrusted -pkg $PKG_DIR/$PKG_NAME -target /
	    ;;
    esac
}

usage_error() {
    printf "$@" >&2
    exit 2
}

validate_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (centos)
		case "$VERSION_ID" in
		    (8)
			return
			;;
		    (*)
			break
			;;
		esac
		;;
	    (debian)
		case "$VERSION_ID" in
		    (10)
			return
			;;
		    (*)
			break
			;;
		esac
		;;
	    (fedora)
		return
		;;
	    (opensuse)
		return
		;;
	    (rhel|ol)
		case "$VERSION_ID" in
		    (8.*)
			return
			;;
		    (*)
			break
			;;
		esac
		;;
	    (ubuntu)
		case "$VERSION_ID" in
		    (18.04)
			return
			;;
		    (20.04)
			return
			;;
		    (20.10)
			return
			;;
		    (*)
			break
			;;
		esac
		;;
	    (macos)
		return
		;;
	esac
    done

    abort_not_supported "Operating system"
}

if [ $# -gt 0 ]; then
    usage_error "%s: Too many arguments\n" "$0"
fi

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
install_homebrew
