#!/bin/sh -eu

# install-emacs-build-deps: install GNU Emacs build dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKG=emacs
DEBIAN_PKGS="libgif-dev libjpeg-dev libncurses5-dev libtiff5-dev libxpm-dev"

OPENSUSE_PKGS="gcc"

REDHAT_PKG=emacs

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

case "$kernel_name" in
    (Linux|GNU)
	case "$ID" in
	    (debian|raspbian|ubuntu|linuxmint|neon|kali)
		package=$DEBIAN_PKG
		packages=$DEBIAN_PKGS
		;;
	    (opensuse-*)
		packages=$OPENSUSE_PKGS
		;;
	    (fedora|ol|centos)
		package=$REDHAT_PKG
		;;
	    (*)
		abort_not_supported Distro
		;;
	esac
	;;
    (FreeBSD|SunOS|CYGWIN_NT-*)
	:
	;;
    (*)
	abort_not_supported "Operating system"
	;;
esac

if [ -z "${package:-}" ] || ! "$script_dir/install-build-deps" "$@" $package; then
    if [ -n "${packages:-}" ]; then
	"$script_dir/install-packages" "$@" $packages
    fi
fi
