#!/bin/sh -eu

# install-oracle-odbc: install Oracle ODBC packages
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CLIENT_VERSION=19.6

FORMAT='%s-%s.0.0.0-1.%s.rpm\n'

INSTANTCLIENT_BASIC=oracle-instantclient${CLIENT_VERSION}-basic
INSTANTCLIENT_ODBC=oracle-instantclient${CLIENT_VERSION}-odbc

ODBC_DRIVER_DESC='Oracle ODBC driver for Oracle 19'
ODBC_DRIVER_FILE=/etc/odbcinst.ini
ODBC_DRIVER_NAME='Oracle 19 ODBC driver'
ODBC_DRIVER_LIB=/usr/lib/oracle/$CLIENT_VERSION/client64/lib/libsqora.so.19.1

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_package_files() {
    for package in $INSTANTCLIENT_BASIC $INSTANTCLIENT_ODBC; do
	if ! rpm -q $package >/dev/null 2>&1; then
	    printf "$FORMAT" $package $CLIENT_VERSION "$(uname -m)"
	fi
    done
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_oracle_odbc() {
    validate_platform
    install-packages $(get-odbc-development-packages)
    install_platform
}

install_platform() {
    package_files=$(get_package_files)

    if [ -n "$package_files" ]; then
	rpm -iv $package_files
    fi

    if ! grep "\[$ODBC_DRIVER_NAME\]" $ODBC_DRIVER_FILE >/dev/null 2>&1; then
	cat <<EOF >$ODBC_DRIVER_FILE
[$ODBC_DRIVER_NAME]
Description=$ODBC_DRIVER_DESC
Driver=$ODBC_DRIVER_LIB
Setup=
FileUsage=
CPTimeout=
CPReuse=

EOF
    fi
}

validate_platform() {
    case "$ID" in
	(rhel|ol)
	    case "$VERSION_ID" in
		(8.1)
		    return
		    ;;
	    esac
	    ;;
    esac

    abort_not_supported "Operating system"
}

if [ $# -gt 0 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

script_dir=$(get_realpath "$(dirname "$0")")

. "$script_dir/common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
install_oracle_odbc
