#!/bin/sh -eu

# install-python-build-dependencies: install python build dependencies
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEBIAN_PKG="python"
DEBIAN_PKGS="build-essential libffi-dev libgdbm-dev libhashkit-dev \
libreadline-dev libsqlite3-dev libssl-dev python-dev readline-dev \
tk-dev uuid-dev"

REDHAT_PKG="python"
REDHAT_PKGS="gcc make gdbm-devel libffi-devel ncurses-devel \
openssl-devel python-dev readline-devel sqlite-devel \
tcl-devel tix-devel tk-devel uuid-dev yum-utils"

SUNOS_PKGS="build-essential gcc gcc-runtime gnutls"

abort() {
    printf "$@" >&2
    exit 1
}

distro_name=$(get-os-distro-name)
kernel_name=$(get-os-kernel-name)
package_manager=$(get-package-manager)

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
		package=$DEBIAN_PKG
		packages="$DEBIAN_PKGS"
		;;
	    (redhat|centos)
		package=$REDHAT_PKG
		packages="$REDHAT_PKGS"
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (SunOS)
	packages="$SUNOS_PKGS"
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac

if [ -z "${package:-}" ] || ! install-build-dependencies $package; then
    install-packages $packages
fi
