#!/bin/sh -eux

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_epel_8() {
    case "$kernel_name" in
	(Linux)
	    case "$ID" in
		(ol)
		    :
		    ;;
		(*)
		    abort_not_supported Distro
		    ;;
		esac
	    :
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac

    dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
}

if [ $# -gt 0 ]; then
    abort "%s: Too many arguments\n" "$0"
fi

script_dir=$(get_realpath "$(dirname "$0")")

eval $("$script_dir/get-os-release" -X)

install_epel_8
