#!/bin/sh -eu

# install-python3-build-extras: install Python3 build extras
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

realpath() {
    if [ -x /usr/bin/realpath ]; then
	/usr/bin/realpath "$@"
    else
	if expr "$1" : '/.*' >/dev/null; then
	    printf "%s\n" "$1"
	else
	    printf "%s\n" "$PWD/${1#./}"
	fi
    fi
}

script_dir=$(realpath $(dirname $0))
distro_name=$(sh -eu "$script_dir/get-os-distro-name")
kernel_name=$(sh -eu "$script_dir/get-os-kernel-name")
package_manager=$(sh -eu "$script_dir/get-package-manager")
package_install_options=$(sh -eu "$script_dir/get-package-install-options")
packages=$(sh -eu "$script_dir/get-python3-build-extras")

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
	    	;;
	    (fedora)
	    	;;
	    (opensuse-*)
	    	;;
	    (redhat|centos)
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (FreeBSD|SunOS|NT)
    	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac

if [ -n "$package_manager" ]; then
    if [ -n "$packages" ]; then
	$package_manager install $package_install_options $packages
    fi
fi
