#!/bin/sh -eu

# install-mssql-odbc: install Microsoft SQL Server ODBC packages
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BASE_URL=https://packages.microsoft.com
MSSQL_RELEASE=/etc/apt/sources.list.d/mssql-release.list

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_packages() {
    printf "%s\n" msodbcsql17 mssql-tools
    get-odbc-development-packages
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

install_mssql_odbc() {
    validate_platform
    preinstall_platform
    install-packages $(get_packages)
    postinstall_platform
}

postinstall_platform() {
    ln -sf /opt/mssql-tools/bin/* /usr/local/bin
}

preinstall_platform() {
    case "$ID" in
	(debian|ubuntu)
	    if [ ! -f $MSSQL_RELEASE ]; then
		curl $BASE_URL/keys/microsoft.asc | apt-key add -
		curl $BASE_URL/config/$ID/$VERSION_ID/prod.list >$MSSQL_RELEASE
		apt-get update
	    fi
	    ;;
    esac
}

usage_error() {
    printf "$@" >&2
    exit 2
}

validate_platform() {
    case "$ID" in
	(debian|raspbian)
	    case "$VERSION_ID" in
		(10)
		    true
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(ubuntu)
	    case "$VERSION_ID" in
		(18.04)
		    true
		    ;;
		(*)
		    abort_not_supported Release
		    ;;
	    esac
	    ;;
	(*)
	    abort_not_supported "Operating system"
	    ;;
    esac
}

if [ $# -gt 0 ]; then
    usage_error "%s: Too many arguments\n" "$0"
fi

export ACCEPT_EULA=Y

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

set_user_profile "$script_dir"
eval $(get-os-release -x)
install_mssql_odbc
