#!/bin/bash -eu

# make-git-credential-helper: make git credential helper binary
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function abort() {
    echo $1 >&2
    exit 1
}

distro_name=$(get-distro-name)
platform_name=$(get-platform-name)

case "$platform_name" in
    (Linux)
	case "$distro_name" in
	    (Debian|Ubuntu)
		sudo apt-get install -qq -y libglib2.0-dev libsecret-1-dev
		;;
	    (*)
		abort "$distro_name: Distro not supported"
		;;
	esac
	;;
    (*)
	abort "$platform_name: Platform not supported"
	;;
esac

helper_source=$(get-git-credential-source)

if [ -n "$helper_source" ]; then
    if [ -e "$helper_source" ]; then 
	if cd $(dirname $helper_source); then
	    sudo make $(basename ${helper_source%.c})
	fi
    else
	abort "$helper_source: No such credential helper source file"
    fi
else
    abort "No credential helper source"
fi
