#!/bin/sh -eu

# normalize-path: eliminate duplicate directories in PATH
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

get_realpath() (
    for file; do
	if expr "$file" : '/.*' >/dev/null; then
	    printf "%s\n" "$file"
	else
	    printf "%s\n" "$PWD/${file#./}"
	fi
    done
)

join_dirnames() {
    tr '\n' ':' | sed 's/:$/\n/'
}

normalize_path() {
    if [ -x /bin/realpath ]; then
	realpath="/bin/realpath -q"
    else
	realpath=get_realpath
    fi

    dirnames=$(printf '%s\n' "${1-$PATH}" | split_path | quote_lines)
    eval $realpath $dirnames | awk '!_[$0]++' | join_dirnames
}

quote_lines() {
    sed 's/^\(.*\)$/"\1"/'
}

split_path() {
    tr ':' '\n'
}

normalize_path "$@"
