#!/bin/sh -eu

# normalize-path: eliminate duplicate directories in PATH
# Copyright (C) 2021  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
}

clean_up() {
    eval rm -f ${tmpfiles-}
}

create_tmpfile() {
    trap clean_up EXIT INT QUIT TERM
    tmpfile=$(mktemp)
    assert [ -n "${tmpfile}" ]
    tmpfiles="${tmpfiles+$tmpfiles }'$tmpfile'"
}

get_realpath() (
    assert [ $# -ge 1 ]

    for file; do
	if expr "$file" : '/.*' >/dev/null; then
	    printf "%s\n" "$file"
	else
	    printf "%s\n" "$PWD/${file#./}"
	fi
    done
)

normalize_path() {
    if [ -x /bin/realpath ]; then
	realpath=/bin/realpath
    else
	realpath=get_realpath
    fi

    printf "%s\n" "${1-$PATH}" | tr ':' '\n' | while read dir; do
	if [ -d "$dir" ]; then
	    dir=$($realpath "$dir")

	    if ! grep -q '^'"$dir"'$' $tmpfile; then
		printf '%s\n' "$dir" >>$tmpfile
	    fi
	fi
    done

    tr '\n' ':' <$tmpfile | sed 's/:$//'
    printf '%s\n' ''
}

create_tmpfile
normalize_path "$@"
