#!/bin/sh -eu

# pip-install: install PyPI packages via PIP
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PYTHON=python3

get_options() {
    options=

    if [ "$id" -gt 0 ]; then
        options="${options:+$options }--user"
    fi

    printf '%s\n' $options
}

pip_install() {
    id="$(id -u)"
    options=$(get_options)
    pip_install="$PYTHON -m pip install ${options+$options }"

    if [ "$id" -gt 0 ]; then
        $pip_install --upgrade pip
    fi

    $pip_install "$@"
}

case "$0" in
    (*/*)
        script_dir=$(realpath "$(dirname "$0")")
        ;;
    (*)
        script_dir=
        ;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}tableau-config.sh"
. "${script_prefix}tableau-library.sh"

if [ $# -lt 1 ]; then
    usage_error "Not enough arguments"
fi

pip_install "$@"
