#!/bin/sh -eux

BASE_NAMES="subgid subuid"

GID_BEGIN=100000
GID_COUNT=65536

print_entry() {
    printf '%s:%s:%s\n' \
	   "$user_name" \
	   $GID_BEGIN \
	   $GID_COUNT
}

populate_sub_ids() {
    user_name=${SUDO_USER-$USER}

    for base_name in $BASE_NAMES; do
	file_name=/etc/$base_name

	if [ ! -s "$file_name" ]; then
	    print_entry >$file_name
	fi
    done

    podman system migrate
}

populate_sub_ids
