#!/bin/sh -eu

BASE_URL=artifactory.prod.tableautools.com:6555/dataservices

DATABASES="ibm-db2 mssql mysql oracle postgres presto sap-hana"

IBM_DB2_VERSIONS="11.5.4.0"
MSSQL_VERSIONS="2017 2019"
MYSQL_VERSIONS="5.6 5.7 8.0"
ORACLE_VERSIONS="12 18 19"
POSTGRES_VERSIONS="9.4 11 12"
PRESTO_VERSIONS="336"
SAP_HANA_VERSIONS="ee2"

TAG="$(date +%Y%m%d%H%M)"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

build_image() {
    $(get_command $method) $(get_build_subcommand $method $image)
}

create_builder() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]

    case $1 in
	(buildx)
	    builder=$(get_insecure_builder)

	    if [ "$builder" != insecure-builder ]; then
		docker buildx create \
		       --use \
		       --name insecure-builder \
		       --buildkitd-flags \
		       '--allow-insecure-entitlement security.insecure'
	    fi
	    ;;
    esac
}

get_build_subcommand() {
    assert [ $# -eq 2 ]
    assert [ -n "$1" ]
    assert [ -n "$2" ]

    case "$1" in
	(buildah)
	    printf '%s\n' bud --cap-add=all -t "$2" .
	    ;;
	(buildx)
	    printf '%s\n' buildx build \
		   --allow security.insecure \
		   --load -t "$2" .
	    ;;
	(docker)
	    printf '%s\n' build -t "$2" .
	    ;;
	(podman)
	    printf '%s\n' build -t "$2" .
	    ;;
    esac
}

get_command() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]

    case "$1" in
	(buildah)
	    printf '%s\n' buildah
	    ;;
	(buildx)
	    printf '%s\n' docker
	    ;;
	(docker)
	    printf '%s\n' docker
	    ;;
	(podman)
	    printf '%s\n' podman
	    ;;
    esac
}

get_insecure_builder() {
    docker buildx ls | awk 'NR > 1 && $1 == "insecure-builder" { print $1 }'
}

get_versions() {
    case $database in
	(ibm-db2)
	    versions_default=$IBM_DB2_VERSIONS
	    ;;
	(mssql)
	    versions_default=$MSSQL_VERSIONS
	    ;;
	(mysql)
	    versions_default=$MYSQL_VERSIONS
	    ;;
	(oracle)
	    versions_default=$ORACLE_VERSIONS
	    ;;
	(postgres)
	    versions_default=$POSTGRES_VERSIONS
	    ;;
	(presto)
	    versions_default=$PRESTO_VERSIONS
	    ;;
	(sap-hana)
	    versions_default=$SAP_HANA_VERSIONS
	    ;;
	(*)
	    abort '%s: %s: DBMS not recognized\n' "$0" "$database"
	    ;;
    esac

    printf '%s\n' "$versions_default"
}

parse_arguments() {
    databases=
    method=docker
    no_build=false
    only_build=false
    tag=
    versions=

    while getopts M:blnt:v:h opt; do
	case $opt in
	    (M)
		case "$OPTARG" in
		    (buildah)
			method="$OPTARG"
			;;
		    (buildx)
			if [ "${DOCKER_CLI_EXPERIMENTAL-}" = enabled ]; then
			    method="$OPTARG"
			fi
			;;
		    (docker)
			method="$OPTARG"
			;;
		    (podman)
			method="$OPTARG"
			;;
		esac
		;;
	    (b)
		no_build=false
		only_build=true
		;;
	    (l)
		tag=latest
		;;
	    (n)
		no_build=true
		only_build=false
		;;
	    (t)
		tag="$OPTARG"
		;;
	    (v)
		versions="$OPTARG"
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))
    databases="$@"
}

publish_docker_images() {
    for database; do
	for version in ${versions:-$(get_versions)}; do
	    publish_image $database $version
	done
    done
}

publish_image() (
    image=tableau-${1}-${2%.0}
    repo_image=$BASE_URL/$image:${tag:-$TAG}

    if [ -d docker-${1}/$2 ]; then
	cd docker-${1}/$2

	if [ "$no_build" = false ]; then
	    create_builder $method
	    build_image $method $image
	fi

	if [ "$only_build" = false ]; then
	    $(get_command $method) tag $image $repo_image
	    $(get_command $method) push $repo_image
	fi
    fi
)

usage_error() {
    printf "$@" >&2
    exit 2
}

parse_arguments "$@"
publish_docker_images ${databases:-$DATABASES}
