#!/bin/sh

# remove-from-path: remove directory name from PATH parameter
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ $# -gt 0 ]; then
    value="$(printf "%s\n" "$PATH" | sed -e 's|^'"$1"':||g;s|:'"$1"':|:|g;s|:'"$1"'$||g')"

    case ${SHELL##*/} in
	(bash|fish|ksh|ksh93|rbash|zsh)
	    printf "export %s=%s\n" PATH "$value"
	    ;;
	(csh|tcsh)
	    printf "setenv %s %s;\n" PATH "$value"
	    ;;
	(sh)
	    printf "%s=%s\n" PATH "$value"
	    printf "export %s\n" PATH
	    ;;
	(*)
	    abort "%s: %s: Shell not supported\n" "$0" "$SHELL"
	    ;;
    esac
fi
