#!/bin/sh

# renew-dhcp-lease: renew the DHCP lease

if which dhclient >/dev/null 2>&1; then
    dhclient -r
    dhclient
elif which systemctl >/dev/null 2>&1; then
    systemctl restart network.service
fi
