#!/bin/sh -eux

# reset-podman-containers: delete all rootless Podman container storage

uid=$(id -u)

/bin/rm -rf ~/.config/containers ~/.local/share/containers \
    /run/user/$uid/libpod /run/user/$uid/runc /run/user/$uid/vfs-*
