#!/bin/sh -eu

# run-python: run Python 3 script
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PYTHON_VERSIONS="3.8 3.7 3.6 3.5 3"

abort_python_missing() {
    printf 'No working Python 3 interpreter was found.\n' >&2
    printf 'The following commands were tried:\n' >&2
    printf 'python%s\n' $PYTHON_VERSIONS >&2
    exit 1
}

get_python_interpreter() (
    for version in $PYTHON_VERSIONS; do
	python=$(which python$version 2>/dev/null || true)

        if $python --version >/dev/null 2>&1; then
            printf '%s\n' "$python"
            break
        fi
    done
)

run_python() {
    python="$(get_python_interpreter)"

    if [ -n "$python" ]; then
        "$python" "$@"
    else
	abort_python_missing
    fi
}

run_python "$@"
