#!/bin/sh -eu

# set-publisher-sfe-on-openindiana: add publisher SFE on OpenIndiana
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

URL=http://pkg.openindiana.org/sfe

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_publisher_data() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]
    awk -v publisher=$1 'NR > 1 && $1 == publisher && $2 == "origin" {print $0}'
}

set_publisher_sfe() {
    data=$(pkg publisher | get_publisher_data sfe)

    if [ -z "$data" ]; then
	pkg set-publisher -p $URL
    fi
}

set_publisher_sfe
