#!/bin/bash -eu

# set-git-credential-helper: configure git credential helper
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function abort() {
    printf "$@" >&2
    exit 1
}

helper_binary="$(get-git-credential-binary)"

if [ -n "$helper_binary" ]; then
    if [ "$helper_binary" = cache -o -e "$helper_binary" ]; then
	git config --global credential.helper "$helper_binary"
    else
	abort "%s: No such credential helper\n" "$helper_binary"
    fi
else
    abort "No credential helper\n"
fi
