#!/bin/sh

# set-up-hercules: install and configure Hercules emulator
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Create hercules account and group
sudo useradd --system hercules

# Add hercules group to user's groups
sudo usermod -a -G hercules $USER

# Install hercules and related packages
sudo apt install hercules herculesstudio

# Override Debian package permissions for hercules
for f in /usr/bin/hercules /usr/bin/hercifc; do
    sudo dpkg-statoverride --update --add root hercules 4750 "$f"
done

# Set up udev rules for hercules
sudo sh <<EOF1
cat <<EOF2 >/etc/udev/rules.d/99-local.rules
KERNEL=="tun", ACTION=="add", GROUP="hercules", MODE="0660", OPTIONS+="static_node=net/tun"
EOF2
EOF1
