#!/bin/sh -eu

# set-up-tunnel: set up IP forwarding tunnel using iptables
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

NETWORK=10.10.0.0/23

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

realpath() {
    assert [ -d "$1" ]

    if [ -x /usr/bin/realpath ]; then
	/usr/bin/realpath "$1"
    else
	if expr "$1" : '/.*' >/dev/null; then
	    printf "%s\n" "$1"
	else
	    printf "%s\n" "$PWD/${1#./}"
	fi
    fi
}

script_dir=$(realpath "$(dirname "$0")")

eval $(sh -eu $script_dir/get-os-release -X)

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    (debian|ubuntu)
	    	;;
	    (*)
		abort "%s: Distro not supported\n" "$pretty_name"
		;;
	esac
	;;
    (*)
	abort "%s: Operating system not supported\n" "$pretty_name"
	;;
esac

iptables -t nat -A POSTROUTING -s $NETWORK -j MASQUERADE  
iptables -A FORWARD -s $NETWORK -j ACCEPT
iptables -A FORWARD -d $NETWORK -j ACCEPT
echo 1 | sh -c "cat >/proc/sys/net/ipv4/ip_forward"
echo 1 | sh -c "cat >/proc/sys/net/ipv4/conf/all/proxy_arp"
