#!/bin/sh -eu

# set-proxy-parameters: print shell commands to set proxy parameters
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

ALL_PROXY_FILE="$HOME/.proxy"
NO_PROXY_FILE="$HOME/.no-proxy"

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
}

configure_platform() {
    all_proxy=$(get_file_contents "$ALL_PROXY_FILE")
    no_proxy=$(get_file_contents "$NO_PROXY_FILE")
}

get_file_contents() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]

    if [ -r "$1" ]; then
	cat "$1"
    fi
}

parse_arguments() {
    no_export=false
    shell=$SHELL

    while getopts s:nh opt; do
	case $opt in
	    (n)
		no_export=true
		;;
	    (s)
		parse_shell "$OPTARG"
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error '%s: Too many arguments\n' "$script"
    fi
}

print_proxy_parameters() {
    while IFS='=' read var value; do
	print_parameter "$var" "$value"
    done
}

set_proxy_parameters() {
    configure_platform

    if [ -n "$all_proxy" ]; then
	"${script_prefix}generate-proxy-parameters" \
	    ${no_proxy:+-n $no_proxy} $all_proxy | \
	    print_proxy_parameters
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script: [-s SHELL]
       $script: -n
       $script: -h
EOF
}

script=$(basename "$0")

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}parameter-functions.sh"

parse_arguments "$@"
set_proxy_parameters
