#!/bin/sh -eu

# set-publisher-solarisstudio: add publisher SolarisStudio on Oracle Solaris
# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CERT=pkg.oracle.com.certificate.pem
KEY=pkg.oracle.com.key.pem
URL=https://pkg.oracle.com/solarisstudio/release

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_publisher_data() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]
    awk -v publisher=$1 'NR > 1 && $1 == publisher && $2 == "origin" {print $0}'
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

set_publisher_solarisstudio() {
    validate_platform
    data=$(pkg publisher | get_publisher_data solarisstudio)

    if [ -z "$data" ]; then
	pkg set-publisher -k $KEY -c $CERT -G "*" -g $URL solarisstudio
    fi
}

validate_platform() {
    for id in $ID $ID_LIKE; do
	case "$id" in
	    (illumos)
		abort_not_supported "Operating system"
    		;;
	    (solaris)
		return
    		;;
	esac
    done

    abort_not_supported "Operating system"
}

eval $(get-os-release -x)

set_publisher_solarisstudio
