#!/bin/sh -eu

# set-askpass: print Bash statements to set askpass helper binary
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

askpass_helper=$(get-askpass)

if [ $# -gt 0 ]; then
    commands="$@"
else
    commands="git ssh sudo"
fi

for command in $commands; do
    case "$command" in
	(git|ssh|sudo)
	    var=${command}_askpass
	    var=$(echo $var | to-upper)

	    case ${SHELL##*/} in
		(bash|fish|ksh|ksh93|rbash|zsh)
		    printf "export %s=%s\n" "$var" "$askpass_helper"
		    ;;
		(csh|tcsh)
		    printf "setenv %s %s;\n" "$var" "$askpass_helper"
		    ;;
		(sh)
		    printf "%s=%s\n" "$var" "$askpass_helper"
		    printf "export %s\n" "$var"
		    ;;
		(*)
		    abort "%s: Shell not supported\n" "$SHELL"
		    ;;
	    esac
	    ;;
	(*)
	    abort "%s: Not a valid command\n" "$command"
    esac
done
