#!/bin/sh -eu

# set-up-sap-hana: set up SAP HANA Docker container
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
    	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

set_up_sap_hana() {
    /bin/rm -rf $DATADIR
    mkdir -p $DATADIR
    cat <<EOF >$DATADIR/$JSON_FILE
{
    "master_password" : "${DATABASE_PASSWORD-P455w0rd}"
}
EOF

    if [ "$(id -u)" -eq 0 ]; then
        chmod ugo=rw $DATADIR/$JSON_FILE
        chown ${SAP_UID-12000}:${SAP_GID-79} $DATADIR/$JSON_FILE
    fi
}

script_basename="$(basename "$0")"
script_dirname="$(get_realpath "$(dirname "$0")")"

. "$script_dirname/sap-hana-config.sh"

if [ -r $ENV_FILE ]; then
    . $ENV_FILE
fi

set_up_sap_hana
