#!/bin/sh -eu

# set-up-tunnel: set up IP forwarding tunnel using iptables
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

NETWORK=10.10.0.0/23

iptables -t nat -A POSTROUTING -s $NETWORK -j MASQUERADE  
iptables -A FORWARD -s $NETWORK -j ACCEPT
iptables -A FORWARD -d $NETWORK -j ACCEPT
echo 1 | sh -c "cat >/proc/sys/net/ipv4/ip_forward"
echo 1 | sh -c "cat >/proc/sys/net/ipv4/conf/all/proxy_arp"
