#!/bin/sh -eu

# software-properties: invoke software properties dialog
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

realpath() {
    assert [ -d "$1" ]

    if [ -x /usr/bin/realpath ]; then
	/usr/bin/realpath "$1"
    else
	if expr "$1" : '/.*' >/dev/null; then
	    printf "%s\n" "$1"
	else
	    printf "%s\n" "$PWD/${1#./}"
	fi
    fi
}

realpath() {
    if [ -x /usr/bin/realpath ]; then
	/usr/bin/realpath "$@"
    else
	if expr "$1" : '/.*' >/dev/null; then
	    printf "%s\n" "$1"
	else
	    printf "%s\n" "$PWD/${1#./}"
	fi
    fi
}

script_dir=$(realpath "$(dirname "$0")")
desktop_name=$(sh -eu $script_dir/get-desktop-name)
distro_name=$(sh -eu $script_dir/get-os-distro-name)
kernel_name=$(sh -eu $script_dir/get-os-kernel-name)

if [ -z "${DISPLAY:-}" ]; then
    abort "No DISPLAY variable set\n"
fi

if [ -z "${desktop_name:-}" ]; then
    abort "Desktop not specified\n"
fi

case "$kernel_name" in
    (Linux)
	case "$distro_name" in
	    (debian)
		case "$desktop_name" in
		    (GNOME*|*:GNOME)
			software-properties-gtk
			;;
		    (KDE*)
			software-properties-kde
			;;
		    (MATE)
			software-properties-gtk
			;;
		    (*)
			abort "%s: Desktop not supported\n" "$desktop_name"
			;;
		esac
		;;
	    (ubuntu)
		case "$desktop_name" in
		    (GNOME*|*:GNOME)
			software-properties-gtk
			;;
		    (KDE*)
			software-properties-kde
			;;
		    (MATE)
			software-properties-gtk
			;;
		    (*)
			abort "%s: Desktop not supported\n" "$desktop_name"
			;;
		esac
		;;
	    (*)
		abort "%s: Distro not supported\n" "$distro_name"
		;;
	esac
	;;
    (*)
	abort "%s: Operating system not supported\n" "$kernel_name"
	;;
esac
