#!/bin/bash -eu

# start-oracle-databases: start Oracle databases
# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
}

cat_sql_startup() {
    cat <<EOF
CONNECT / AS SYSDBA;
STARTUP;
SELECT value FROM v\$parameter WHERE name='service_names';
EXIT;
EOF
}

get_logfile() {
    assert [ $# -eq 2 ]
    assert [ -n "$1" ]
    assert [ -n "$2" ]
    printf '%s/start-%s.log\n' "$1" "$2"
}

parse_arguments() {
    databases=

    if [ $# -gt 0 ]; then
	databases="$@"
    fi
}

start_database() {
    assert [ $# -eq 1 ]
    assert [ -n "$1" ]
    export ORACLE_SID=$(get_system_id "$1")
    logfile=$(get_logfile "$HOME" "$ORACLE_SID")
    print_info "Starting SID $ORACLE_SID"
    cat_sql_startup | sqlplus /nolog | \
	tee $logfile | filter_sqlplus

    if grep -q "^Database opened." $logfile; then
	print_info "SID $ORACLE_SID started"
	status=0
    else
	print_error "SID $ORACLE_SID startup failed"
	print_error "Check $logfile for errors"
	status=1
    fi

    return $status
}

start_databases() {
    : ${ORACLE_BASE?}
    : ${ORACLE_HOME?}
    : ${ORACLE_PWD?}
    unset TWO_TASK
    check_dirs

    for database; do
	start_database "$database"
    done
}

script_basename=$(basename "$0")
script_dirname=$(realpath "$(dirname "$0")")

. "$script_dirname/oracle-config.sh"
. "$script_dirname/oracle-library.sh"

parse_arguments "$@"
start_databases ${databases:-$DATABASES}
